### ISSUE TITLE
QuestID: 26674 - Mistmantle's Revenge

### ISSUE THREAD

**Issue by brownbr** [Thordekk/Dekk-Core-Donator-Bugtracker#1]
When using the item Mistmantle Family Ring [ItemID=59363] At Manor Mistmantle, animation plays of a self-cast but nothing happens after that. Have tried inside and outside house, on top of the object in the ground labelled Manor Mistmantle, Stalvan Mistmantle does not appear

**Comment by Thordekk** [comment]
Fixed
