### ISSUE TITLE
Ambassador Blackguard

### ISSUE THREAD

**Issue by Gargash** [Thordekk/Dekk-Core-Donator-Bugtracker#100]
Ambassador Blackguard has wrong phase flag as he is present with .gm on but phases out in .gm off

https://www.wowhead.com/npc=133407/ambassador-blackguard

Also missing link to For the Horde Quest Completion
https://www.wowhead.com/quest=58122/for-the-horde
Quest ID in DB is 51485

Also missing stranger in a strange land
https://www.wowhead.com/quest=58124/stranger-in-a-strange-land

**Comment by Thordekk** [comment]
Fixed flags
