### ISSUE TITLE
Chromie Missing Orgrimmar

### ISSUE THREAD

**Issue by Gargash** [Thordekk/Dekk-Core-Donator-Bugtracker#101]
Missing Chromie in Orgrimmar for Vulpera starting quest line.

NPC
https://www.wowhead.com/npc=167032/chromie

Quests missing 
https://www.wowhead.com/quest=60123/burning-crusade-to-outland
https://www.wowhead.com/quest=60961/burning-crusade-onward-to-adventure-in-outland

Completes in DB as 60959

**Comment by Thordekk** [comment]
Spawned
