### ISSUE TITLE
The support creche

### ISSUE THREAD

**Issue by ipro4911** [Thordekk/Dekk-Core-Donator-Bugtracker#1019]
Quest id https://www.wowhead.com/quest=65063/into-the-hive doesnt have corpse of Viridia and its just stuck

it should be able to spawn like phase of corpse of viridia
![image](https://github.com/Thordekk/Dekk-Core-Donator-Bugtracker/assets/105972244/42fadf95-d607-46eb-8386-e2d0b5121687)

**Comment by Thordekk** [comment]
Tested and working follow npc
