### ISSUE TITLE
Azure span quest

### ISSUE THREAD

**Issue by KamiNoEnd** [Thordekk/Dekk-Core-Donator-Bugtracker#1028]
https://www.wowhead.com/quest=72784/supporting-the-cobalt-assembly can't be completed as Venthi doesn't have a quest tag
![image](https://github.com/Thordekk/Dekk-Core-Donator-Bugtracker/assets/49670986/10a7913e-2ead-4568-a310-610886568911)

**Comment by Thordekk** [comment]
Fixed
