### ISSUE TITLE
Forbidden reach / The old wyern grounds 

### ISSUE THREAD

**Issue by ipro4911** [Thordekk/Dekk-Core-Donator-Bugtracker#1030]
Quest https://www.wowhead.com/quest=65057/rally-to-emberthal cant be completed cuz game tells u to use optional soar enchancher but doesnt teleport u back and when u try any other way doesnt count as credit
![image](https://github.com/Thordekk/Dekk-Core-Donator-Bugtracker/assets/105972244/0177b84f-11c2-4594-b936-56ca4abb2af9)
![image](https://github.com/Thordekk/Dekk-Core-Donator-Bugtracker/assets/105972244/1e3443ed-3b56-486a-92ed-0394a81e25a8)

**Comment by Korsar1808** [comment]
<img width="323" alt="image" src="https://github.com/Thordekk/Dekk-Core-Donator-Bugtracker/assets/59765795/4ef3b399-f987-40d6-b720-30422531d2ba">

**Comment by Korsar1808** [comment]
sorry find any issus.For me work :)
