### ISSUE TITLE
Valdrakken quest

### ISSUE THREAD

**Issue by KamiNoEnd** [Thordekk/Dekk-Core-Donator-Bugtracker#1032]
https://www.wowhead.com/quest=67074/the-gift-of-silver gossips don't work.

![image](https://github.com/Thordekk/Dekk-Core-Donator-Bugtracker/assets/49670986/10566ac0-14e1-4d72-bca0-e7005d93b4a6)

**Comment by Thordekk** [comment]
Fixed
