### ISSUE TITLE
Bug quest 53500 Terra incognita

### ISSUE THREAD

**Issue by Steyfix** [Thordekk/Dekk-Core-Donator-Bugtracker#1033]
https://www.wowhead.com/fr/quest=53500/terra-incognita

The quest cannot be validated by speaking to Chromie

**Comment by Korsar1808** [comment]
<img width="535" alt="image" src="https://github.com/Thordekk/Dekk-Core-Donator-Bugtracker/assets/59765795/448c4cb9-38ca-4a76-ba09-e2893e6ad671">

**Comment by Korsar1808** [comment]
Sorry find  no issus.Quest work
