### ISSUE TITLE
Gameobject interface bug

### ISSUE THREAD

**Issue by Steyfix** [Thordekk/Dekk-Core-Donator-Bugtracker#1034]
![WoWScrnShot_101223_221326](https://github.com/Thordekk/Dekk-Core-Donator-Bugtracker/assets/12504219/d7906b55-ff06-4e2b-ae6a-448b524ba2d7)
As we can see on the screen, the hero board interface is not good. gameobject id: 281339

**Comment by Thordekk** [comment]
Fixed
