### ISSUE TITLE
Rally to Emberthal

### ISSUE THREAD

**Issue by ajosuecr** [Thordekk/Dekk-Core-Donator-Bugtracker#1035]
https://www.wowhead.com/quest=65057/rally-to-emberthal

soar is bug

**Comment by Thordekk** [comment]
work for me why is bug?

**Comment by ajosuecr** [comment]
se probo y no hace ninguna acción bro

**Comment by Thordekk** [comment]
https://gyazo.com/340780fdc5575a12d90c42855f392255 soar luego doble salto y recuerden equipar las habilidades del dragonriding
