### ISSUE TITLE
NPC issue

### ISSUE THREAD

**Issue by ipro4911** [Thordekk/Dekk-Core-Donator-Bugtracker#1038]
the NPC chromie

![image](https://github.com/Thordekk/Dekk-Core-Donator-Bugtracker/assets/105972244/346194a0-12a1-46d3-96a2-bba4f52f608d)
https://www.wowhead.com/npc=167032/chromie

doesnt give u any timeline to select as mission

**Comment by Thordekk** [comment]
Chromie timelines are for levels -60 😂

**Comment by ipro4911** [comment]
Oh wao didnt know thought was a bug not a feature sry
