### ISSUE TITLE
De Other Side - Manastorms Duo is Friendly

### ISSUE THREAD

**Issue by ShadowTommy536** [Thordekk/Dekk-Core-Donator-Bugtracker#104]
https://www.wowhead.com/npc=101976/millificent-manastorm and his partner Milhaus are Friendly in the Dungeon "De Other Side"

I played it on Mythic and also realised, that the Item Level that drops there, is still on 184, like to Patch 9.0.2

**Comment by Thordekk** [comment]
Corrected faction thanks for report
