### ISSUE TITLE
Evoker Spell

### ISSUE THREAD

**Issue by ipro4911** [Thordekk/Dekk-Core-Donator-Bugtracker#1040]
![image](https://github.com/Thordekk/Dekk-Core-Donator-Bugtracker/assets/105972244/387c2a8b-7d8b-4925-9bc4-b3a1b2f06dc7)
https://www.wowhead.com/spell=375087/dragonrage
this when tryign to use crashes server or dc u so it doesnt even finish animation

**Comment by Thordekk** [comment]
https://gyazo.com/346b7479c50cf0b49a2b072d217873fd no crash
