### ISSUE TITLE
Damage on the boat to Dragon Island

### ISSUE THREAD

**Issue by Steyfix** [Thordekk/Dekk-Core-Donator-Bugtracker#1059]
Hello, taking the quest https://www.wowhead.com/fr/quest=67700/direction-les-%C3%AEles-aux-dragons and getting on the boat I am attacked by an invisible creature. I am attaching the screenshot of the combat log.

![image](https://github.com/Thordekk/Dekk-Core-Donator-Bugtracker/assets/12504219/49615f91-a7c4-4b75-a3e2-737481dae3a3)

**Comment by ahoffman1** [comment]
fixed
