### ISSUE TITLE
Northern Barrens - NPCS Issue

### ISSUE THREAD

**Issue by KKBa20** [Thordekk/Dekk-Core-Donator-Bugtracker#1069]
These npcs cast unnecessary spells at your player with insane damage -

https://www.wowhead.com/npc=3242/zhevra-runner
https://www.wowhead.com/npc=3244/greater-plainstrider
https://www.wowhead.com/npc=3246/fleeting-plainstrider
https://www.wowhead.com/npc=3272/kolkar-wrangler
https://www.wowhead.com/npc=3939/razormane-wolf
https://www.wowhead.com/npc=4316/kolkar-packhound
https://www.wowhead.com/npc=3248/barrens-giraffe

![WoWScrnShot_102023_222145](https://github.com/Thordekk/Dekk-Core-Donator-Bugtracker/assets/129208594/9ed2b3b8-e4cf-42f5-94b1-f299bff7af0e)
![WoWScrnShot_102023_222413](https://github.com/Thordekk/Dekk-Core-Donator-Bugtracker/assets/129208594/221c0c64-ec21-403a-9079-baf6fa182e5a)
![WoWScrnShot_102023_223113](https://github.com/Thordekk/Dekk-Core-Donator-Bugtracker/assets/129208594/a02edf7f-5860-4aef-93dd-9ef247ece88c)
![WoWScrnShot_102023_223120](https://github.com/Thordekk/Dekk-Core-Donator-Bugtracker/assets/129208594/9cd6d7df-8492-43f8-b0a5-8bfc443220c4)
![WoWScrnShot_102023_223448](https://github.com/Thordekk/Dekk-Core-Donator-Bugtracker/assets/129208594/5d42b8bc-9f76-4847-b85b-252f890a656e)
![WoWScrnShot_102023_223748](https://github.com/Thordekk/Dekk-Core-Donator-Bugtracker/assets/129208594/b0c0b576-5685-4008-b9bf-f0ae015e3e98)

**Comment by Thordekk** [comment]
Fixed
