### ISSUE TITLE
Bugs from the new Repack

### ISSUE THREAD

**Issue by ShadowTommy536** [Thordekk/Dekk-Core-Donator-Bugtracker#107]
Overall, 2 Dungeons entrances are working now:
• https://www.wowhead.com/spires-of-ascension
• https://www.wowhead.com/de-other-side
- https://www.wowhead.com/sanguine-depths Portal Entrance/Exit isn't working.
- https://www.wowhead.com/theater-of-pain Portal Entrance/Exit isn't working.
The other entraces are not working.
But most of the bosses are bugged, like mentioned in the "De other side" Issues..
The Raid entrances for Nathria is for example not working, even if you use LFR, they port you into the Void and maybe kill you, like in the Sanctum of Domination.

The Portal to Oribos is still unavailable.

**Comment by Thordekk** [comment]
POrtal to oribos need delete template addon of gob i check boss in short

**Comment by Thordekk** [comment]
Fixed
