### ISSUE TITLE
Interfaz de ticket y hermandades bug

### ISSUE THREAD

**Issue by ajosuecr** [Thordekk/Dekk-Core-Donator-Bugtracker#1071]
las hermandades no se pueden ni inscribir y si se hace con el comando de gm no se puede invitar a gente y no deslaza información la asistencia al jugador no muestra opciones  y osea que los jugadores no puede realizar sus tickets para solicitar ayuda del staff

**Comment by Thordekk** [comment]
Imposible de reparar la interfaz las hermandades funcionan con el comando perfectamente
