### ISSUE TITLE
Broken quests

### ISSUE THREAD

**Issue by Nokreb** [Thordekk/Dekk-Core-Donator-Bugtracker#108]
Fixed - Does not have NPC for challenge
https://www.wowhead.com/quest=12733/deaths-challenge#videos 
![image](https://user-images.githubusercontent.com/13070265/167194408-e38f28af-4441-4c74-9dc6-af0989d9e46a.png)

**Comment by Nokreb** [comment]
Curly is missing - https://www.wowhead.com/npc=163007/curly
https://www.wowhead.com/quest=58908/finding-your-way
![image](https://user-images.githubusercontent.com/13070265/167197383-c926c3af-ac1b-49eb-aee2-5d973002b0e2.png)

**Comment by Nokreb** [comment]
Quest 58902 - cant take quest from board and complete quest
https://www.wowhead.com/quest=58902/defender-of-azeroth
![image](https://user-images.githubusercontent.com/13070265/167197926-3ed8e397-fde6-4eb5-875a-5351546fa916.png)

**Comment by Nokreb** [comment]
Quest 29547 - can't complete quest and several strange NPC near table
https://www.wowhead.com/quest=29547/the-kings-command
![image](https://user-images.githubusercontent.com/13070265/167204429-41d8987a-0475-4209-a544-990322d337d1.png)

**Comment by Thordekk** [comment]
All fixed tested now
