### ISSUE TITLE
Disappearance of pnj 156595

### ISSUE THREAD

**Issue by Steyfix** [Thordekk/Dekk-Core-Donator-Bugtracker#1081]
Hello after finishing the quest id 55879 I change phase correctly but on the other hand the NPC of the wild boar of the quest remains spawned. So you would have to make it disappear when you return the quest or when the first objective of the quest is completed.

https://www.wowhead.com/fr/quest=55879/la-chevauch%C3%A9e-du-sanglier-scientifiquement-modifi%C3%A9

![WoWScrnShot_102323_210528](https://github.com/Thordekk/Dekk-Core-Donator-Bugtracker/assets/12504219/0a2d2eeb-0851-4823-a5d7-87f511a626a8)

**Comment by Thordekk** [comment]
Exiles being full rewrited by flux
