### ISSUE TITLE
npc not in the right phase

### ISSUE THREAD

**Issue by Steyfix** [Thordekk/Dekk-Core-Donator-Bugtracker#1082]
hello as we can see on my screen the npc id 167212 is not in the right phase, he is currently in the alliance quest phase while he should be in the horde phase.
![WoWScrnShot_102323_211458](https://github.com/Thordekk/Dekk-Core-Donator-Bugtracker/assets/12504219/936757dc-384d-4cd4-bd9e-03f16ab89252)

**Comment by Thordekk** [comment]
Exiles being full rewrited by flux
