### ISSUE TITLE
quest 58915 check conditions

### ISSUE THREAD

**Issue by Steyfix** [Thordekk/Dekk-Core-Donator-Bugtracker#1083]
The quest https://www.wowhead.com/fr/quest=58915/la-derni%C3%A8re-ex%C3%A9cution-de-hjalmar given by the njp id 162943 gives the quest to everyone while only warriors should be able to have it.

![WoWScrnShot_102323_221943](https://github.com/Thordekk/Dekk-Core-Donator-Bugtracker/assets/12504219/98866560-dd1f-47c2-b030-c97cf91c27d9)

**Comment by Thordekk** [comment]
Exiles being full rewrited by flux
