### ISSUE TITLE
Review the continuation of the end of exile quest

### ISSUE THREAD

**Issue by Steyfix** [Thordekk/Dekk-Core-Donator-Bugtracker#1084]
I am currently with quest 55981 which is completing well but I cannot return it with NPCs who should not appear in this phase and the NPC I need who is not in the same phase as me.

![WoWScrnShot_102323_223556](https://github.com/Thordekk/Dekk-Core-Donator-Bugtracker/assets/12504219/06dff40f-9285-4437-a9fa-cb9363a0c46e)

**Comment by Thordekk** [comment]
Exiles being full rewrited by flux
