### ISSUE TITLE
World Quest bosses NPC

### ISSUE THREAD

**Issue by ipro4911** [Thordekk/Dekk-Core-Donator-Bugtracker#1085]
![image](https://github.com/Thordekk/Dekk-Core-Donator-Bugtracker/assets/105972244/55fa1bfa-bc8e-406c-83f4-43f891342b16)
![image](https://github.com/Thordekk/Dekk-Core-Donator-Bugtracker/assets/105972244/c92d682a-a990-41b3-b04a-204bc62201bd)

Sometime when u kill one of them for world quest it makes game like bugged cant even log out like it got frozen like doing 2+ at once probably world quest name dragonhunter igordan

**Comment by Thordekk** [comment]
Fixed
