### ISSUE TITLE
Horde Warlock Quest In Exile's reach not being offered by NPC

### ISSUE THREAD

**Issue by Wootenblatz** [Thordekk/Dekk-Core-Donator-Bugtracker#109]
A Warlock's Bargain is the quest that gives warlocks their Summon Voidwalker spell in Exile's reach.

The Horde quest ID is [59970](https://www.wowhead.com/quest=59970/a-warlocks-bargain).  I did not test the alliance version but that quest ID is [58962](https://www.wowhead.com/quest=58962/a-warlocks-bargain)

[Grunt Throg](https://www.wowhead.com/npc=167216/grunt-throg) is the Horde NPC that is supposed to start this quest chain.   I used **.quest add 59970** to pick the quest up and went to the place where one would interact with the [dead NPC](https://www.wowhead.com/npc=167478/sprag-buzzboom) but it was missing.

Here is a screenshot of the NPC that gives this quest for Horde Warlocks
![WoWScrnShot_051922_194443](https://user-images.githubusercontent.com/64573/169435026-6aeabc7b-b9b8-4848-8a53-49d1b9029eab.jpg)

This is where the dead NPC should show up
![WoWScrnShot_051922_194357](https://user-images.githubusercontent.com/64573/169435097-269cfb81-4275-452d-94c0-cb2dbd56a1bf.jpg)

**Comment by Thordekk** [comment]
added
