### ISSUE TITLE
Twilight Encroacher NPC

### ISSUE THREAD

**Issue by KKBa20** [Thordekk/Dekk-Core-Donator-Bugtracker#1090]
When these npcs cast their spell on you, the spell seems to spawn and be an extreme high level, which gives massive damage to your player.

https://www.wowhead.com/npc=44729/twilight-encroacher
https://www.wowhead.com/spell=78160/twilight-fissure

![WoWScrnShot_102423_232819](https://github.com/Thordekk/Dekk-Core-Donator-Bugtracker/assets/129208594/b0e6e84f-cd74-4f83-8a3b-39d94ad3a1a6)

**Comment by Thordekk** [comment]
Fixed
