### ISSUE TITLE
Abalorios, encantamientos y spell Bugs.

### ISSUE THREAD

**Issue by Locuraa** [Thordekk/Dekk-Core-Donator-Bugtracker#1098]
Buenas, casi todos los abalorios. no activan las habilidades de la descripción de cada uno. Solo hacen la animación y no otorga nada.
También los encantamientos todos no funcionan no dan lo que dice su descripción.
El poder del chamán hendimiento y toten de viento furioso están bug.
El poder del dk furia de vernis de escarcha tampoco funciona.

**Comment by Thordekk** [comment]
REporte invalido sin ids o links
