### ISSUE TITLE
Worldquest bugs the character

### ISSUE THREAD

**Issue by Northernn** [Thordekk/Dekk-Core-Donator-Bugtracker#1100]
Crashes the client with buffer overrun.

https://www.wowhead.com/quest=53319/our-sacred-forest

Remove it from the characters -> character_queststatus to fix the character

Breaks again if you venture into the worldquest area 

Example is to fly from darkshore to moonglade, it will crash, then when you try and log in it will crash until you remove it from the character database, then you can log in again.

Logging it to remember to look into it! 
![darkshire-client-crash](https://github.com/Thordekk/Dekk-Core-Donator-Bugtracker/assets/67755436/afac5aa6-d11c-483c-8169-8c22854268cf)

**Comment by Thordekk** [comment]
Fixed
