### ISSUE TITLE
Various Broken quests so far.

### ISSUE THREAD

**Issue by JamesMCarlson** [Thordekk/Dekk-Core-Donator-Bugtracker#1108]
Trolling for information - completely bugged
frostmane troll whelps unattackable.
The troll menace - bugged because whelps unattackable
Ice And fire - bugged because Grik'nir the cold and Wayward fire elemental unattackable
Pack Your bags - Quest window dialog in another language.

**Comment by Korsar1808** [comment]
<img width="223" alt="image" src="https://github.com/Thordekk/Dekk-Core-Donator-Bugtracker/assets/59765795/e46aaa4f-587a-4fe4-ab94-415ca0f441fa">

can attack frostmane
<img width="243" alt="image" src="https://github.com/Thordekk/Dekk-Core-Donator-Bugtracker/assets/59765795/f37b1caa-5b7d-4214-9f9e-4402b4706037">
quest trolling infomation run
