### ISSUE TITLE
Exile Rach Party Bugs

### ISSUE THREAD

**Issue by eXPeRi91** [Thordekk/Dekk-Core-Donator-Bugtracker#111]
The entire map Exile Reach is bugged.
What I mean if you accept Quest that belong in personal spawn, you are phasing with your party and/or most of the time the map update with all player on that place even if they are not in your party.
Example on few quest where "Personal Spawn" have to be personal:

1. https://www.wowhead.com/quest=59254 Here you have to practice with Captain Garrick, but if you are on party you have to wait cause you can't engage the fight, if someone was accept the quest first (You will see the entire fight) after your party member finish the fight you have to abandon the quest and re-accept it, in order to complete it. (server crash here unknown cause) https://pastebin.com/41zY7NDH
2. https://www.wowhead.com/quest=55173 Here the server crashed again as soon as we reach "Austin Huxworth" https://pastebin.com/JUr1WeVN (Personal pool and Smooth phasing) after restart it was good.
3. https://www.wowhead.com/quest=55184 on this quest the NPC's that you have to kill "Quilboar Warrior" and "Quilboar Geomancer" they have too big pull box range, you can see on this video: [VIDEO](https://youtu.be/yjEoKGwxuCY?t=574) their pull box is like close to them, but in this core they can see you from 40 foots away...
4. https://www.wowhead.com/quest=55193 Here, me and my party were able to take the quest, but I was the only one who were able to turn the quest, my party didn't saw this gnome to turn the quest.
5. https://www.wowhead.com/quest=56034 this quest do not work, the phase is wrong, all the spawns are missing...

That was the last quest where we can go up.
After this point we had to delete our characters, they was stuck in other phase.

There is other bug:
Horde & and Alliance are using the same map, but they are not supposed to see each other.
Screenshots 
Horde side: https://postimg.cc/18z4wT5p
Alliance side: https://postimg.cc/BPGXFnX6

On the ship (The few first quests) there also with wrong phases...
You need to revise the entire map to be playable, not only one side.

**Comment by Feldevil** [comment]
Quest Catapult Destruction(Horde) Does not work. https://www.wowhead.com/quest=59980/catapult-destruction

**Comment by fluxurion** [comment]
Who can help me with testing in party

**Comment by eXPeRi91** [comment]
> Who can help me with testing in party

Just login with 2nd account, actually it's not only this zone all quest with personal spawn are bugged for party.
