### ISSUE TITLE
Demon hunter starting zone

### ISSUE THREAD

**Issue by Feldevil** [Thordekk/Dekk-Core-Donator-Bugtracker#112]
WHen trying to open the map in the Demon hunter starting zone i get Error 132.
[SCREENSHOT](https://gyazo.com/8964aa97c6b60437fc9838c1bbb8676b)

**Comment by Feldevil** [comment]
When you start as Demon hunter  You are learning all your riding skills. 
[SCREENSHOT](https://gyazo.com/c072bf3b2caed5c02b3d36a9acfc16b5)

**Comment by Thordekk** [comment]
> When you start as Demon hunter You are learning all your riding skills. [SCREENSHOT](https://gyazo.com/c072bf3b2caed5c02b3d36a9acfc16b5)

is custom feature u can disable

**Comment by fluxurion** [comment]
Riding skill and wowerror bug fixed

**Comment by Thordekk** [comment]
Fixed by flux
