### ISSUE TITLE
Classic Dungeons Bugs

### ISSUE THREAD

**Issue by Feldevil** [Thordekk/Dekk-Core-Donator-Bugtracker#113]
Shadowfang Keep Dungeon- Does not scale with the players level. [Screenshot](https://gyazo.com/0013dcb86c79117b9f12ce859705131c). Both Faction NPC`s for the dungeon are present at the start of the dungeon and they are attacking [SCREENSHOT](https://gyazo.com/b7a86743fa8bfd4d8d34fd68a952c592) . After the first boss is killed the door should be opened. It is not [Screenshot](https://gyazo.com/89f4034dfd6f7c5878576e89552cfc61).  The door for the last boss does not open. [Screenshot](https://gyazo.com/92bc72522487bef5d9b8abfaa96f5fc6)

**Comment by Feldevil** [comment]
Ragefire Chasm Dungeon- Does not scale with the player Level [Screenshot](https://gyazo.com/db5480a551d0d84f1c77cbeb46a3b1b5). Quest [No Orc Left Behind](https://www.wowhead.com/quest=30984/no-orc-left-behind) Broken. The NPC`s are utargetable and can not be saved.

**Comment by Feldevil** [comment]
Wailing Caverns Dungeon- The last boss [Mutanus the Devourer](https://www.wowhead.com/npc=3654/mutanus-the-devourer) is spawned from the start of the dungeon.  Mutanus the Devourer is spawned after successfully escorting the [Disciple of Naralex](https://www.wowhead.com/npc=3678) through Wailing Caverns once the four Fanglords have been defeated. Players will fight through multiple waves of raptors, until eventually reaching a stone altar at waterfront, where the Disciple will begin channeling a spell in an attempt to free [Naralex](https://www.wowhead.com/npc=3679) from the Emerald Dream. Once players have defeated a few waves of mobs, the mighty murloc boss Mutanus will rise from the depths to battle.

**Comment by Feldevil** [comment]
Blackfathom deeps. The NPC`s are not scaling. Both Faction NPC`s for the dungeon are present at the start of the dungeon and they are attacking[Screenshot](https://gyazo.com/e8f7eca1ef987f8fc99d1fd424e686d9).

**Comment by Korsar1808** [comment]
Fix
