### ISSUE TITLE
Server "break" caused by GM Command

### ISSUE THREAD

**Issue by jadedprophet** [Thordekk/Dekk-Core-Donator-Bugtracker#116]
The GM command ".learn all languages" can cause the server to "break" .. the only way to somewhat fix it is to go into character db and delete the character it was used on and then the server seemed to work fine again.

**Comment by Thordekk** [comment]
why u need learn all languages?

**Comment by jadedprophet** [comment]
I didn’t and I’m not the one that used it. A friend that I gave gm status
to thought it would be good to know all the languages but changed his mind
after it caused server issues.

**Comment by fluxurion** [comment]
no probs maybe it's teach some deprecated language im gonna check

**Comment by jadedprophet** [comment]
The Learn all languages command is to give the player the ability to
understand all the languages used in the game. It's not really needed.
There are addons that can do the same thing without the command being used.
