### ISSUE TITLE
Webwood Corruption

### ISSUE THREAD

**Issue by justSelim** [Thordekk/Dekk-Core-Donator-Bugtracker#119]
Quest is working as intended but the Quest-NPC Population is pretty low and the NPC to End the Quest is missing. 

Quest: https://www.wowhead.com/quest=28726/webwood-corruption
Quest NPC: https://www.wowhead.com/npc=1986/webwood-spider
Quest End: https://www.wowhead.com/npc=49480/tarindrella

**Comment by Korsar1808** [comment]
fix
