### ISSUE TITLE
[Quest] Vile Touch 

### ISSUE THREAD

**Issue by justSelim** [Thordekk/Dekk-Core-Donator-Bugtracker#120]
Quest Start NPC and Quest End NPC is missing and Quest NPC is missing.

Quest Start: https://www.wowhead.com/npc=49480/tarindrella
Quest End: https://www.wowhead.com/npc=49480/tarindrella
Quest NPC: https://www.wowhead.com/npc=1994/githyiss-the-vile

**Comment by DruidazZo** [comment]
Fixed thx for report
