### ISSUE TITLE
[Quest] Signs of Things to Come

### ISSUE THREAD

**Issue by justSelim** [Thordekk/Dekk-Core-Donator-Bugtracker#121]
Quest Start NPC is missing so quest is not acceptable

Quest Start: https://www.wowhead.com/npc=49480/tarindrella
Quest: https://www.wowhead.com/quest=28728/signs-of-things-to-come

**Comment by Korsar1808** [comment]
FIX

**Comment by Korsar1808** [comment]
> Quest Start NPC is missing so quest is not acceptable
> 
> Quest Start: https://www.wowhead.com/npc=49480/tarindrella Quest: https://www.wowhead.com/quest=28728/signs-of-things-to-come

#
