### ISSUE TITLE
[Quest] Nature's Reprisal

### ISSUE THREAD

**Issue by justSelim** [Thordekk/Dekk-Core-Donator-Bugtracker#125]
Quest is complete-able but after a long time because Quest NPCs are not well spawned 

Quest: https://www.wowhead.com/quest=13946/natures-reprisal
Quest NPC: 
https://www.wowhead.com/npc=2003/shadow-sprite, https://www.wowhead.com/npc=2002/rascal-sprite, https://www.wowhead.com/npc=2004/dark-sprite 
https://www.wowhead.com/npc=2005/vicious-grell

**Comment by Korsar1808** [comment]
fix
