### ISSUE TITLE
[Quest] Resident Danger 

### ISSUE THREAD

**Issue by justSelim** [Thordekk/Dekk-Core-Donator-Bugtracker#127]
Quest NPCs are not well spawned in Zone Ban'ethil Barrow Den

Quest: https://www.wowhead.com/quest=13945/resident-danger

Quest NPC:
https://www.wowhead.com/npc=2011/gnarlpine-augur
https://www.wowhead.com/npc=2010/gnarlpine-defender
https://www.wowhead.com/npc=2009/gnarlpine-shaman

Zone: https://www.wowhead.com/zone=262/banethil-barrow-den

**Comment by DruidazZo** [comment]
its a little issue with wander distance and collision. Fixed, and thx for report
