### ISSUE TITLE
[Quest] Threat from the Water

### ISSUE THREAD

**Issue by justSelim** [Thordekk/Dekk-Core-Donator-Bugtracker#130]
Quest is not acceptable because Quest Start NPC is missing/invisible see able in gm mode

Quest: https://www.wowhead.com/quest=13522/threat-from-the-water
Quest Start: https://www.wowhead.com/npc=32971/ranger-glynda-nalshea
Quest End: https://www.wowhead.com/npc=32971/ranger-glynda-nalshea

**Comment by DruidazZo** [comment]
The npc had an aura that made him invisible. Fixed thx for report.
