### ISSUE TITLE
[Quest] Bearer of Good Fortune

### ISSUE THREAD

**Issue by justSelim** [Thordekk/Dekk-Core-Donator-Bugtracker#133]
Quest drops from npcs but npcs are not spawned

Quest: https://www.wowhead.com/quest=13557/bearer-of-good-fortune
Quest Dropped Item: https://www.wowhead.com/item=44927/corruptors-master-key

Quest NPCs:
https://www.wowhead.com/npc=33022/vile-corruptor
https://www.wowhead.com/npc=33020/zenn-foulhoof

**Comment by justSelim** [comment]
2ND BUG

The Cages are able to open with the key but to complete the Quest you have to slain the Thistle Bears. This is not the same like in Retail

Here is a Video: https://www.youtube.com/watch?v=qTxEjI7b2Vk&feature=youtu.be

**Comment by Thordekk** [comment]
Fixed
