### ISSUE TITLE
[Quest] Ritual Materials

### ISSUE THREAD

**Issue by justSelim** [Thordekk/Dekk-Core-Donator-Bugtracker#135]
Quest NPCs are not "dropping" needed Quest Items

Quest: https://www.wowhead.com/quest=13566/ritual-materials
Quest NPCs: 

https://www.wowhead.com/npc=33127/moonstalker  <--- should be neutral but is aggro
https://www.wowhead.com/npc=33978/hungry-thistle-bear  <--- is neutral but not "dropping" item

**Comment by Thordekk** [comment]
https://www.wowhead.com/npc=33127/moonstalker is agro look at wowhead not neutral same for second npc both need to be agro But im on it fixed soon

**Comment by Thordekk** [comment]
Fixed
