### ISSUE TITLE
SL: Nilsa Vulpera Starter quest 'For The Horde' Missing

### ISSUE THREAD

**Issue by Xeliaa** [Thordekk/Dekk-Core-Donator-Bugtracker#141]
For All starting vulpera, For the horde Vulpera Starter is missing right at login point, NPC Nilsa

**Comment by Thordekk** [comment]
allways add wowhead link please

**Comment by Xeliaa** [comment]
> allways add wowhead link please

sorry i had to dig deep in to the Allied race quests to find it, as just typing for the horde it wont show.

https://www.wowhead.com/quest=58122/for-the-horde

**Comment by Korsar1808** [comment]
fix
