### ISSUE TITLE
All Spell Bugs We've Found

### ISSUE THREAD

**Issue by xXBentRealityXx** [Thordekk/Dekk-Core-Donator-Bugtracker#143]
- [ ] Warrior
  - General:
    - [x] Heroic Leap - 6544 - Does not jump nor damage as intended.
    - [x] All other abilities are working fine, including ignore pain now shields damage (this one might need a recheck tho, scaling really high)
    - [x] Does not learn execute uppon creation.
  - Arms:
    - [ ] Impending Victory - 202168 - Reduce healing from 40% to 5%
    - [ ] Second Wind - 29838 - Up at all times
    - [ ] Avatar - 1075774 - Does not increase damage done (20%)
    - [ ] Dreadnaught (talent) - 262150 - Not dealing AoE damage
    - [ ] Ravager - 152277 - produces effect but does no damage.
    - [ ] All other abilities and passives seem to be working fine.
  - Fury:
    - [x] Bloodthirst - 23881 - does not trigger heal nor enrage
    - [ ] Enrage - 184362 - does not correctly increase damage
    - [x] Sudden Death - 280721 - does not trigger
    - [ ] Frenzy - 335077 - does not trigger
    - [ ] Mastery - 76856 - Relate to Enrage 184362.
    - [ ] Furious Charge - 202224 - does not trigger (can't be tested as 23881 does not trigger heal)
    - [ ] All other abilities and passives seem to be working fine.
  - Protection:
    - [x] Last Stand - 12975 - Crashes the server
    - [ ] Devastator - 236279 - Not working properly (both damage and shield slam - 23922 - reset)
    - [ ] All other abilities and passives seem to be working fine. (albeist the ones that are affected by the above)

- [ ] Hunter
  - General:
    - [ ] Does not learn Call Pet 1 & Call Pet 2 on creation
    - [ ] Tame Beast, Dismiss Pet, Revive Pet, Mend Pet are missing on creation
    - [ ] Tar Trap - 187698 - not working.
  - Beast Mastery:
    - [x] Kill Command - 34026 - Does damage but doesn't show on recount
    - [ ] Barbed Shot - 217200 - Crashing Server
    - [ ] Animal Companion - 267116 - Not correctly calling your stabled pet as secondary pet
    - [ ] Spitting Cobra talent - 257891 - Not working correctly
    - [ ] Trailblazer - 199921 - Crashing the server
    - [ ] Stampede - 201430 - Not summoning any creatures
    - [ ] Stomp - 199530 - Unable to test as Barbed Shot crashes the server.
    - [ ] Bloodshed - 321530 - Not dealing any damage nor applying debuff.
  - Marksmanship:
    - [ ] Rapid Fire - 257044 - Does not shoot the shots.
    - [ ] Explosive Shot - 212431 - Does not deal any damage and instead summons a human running towards the target.
    - [ ] Steady Shot - 193533 - Not increasing Haste as intended.
    - [ ] Streamline - 260367 - Impossible to test as Rapid Fire is not working.
    - [ ] Chimaera Shot - 342049 - Does not deal any kind of damage.
    - [ ] Double Tap - 260402 - Not correctly working and consuming.
    - [ ] Lethal Shots - 260393 - Not correctly reducing the cooldown.
    - [ ] Lock and Load - 194595 - Not correctly making Aimed Shot instant or getting consumed.
    - [ ] Calling the Shots - 260404 - Not correctly reducing the cooldown of intended abilities.
  - Survival:
    - [ ] Kill Command - 259489 - Triggers the Tip of the Spear talent without it being chosen.
    - [ ] Kill Command - 259489 - Deals no damage.
    - [ ] Viper's Venom - 268552 - Does not get consumed after casting Serpent Sting.
    - [ ] Wildfire Bomb - 259495 - Deals no damage.
    - [ ] Coordinated Assault - 266779 - Doesn't seem to increase damage.
    - [ ] Terms of Engagement - 265895 - Deals no damage on Harpoon cast.
    - [ ] Alpha Predator - 269737 - Adds a charge but can't test for the Kill Command damage.
    - [ ] Guerrilala Tactics - 264332 - Adds a charge but can't test for Wildfire Bomb damage.
    - [ ] Hydra's Bite - 260241 - Not hitting additional targets.
    - [ ] Butchery - 212436 - Doesn't reduce cooldown on Wildfire Bomb.
    - [ ] Steel Trap - 162488 - Does not trigger any damage.
    - [ ] Bloodseeker - 260248 - Doesn't do damage nor does it buff.
    - [ ] Binding Shot - 109248 - Does not root enemies.
    - [ ] Flanking Strike - 269751 - Does no damage.
    - [ ] Birds of Prey - 260331 - Does not extend the duration on Coordinated Assault (266779)
    - [ ] Wildfire Infusion - 271014 - Doesn't seem to be doing anything.
    - [ ] Chakrams - 259391 - Do damage but have no visual effect.

- [ ] Mage
  - General:
    - [ ] Ice Block - 45438 - Shows an immune message.
    - [ ] Mirror Image - 55342 - Summons no mirror images.
  - Arcane:
    - [ ] Arcane Barrage - 44425 - Does not hit multiple target.
    - [ ] Slipstream - 236457 - Channel while moving not working.
    - [ ] Nether tempest - 144923 - Not applying on other creatures as intended.
    - [ ] Ring of Frost - 113724 - Not incapacitating creatures.
    - [ ] Arcane Orb - 153626 - Just goes through and does no damage.
    - [ ] Time Anomaly - 210805 - Not applying buff as intended even after a while in combat.
  - Fire:
    - [ ] Hot Streak - 48108 - Not working as intended, both cast and damage.
    - [ ] Blazing Soul - 235365 - Not igniting Blazing Barrier.
    - [ ] From the Ashes - 342344 - Not giving mastery as intended.
    - [ ] Alextrasza's Fury - 235870 - Not increasing the next ability damage.
    - [ ] Flame Patch - 205037 - Visual working, damage not there.
    - [ ] Meteor - 153561 - Visual on the floor works, no meteor falls and no damage.
    - [ ] Kindling - 155148 - Working too well, it cleanses the cooldown totally.
    - [ ] Pyroclasm - 269650 - Not working as intended.
  - Frost:
    - [ ] Bone Chilling - 205027 - Stacks 3x at a time instead of just 1.
    - [ ] Mastery - 76613 - Not storing icicles.
    - [ ] Frozen Orb - 84714 - Goes forward, does no damage.
    - [ ] Glacial Spike - 199786 - Since Mastery is not working this is not working either, can't cast.

- [ ] Rogue
  - Assassination:
    - [ ] Blindside - 328085 - Not making ambush free and usable without stealth.
    - [ ] Subterfuge - 108208 - Makes Stealth abilities usable at all times and can't enter stealth.
    - [ ] Leeching Poison - 280716 - Not adding Leech (Leech not working in the core?)
    - [ ] Exsanguinate - 200806 - Not working as intended, does not progress bleeds faster.
  - Outlaw:
    - [ ] Grappling Hook - 195457 - Not pulling you to target.
    - [ ] Roll the Bones - 315508 - Not buffing player
    - [ ] Blade Rush - 271877 - Does not charge at target
  - Subtlety:
    - [ ] Gloomblade - 200758 - Is Backstab instead.
    - [ ] Dark Shadow - 245687 - Not applying damage increase on shadow dance.
    - [ ] Secret Technique - 280719 - Does nothing.
    - [ ] Shuriken Tornado - 277925 - Does nothing.

- [ ] Priest
  - Discipline:
    - [ ] Sins of the Many - 280391 - Does not increase damage.
    - [ ] Divine Star - 110744 - Travels forward and doesn't come back, deals no damage.
  - Shadow:
    - [ ] Shadowy Apparitions - 341491 - Not working.
    - [ ] Void Eruption - 228260 - Not casting Void Form.
    - [ ] Unfurling Darkness - 341273 - Not working as intended.
    - [ ] Searing Nightmare - 341385 - Not working as intended.

- [ ] Warlock
  - General: 
    - [ ] Demonic Gateway - 111771 - Visual works, can't use.
    - [ ] Summon Sayaad - 366222 - Does not summon a demon.
    - [ ] Burning Rush - 111400 - Can not turn off the spell.
  - Affliction:
    - [ ] Malefic Rapture - 324536 - Not working correctly.
    - [ ] Seed of Corruption - 27243 - Does not pop Corruption on all targets when exploded.
    - [ ] Darkglare - 205180 - Does not deal damage as intended
    - [ ] Inevitable Demise - 334319 - Does not increase damage from Drain Life.
    - [ ] Nightfall - 108558 - Does not proc an instant cast.
  - Destruction:
    - [ ] Rain of Fire - 5740 - Does not do damage.
    - [ ] Havoc - 80240 - Not working as intended.
    - [ ] Channel Demonfire - 196447 - Can't be used.
  - Demonology:
    - [ ] Call Dreadstalkers - 104316 - Dreadstalkers do not attack.
    - [ ] Bilescourge Bombers - 267211 - Not working.
    - [ ] Nether Portal - 267217 - Calls no creatures.

- [ ] Paladin
  - Protection:
    - [ ] Blessed Hammer - 204019 - Has no visual
  - Retribution:
    - [ ] Crusade - 231895 - Once you reach max stacks it keeps refreshing the duration instead.

- [ ] Druid
  - General:
    - [ ] After getting into Flight Form and out the speed will remain.
  - Balance:
    - [x] Starfall - 191034 - Shows visual and does no damage.
    - [ ] New Moon - 274281 - Doesn't work properly, New Moon > Half Moon > Full Moon
    - [ ] Fury of Elune - 202770 - Does Nothing.
  - Feral:
    - [ ] Rip - 1079 - Not scaling with Combo Points.
    - [ ] Primal Wrath - 285381 - Not popping Rip on all targets.
    - [ ] Savage Roar - 52610 - Not scaling with Combo Points.
  - Guardian:
    - [ ] Pulverize - 80313 - Can not use as it does not consume Thrash Stacks.

- [ ] Shaman 
  - Elemental:
    - [ ] Echoing shock talent does not replicate the second spell as inteded
    - [ ] Passive mastery of the elements talent Procs from every spell and doesnt get consumed as inteded
    - [ ] Storm Elemental talent does command the creature to attack shamans targets and the aura the elemental casts on player is permanent
    - [ ] Fire Elemental does not attack nor provide the inteded aura needed.
    - [ ] Capacitor Totem does not cast the stun aoe as it was suposed to.
    - [ ] Liquid magma totem talent doesnt work as intended. Does not attack nor cast any aura upon enemies.
    - [ ] Mastery: Elemental Overload does not work correctly.
	
  - Enhancement:
    - [ ] Forceful Winds talent does not proc the aura that its suposed to.
    - [ ] Ice Strike does not reset the cooldown on frost shock or Flame Shock
    - [ ] Hot Hand talent increases the damage of lava lash but does not decrease its cooldown
    - [ ] Stormflurry talent doesnt work
    - [ ] Elemental assault talent increases stormstrike damage but doesnt give the maelstrom stack
    - [ ] Hailstorm Talent doesnt work 
    - [ ] Fire nova Talent doesnt work
    - [ ] Feral Lunge Talent has range issues, doesnt let you cast your spell due to out of range error
    - [ ] Crashing Storm Talent doesnt work correctly
    - [ ] Stormkeeper talent works, however the aura doesnt get consumed when chain lightning is cast
    - [ ] Sundering Talent has a issue where it doesnt recognize the target for casting the spell. Always gives "i have no target" error
    - [ ] Elemental Spirits talent reduces Feral Spirit spell's Cooldown, however it doesnt enhance your abilities as stated in talent description.
    - [x] Ascendance talent does not increase your auto-attack range by 30yards as stated nor enhances it with more damage

- [ ] Monk
  - General:
    - [ ] Fortifying Brew - 115203 - Does not increase HP correctly.
    - [ ] Transcendence - 101643 - Does not leave the spirit image hence Transfer doesn't work.
    - [ ] Zen Flight - 125883 - Allows flying everywhere even when not supposed to.
    - [x] Chi burst - 123986 - Deals no damage nor does it heal.
    - [ ] Chi wave - 115098 - Does damage once and does not jump as intended.
  - Brewmaster:
    - [ ] Breath of Fire - 115181 - Does not apply DoT
    - [ ] Celestial Brew - 322507 - 0 absorption shield.
    - [ ] Clash - 324312 - Does not charge to target.
    - [ ] Mastery: Elusive Brawler - 117906 - Since dodge doesn't seem to be working, spell doesn't get consumed.
    - [ ] Spitfire - 242580 - Not correctly reseting the cooldown of Breath of Fire.
    - [ ] Black Ox Statue - 115315 - Follows you and can summon multiple.
    - [ ] Special Delivery - 196730 - Doesn't work as intended.
    - [ ] Celestial Flames - 325177 - Not spawning Breath of Fire on spinning crane kick use.
    - [ ] Blackout Combo - 196736 - Every skill enables this buff when should be Blackout Kick only.
  - Mistweaver:
    - [ ] Invoke Yu'lon, the Jade Serpent - 322118 - Does not spawn Yu'lon nor does it heal.
  - Windwalker:
    - [x] Ring of Peace - 116844 - Does not keep enemies away as intended.
    - [ ] Hit Combo - 196740 - Not working correctly, doesn't add buff.
    - [ ] Whirling Dragon Punch - 152175 - Can't be used after requirement nor does it work.
    - [ ] Storm, Earth, and Fire - 137639 - Spawns 2 NPCs that do not attack
    - [ ] Touch of Karma - 122470 - Does not work as intended.

- [ ] Demon Hunter
  - General:
    - [ ] Lesser Soul Fragments are not spawned with abilities.
  - Havoc:
    - [ ] Glaive Tempest - 342817 - Deals no damage.
    - [ ] Soul Rending - 204909 - Leech not working
    - [ ] Essence Break - 258860 - Does not increase damage taken from abilities.
    - [ ] Demonic - 213410 - Has a visual effect bug.
    - [ ] Vengeful retreat is missing
  - Vengeance:	
    - [ ] Demon Spikes - 203720 - Is missing.
    - [ ] Infernal Strike - 189110 - Damages on cast and on landing when it should be only on landing.
    - [ ] Fiery Brand is missing
    - [ ] Spirit Bomb - 247454 - Does not work as no souls spawn.
    - [ ] Demonic - 321453 - Does not make you go into Metamorphosis.
    - [ ] Fracture - 263642 - Does not spawn souls.
    - [ ] Feed the Demons - 218612 - Demon spikes is missing and souls are not spawning.
    - [ ] Bulk Extraction - 320341 - Does not spawn Soul Fragments

- [ ] Death Knight
  - Blood:
    - [ ] Bone Shield - 195181 - Getting consumed by Blood Plague and stacks maximum up to 3.
    - [ ] Vampiric Blood - 55233 - Does not increase Maximum Health.
  - Frost:
    - [ ] Frostwyrm's Fury - 279302 - Does not summon the Frostwyrm.
    - [ ] Glacial Advance - 194913 - Triggers away from enemies (effect) does not do any damage.
  - Unholy:
    - [ ] Festering Strike - 85948 - Doesn't add Festering Wound.
    - [ ] Scourge Strike - 55090 - Has no festering Wound to burst still does AoE...
    - [ ] Apocalypse - 275699 - Can't be used without Festering Wounds.
    - [ ] All will serve - 194916 - Not summoning a second minion
    - [ ] Infected Claws - 207272 - Not applying festering wounds.
    - [ ] Defile - 152280 - Deals no damage but increases mastery instead??

**Comment by Thordekk** [comment]
Ok we check this week one by one

**Comment by Thordekk** [comment]
Kill Command - 34026 - Does damage but doesn't show on recount recount addon?

**Comment by Thordekk** [comment]
Heroic Leap - 6544 - Does not jump nor damage as intended. FIXED

**Comment by Thordekk** [comment]
spell warrior execute  is a level 10 warrior ability its added on level

**Comment by Thordekk** [comment]
Ascendance fixed

**Comment by Thordekk** [comment]
Kill Command Work is recount problem

**Comment by Thordekk** [comment]
Bloodthirst - 23881rewrited

**Comment by Thordekk** [comment]
Starfall  was missing at scriptname added now

**Comment by Thordekk** [comment]
Chi burst - 123986 was missing at scriptname added
