### ISSUE TITLE
Skill https://www.wowhead.com/spell=228477/soul-cleave

### ISSUE THREAD

**Issue by Shijing1489** [Thordekk/Dekk-Core-Donator-Bugtracker#159]
https://www.wowhead.com/spell=228477/soul-cleave does not inflict any damage. The healing part works.

**Comment by Thordekk** [comment]
Rewrited spell try in next update

**Comment by Shijing1489** [comment]
https://www.wowhead.com/spell=228477/soul-cleave is working now as intended.
