### ISSUE TITLE
Quest: https://www.wowhead.com/quest=38729/return-to-the-black-temple world server crash

### ISSUE THREAD

**Issue by Shijing1489** [Thordekk/Dekk-Core-Donator-Bugtracker#160]
After turning in https://www.wowhead.com/quest=38729/return-to-the-black-temple a sequence starts to play, the world server crashes. This can be reproduced by creating a Demon Hunter and 

.quest add 38729
.quest complete 38729
.quest reward 38729

This happens on Blood and Night Elf.

Logfile:
[9038cd62bee4+_worldserver.exe_[1-11_21-50-32].txt](https://github.com/Thordekk/Dekk-Core-Donator-Bugtracker/files/9913925/9038cd62bee4%2B_worldserver.exe_.1-11_21-50-32.txt)

**Comment by Thordekk** [comment]
tested is script i fix soon

**Comment by Thordekk** [comment]
Fixed
