### ISSUE TITLE
Dark iron dwarf mole machine not working.

### ISSUE THREAD

**Issue by CelixSA** [Thordekk/Dekk-Core-Donator-Bugtracker#162]
After creating a new dark iron dwarf you get the quest [For the Alliance] to Meet Ambassador Moorgard at the Stormwind Embassy. There is a mole machine to Stormwind once you take it you land in Stormwind but unable to move, logout and but in takes you to Tirisfal Glades.

Also fix quest name typo. [Fer the Alliance]

Please fix
Thanks

**Comment by Korsar1808** [comment]
Fix
