### ISSUE TITLE
[Mechanic] [High Priority] Haste Cooldown Reduction

### ISSUE THREAD

**Issue by SaladGuy** [Thordekk/Dekk-Core-Donator-Bugtracker#170]
Haste stat only visually reduces the cooldown, but when you try using the spell it acts as if it's still on cooldown. Hence the cooldown reduction is not functioning at all or is displayed incorrectly.

Please check the image for comparison. In current state, if you had 0% haste it would work perfectly without visual cooldown bugs.
![Bez naslova](https://user-images.githubusercontent.com/89343119/202776021-77044265-33d4-4e9c-92e3-cb7687f610a3.png)

**Comment by SaladGuy** [comment]
I know you decide if it's high priority or not, but i'd like to put these in my reports regarding anything that highly affects gameplay. Let me know what do you think about it.

**Comment by Thordekk** [comment]
Fixed
