### ISSUE TITLE
Quest to be fixed please.

### ISSUE THREAD

**Issue by CelixSA** [Thordekk/Dekk-Core-Donator-Bugtracker#174]
Borean Tundra:
quest=11626/the-emissary ---- Trident of Naz'jan not working on Leviroth 
quest=11908/reference-material ---- Can't loot book Fields, Factories and Workshops
quest=11603/in-wine-truth ---- Can't loot Kul Tiras Wine
quest=11681/rescuing-evanor ---- Can't rescue evanor

Westfall
quest=26241/westfall-stew --- No Okra loot from Harvest Watcher's nor Okra bush gm mode on.
Fix === UPDATE `creature_loot_template` SET `Chance` = 100 WHERE (`Entry` = 114) AND (`Item` = 732);
quest=26295/propaganda --- Can't unable to loot Issue of the Moonbrook Times and Mysterious Propaganda.
quest=176/wanted-hogger --- Hogger is missing??

Pandaria starting zone
quest=29418/kindling-the-fire --- no option to loot Dry Dogwood Root's
quest=29422/huo-the-spirit-of-fire --- Huo's Offerings is not working
quest=29662/stronger-than-reeds --- no option to loot Hard Tearwood Reed's
quest=29679/a-new-friend --- Not working 
quest=29680/the-source-of-our-livelihood --- not given/missing

**Comment by Thordekk** [comment]
quest=11626/the-emissary ---- Trident of Naz'jan working need to be in front of npc now is fixed

**Comment by Thordekk** [comment]
quest=11908/reference-material  i loot normal the book now

**Comment by Thordekk** [comment]
quest=11603/in-wine-truth ---- Can't loot Kul Tiras Wine looted and works

**Comment by Thordekk** [comment]
quest=11681/rescuing-evanor ---- Can't rescue evanor fixed

**Comment by Thordekk** [comment]
quest=26241/westfall-stew - fixed

**Comment by Thordekk** [comment]
quest=176/wanted-hogger fixed
