### ISSUE TITLE
Crashes in Argus

### ISSUE THREAD

**Issue by Mosal2** [Thordekk/Dekk-Core-Donator-Bugtracker#177]
Crashes in Argus when I am near my/the ship/base.

**Comment by Thordekk** [comment]
crash server or client?

**Comment by Mosal2** [comment]
Both close at the same time.

**Comment by Mosal2** [comment]
Client and worldserver clos.

**Comment by Mosal2** [comment]
BFA crashes when I travel out of boralus, Argus crashes when in Krokul  area. Sent from Mail for Windows From: ThordekkSent: Tuesday, December 27, 2022 8:10 PMTo: Thordekk/Dekk-Core-Donator-BugtrackerCc: Mosal2; AuthorSubject: Re: [Thordekk/Dekk-Core-Donator-Bugtracker] Crashes in Argus (Issue #177) crash server or client?—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***> Virus-free.www.avast.com
