### ISSUE TITLE
DB/Quest: The Dragon Isles Await

### ISSUE THREAD

**Issue by PivanDepolo** [Thordekk/Dekk-Core-Donator-Bugtracker#192]
https://www.wowhead.com/quest=65436/the-dragon-isles-await
https://www.wowhead.com/quest=65435/the-dragon-isles-await

The problem is that 2 quests are immediately issued for both the horde and the alliance. Should only be given 1 for the player's faction.

![image](https://user-images.githubusercontent.com/64589699/213513124-a8a28509-4f7b-425d-81a7-4e30f993cbc3.png)

**Comment by PivanDepolo** [comment]
NPC [Abyssian](https://www.wowhead.com/npc=190239/ebyssian) should be in Orgrimmar. And also automatically, when the character enters, a quest is activated, according to which you need to talk with this Abyssinian.

**Comment by Thordekk** [comment]
Fixed only get one now
