### ISSUE TITLE
DB/Quest: Runeforging: Preparation For Battle

### ISSUE THREAD

**Issue by PivanDepolo** [Thordekk/Dekk-Core-Donator-Bugtracker#193]
https://www.wowhead.com/quest=12842/runeforging-preparation-for-battle

after engraving, the quest does not count

![image](https://user-images.githubusercontent.com/64589699/213514051-25bc2fc1-2490-43d7-9f82-1eca74425692.png)

**Comment by Thordekk** [comment]
Fixed
