### ISSUE TITLE
DB/Quest: Rest and Relaxation

### ISSUE THREAD

**Issue by PivanDepolo** [Thordekk/Dekk-Core-Donator-Bugtracker#194]
https://www.wowhead.com/quest=2158/rest-and-relaxation

The window with the quest does not disappear after its completion.

![image](https://user-images.githubusercontent.com/64589699/213515220-3fc94908-1fcd-4c5e-9d00-c2075e1ae678.png)

**Comment by Thordekk** [comment]
need close manual is visual bug
