### ISSUE TITLE
DB/Quest: Report to Gryan Stoutmantle

### ISSUE THREAD

**Issue by PivanDepolo** [Thordekk/Dekk-Core-Donator-Bugtracker#198]
https://www.wowhead.com/quest=109/report-to-gryan-stoutmantle

An obsolete quest that can no longer be taken. There is no label on the map and a description in English (Russian client used)

![image](https://user-images.githubusercontent.com/64589699/213519229-914cf164-eb9b-4f87-9c3a-cb6c6f540a6a.png)

**Comment by Thordekk** [comment]
Fixed
