### ISSUE TITLE
Object: Hero's Call Board

### ISSUE THREAD

**Issue by PivanDepolo** [Thordekk/Dekk-Core-Donator-Bugtracker#199]
https://www.wowhead.com/object=206111/heros-call-board

Quests go beyond the borders of the dialog box

![2023-01-19_1](https://user-images.githubusercontent.com/64589699/213519728-fce20aa0-b91e-470e-9d74-5de229cd98ba.png)

**Comment by Thordekk** [comment]
Yes is visual bug
