### ISSUE TITLE
QuestID: 26727 - The Embalmer's Revenge

### ISSUE THREAD

**Issue by brownbr** [Thordekk/Dekk-Core-Donator-Bugtracker#2]
Upon accepting the quest, Stitches is supposed to appear outside in the town square (I believe this takes place within a phase) but Stitches does not appear.

**Comment by dio85** [comment]
true, have one phase shift, and after if you killed, again.

**Comment by Thordekk** [comment]
On it

**Comment by Thordekk** [comment]
Fixed not blizzlike because spawn npc near player, later we correct the position
