### ISSUE TITLE
Warrior/Spell: Defensive Stance

### ISSUE THREAD

**Issue by PivanDepolo** [Thordekk/Dekk-Core-Donator-Bugtracker#200]
https://www.wowhead.com/spell=386208/defensive-stance

This spell is displayed as a debuff.

![image](https://user-images.githubusercontent.com/64589699/213520444-b78e32d6-9b4d-4e9a-a7ae-9f716bc86a65.png)

**Comment by Thordekk** [comment]
Fixed
