### ISSUE TITLE
DB/NPC: Maztha

### ISSUE THREAD

**Issue by PivanDepolo** [Thordekk/Dekk-Core-Donator-Bugtracker#201]
https://www.wowhead.com/npc=44919/maztha

The "learn" button for learning the "Riding Master" is unavailable

![image](https://user-images.githubusercontent.com/64589699/213520937-f13854da-e454-4813-a13a-7bf247f30ebd.png)

**Comment by Thordekk** [comment]
Did u have enough gold?

**Comment by PivanDepolo** [comment]
> Did u have enough gold?

yes

**Comment by Thordekk** [comment]
Fixed
