### ISSUE TITLE
DB/NPC: Shay Pressler

### ISSUE THREAD

**Issue by PivanDepolo** [Thordekk/Dekk-Core-Donator-Bugtracker#204]
https://www.wowhead.com/npc=46602/shay-pressler

Sells guild items to everyone, even without a guild. Also sells all items without achievements at once

![image](https://user-images.githubusercontent.com/64589699/213522737-a059503f-a20d-4d38-b3e5-b4534e810930.png)

**Comment by Thordekk** [comment]
yes is custom feature
