### ISSUE TITLE
DB/NPC: Aldwin Laughlin

### ISSUE THREAD

**Issue by PivanDepolo** [Thordekk/Dekk-Core-Donator-Bugtracker#205]
https://www.wowhead.com/npc=4974/aldwin-laughlin

There are 2 problems here:

1) There is no dialogue with him and it is impossible to create a guild
2) There is an error in Russian localization, now NPCs are called as "Альдвин Лолкинс", but it should be like "Альдвин Лафлин"

![image](https://user-images.githubusercontent.com/64589699/213523522-c10a7c1d-d097-4b8d-8adc-0e01f774d9be.png)

**Comment by Thordekk** [comment]
Fixed
