### ISSUE TITLE
Mage/Spell: Mastery: Icicles

### ISSUE THREAD

**Issue by PivanDepolo** [Thordekk/Dekk-Core-Donator-Bugtracker#207]
https://www.wowhead.com/spell=76613/mastery-icicles

Does not work. No manifestation effect + no crystals themselves and no damage from them

![image](https://user-images.githubusercontent.com/64589699/213525304-83daeea7-81a1-4821-9bd6-979fd6f58412.png)

**Comment by Thordekk** [comment]
Scripted
