### ISSUE TITLE
Mage/Spell: Flurry

### ISSUE THREAD

**Issue by PivanDepolo** [Thordekk/Dekk-Core-Donator-Bugtracker#208]
https://www.wowhead.com/spell=44614/flurry

Only one shot goes (1/3 ability damage). Does not apply the "Winter's Chill" debuff

![image](https://user-images.githubusercontent.com/64589699/213526140-2a7f59fb-e74b-469c-b7dc-c2f1c666dbbd.png)

**Comment by Thordekk** [comment]
Fixed now is visual bug but  target the debuff
