### ISSUE TITLE
Mage/Spell: Mirror Image

### ISSUE THREAD

**Issue by PivanDepolo** [Thordekk/Dekk-Core-Donator-Bugtracker#211]
https://www.wowhead.com/spell=55342/mirror-image

Nothing happens when clicked

![image](https://user-images.githubusercontent.com/64589699/213528213-f6f29170-344e-45dc-816c-fb100ae57e7e.png)

**Comment by Thordekk** [comment]
need test soon

**Comment by Thordekk** [comment]
spell changed need sniff
