### ISSUE TITLE
Mage/Spell: Alter Time

### ISSUE THREAD

**Issue by PivanDepolo** [Thordekk/Dekk-Core-Donator-Bugtracker#213]
https://www.wowhead.com/spell=108978/alter-time

The ability does not go on cooldown and cannot be used again. You need to relog.

![image](https://user-images.githubusercontent.com/64589699/213529201-02084098-5825-410c-a1ff-839548411320.png)

**Comment by Thordekk** [comment]
Scripted need test

**Comment by Thordekk** [comment]
Fixed only not show cooldown in ui so now its visual bug
