### ISSUE TITLE
Mage/Spell: Prismatic Cloak

### ISSUE THREAD

**Issue by PivanDepolo** [Thordekk/Dekk-Core-Donator-Bugtracker#214]
https://www.wowhead.com/spell=198064/prismatic-cloak

The buff is given literally for a microsecond after using the Blink ability. I can’t say for the performance of the buff itself

![image](https://user-images.githubusercontent.com/64589699/213530209-c6e1d2a0-38c6-4232-84f1-1924e67d9c6a.png)

**Comment by Thordekk** [comment]
check now with latest fix

**Comment by Thordekk** [comment]
fixed
