### ISSUE TITLE
Unable to create a demon hunter

### ISSUE THREAD

**Issue by PivanDepolo** [Thordekk/Dekk-Core-Donator-Bugtracker#215]
After the removal of the character of the 60th level, the character of the 42nd level remained on the account. After that, the following error appeared:

![2023-01-19_7](https://user-images.githubusercontent.com/64589699/213531259-bb1bbefa-1d4d-4a34-a201-5d738234a4b8.png)

It says "You can only create a Dracthyr if you have a character of at least level 50 in that realm."

The config has `CharacterCreating.MinLevelForEvoker = 50`  a limit for evokers, but not dh

It writes specifically about the Dracthyrs, not the DH. Deleted the cache, didn't help.

**Comment by PivanDepolo** [comment]
Even if the account has a character even level 70, the problem still remains and it is impossible to create a DH.

**Comment by Thordekk** [comment]
put requirement as 0
