### ISSUE TITLE
Mage/Spell: Snowdrift

### ISSUE THREAD

**Issue by PivanDepolo** [Thordekk/Dekk-Core-Donator-Bugtracker#216]
https://www.wowhead.com/spell=389794/snowdrift

Deals no damage. There is no visual display. Only the buff appears

![image](https://user-images.githubusercontent.com/64589699/213532212-7a738ed2-01df-4869-8d79-37f2dd9de492.png)

**Comment by Thordekk** [comment]
Scripted need test soon

**Comment by Thordekk** [comment]
Fixed need add areatrigger
