### ISSUE TITLE
Mardum, the Shattered Abyss dead creatures

### ISSUE THREAD

**Issue by PivanDepolo** [Thordekk/Dekk-Core-Donator-Bugtracker#217]
In the starting location of the DH, half of the creatures are dead

![WoWScrnShot_011923_221606](https://user-images.githubusercontent.com/64589699/213539988-28999dd0-052b-40b6-8ce6-ed7a4101dee5.jpg)

**Comment by Thordekk** [comment]
Need ids of the creatures please

**Comment by PivanDepolo** [comment]
> Need ids of the creatures please

https://www.wowhead.com/npc=98484/moarg-brute|
