### ISSUE TITLE
Demon Hunter Talents Problem 

### ISSUE THREAD

**Issue by PivanDepolo** [Thordekk/Dekk-Core-Donator-Bugtracker#218]
A passive was chosen to replace the demon's bite, but the demon's bite did not disappear, the passive was not given, and the rest of the attacking abilities were no longer possible to use at all

![WoWScrnShot_011923_221658](https://user-images.githubusercontent.com/64589699/213540264-9b71070c-59d7-4fcb-be33-92f82d926761.jpg)

**Comment by Thordekk** [comment]
On it
