### ISSUE TITLE
DB/NPC: Public Relations Agent

### ISSUE THREAD

**Issue by PivanDepolo** [Thordekk/Dekk-Core-Donator-Bugtracker#227]
https://www.wowhead.com/npc=37675/public-relations-agent

Stormwind has NPC, from the Love Fever holiday, but should only appear from February 6th to February 20th in the game calendar.

![image](https://user-images.githubusercontent.com/64589699/213647387-d66f9336-9e37-4a9e-a9ef-40eb17d09abb.png)

**Comment by Thordekk** [comment]
fixed
