### ISSUE TITLE
Object: Wanted Poster

### ISSUE THREAD

**Issue by PivanDepolo** [Thordekk/Dekk-Core-Donator-Bugtracker#228]
https://www.wowhead.com/object=68/wanted-poster 

This object must have a quest [WANTED: "Hogger"](https://www.wowhead.com/quest=176/wanted-hogger)

![image](https://user-images.githubusercontent.com/64589699/213648580-46830cfb-bc6f-4962-bbd5-3128a70e231f.png)

**Comment by Thordekk** [comment]
added
