### ISSUE TITLE
Warlock/Spell: Dark Pact

### ISSUE THREAD

**Issue by PivanDepolo** [Thordekk/Dekk-Core-Donator-Bugtracker#229]
https://www.wowhead.com/spell=108416/dark-pact

This ability just doesn't work.

![2023-01-20_1](https://user-images.githubusercontent.com/64589699/213659195-6025dd1b-a29b-423e-9b04-111677278f5d.png)

**Comment by Thordekk** [comment]
was duplicate script need test

**Comment by Thordekk** [comment]
https://gyazo.com/beeca2404b9ad274ba9f7301e4e7ad2b
