### ISSUE TITLE
Warlock/Spell: Inquisitor's Gaze

### ISSUE THREAD

**Issue by PivanDepolo** [Thordekk/Dekk-Core-Donator-Bugtracker#233]
https://www.wowhead.com/spell=386344/inquisitors-gaze

2 buff applies and does not work

![2023-01-20_5](https://user-images.githubusercontent.com/64589699/213666871-e5391a58-ab4e-42db-af15-54c01fe303d3.png)
![2023-01-20_8](https://user-images.githubusercontent.com/64589699/213666920-f133cbaa-3118-4e21-a6e2-991779cd9e5a.png)

**Comment by Thordekk** [comment]
scripted need check procs
