### ISSUE TITLE
DK/Spell: Death Strike

### ISSUE THREAD

**Issue by PivanDepolo** [Thordekk/Dekk-Core-Donator-Bugtracker#234]
https://www.wowhead.com/spell=49998/death-strike

This ability does not heal the character, but should. (It works correctly on TC)

![WoWScrnShot_012023_122017](https://user-images.githubusercontent.com/64589699/213667481-ad59162a-3738-40ad-ba0d-72f099db0764.jpg)
![WoWScrnShot_012023_122715](https://user-images.githubusercontent.com/64589699/213667725-59374761-82a8-4145-b3b6-0657265a5322.jpg)
![54410ef2adf35157](https://user-images.githubusercontent.com/64589699/213667739-385ee477-f799-4e2a-b931-2319fe3d8b67.png)

**Comment by Thordekk** [comment]
fixed soon u can test
