### ISSUE TITLE
DB/NPC: Primal Proto-Drake

### ISSUE THREAD

**Issue by PivanDepolo** [Thordekk/Dekk-Core-Donator-Bugtracker#236]
https://www.wowhead.com/npc=195639/primal-proto-drake

This NPC flies in water and sometimes in textures

![2023-01-20_10](https://user-images.githubusercontent.com/64589699/213686621-ef867353-23c9-42a4-9a33-1a84e414eb19.png)

Another problem is that they must fly in a completely different part of the map

**Comment by Thordekk** [comment]
fixed i make a creature cleanup soon
