### ISSUE TITLE
Spell/Hunter: Trailblazer

### ISSUE THREAD

**Issue by PivanDepolo** [Thordekk/Dekk-Core-Donator-Bugtracker#244]
https://www.wowhead.com/spell=199921/trailblazer

This spell just doesn't work. Gives 0.

![2023-01-20_25](https://user-images.githubusercontent.com/64589699/213862376-ca5a0fd7-b180-4b6c-9096-43e12097b8e0.png)

**Comment by Thordekk** [comment]
Rewrited
