### ISSUE TITLE
DB/Quest: Crocolisk Life Crash Client 

### ISSUE THREAD

**Issue by PivanDepolo** [Thordekk/Dekk-Core-Donator-Bugtracker#245]
This [quest](https://www.wowhead.com/quest=48573/crocolisk-life) will give you the following [item](https://www.wowhead.com/item=152596/).

After using this item, the player crashes

And now when he is in the game and wants to open a map or a quest table, he immediately crashes.

**Comment by Thordekk** [comment]
Fixed and fixed quest
