### ISSUE TITLE
Mage/Spell: Ice Floes

### ISSUE THREAD

**Issue by PivanDepolo** [Thordekk/Dekk-Core-Donator-Bugtracker#249]
This issue was closed https://github.com/Thordekk/Dekk-Core-Donator-Bugtracker/issues/220 as fixed, but it's not fixed.

https://www.wowhead.com/spell=108839/ice-floes

Nothing happens when used. Prevents casting while moving. No buff

![image](https://user-images.githubusercontent.com/64589699/213862933-b1310102-80d6-462e-a5e1-82c94e06a33e.png)

**Comment by Thordekk** [comment]
Scripted u can test soon
