### ISSUE TITLE
Mage/Spell: Shimmer

### ISSUE THREAD

**Issue by PivanDepolo** [Thordekk/Dekk-Core-Donator-Bugtracker#250]
https://www.wowhead.com/spell=212653/shimmer

Does not apply a shield when used

![image](https://user-images.githubusercontent.com/64589699/213862978-710a7c33-befb-4a57-8976-da94e7c915c4.png)

**Comment by Thordekk** [comment]
The spell not apply a shield look wowhead : 
Teleports you 20 yards forward, unless something is in the way. Unaffected by the global cooldown and castable while casting.
--
