### ISSUE TITLE
Mage/Spell: Glacial Assault

### ISSUE THREAD

**Issue by PivanDepolo** [Thordekk/Dekk-Core-Donator-Bugtracker#253]
https://www.wowhead.com/spell=279854/glacial-assault

This ability does not proc.

![image](https://user-images.githubusercontent.com/64589699/213863156-70600248-08f8-48a2-b2e9-2ebd0470c27c.png)

**Comment by Thordekk** [comment]
Scripted i upload soon so can be tested
