### ISSUE TITLE
Mage/Spell: Overflowing Energy

### ISSUE THREAD

**Issue by PivanDepolo** [Thordekk/Dekk-Core-Donator-Bugtracker#254]
https://www.wowhead.com/spell=390218/overflowing-energy

Doesn't get a buff to increase crit. Does not grant 10% passive crit.

![image](https://user-images.githubusercontent.com/64589699/213863213-842e2f89-2c93-4615-96cb-5676f5eae4d7.png)

**Comment by Thordekk** [comment]
spell scripted now
