### ISSUE TITLE
Mount Traveler's Tundra Mammoth

### ISSUE THREAD

**Issue by PivanDepolo** [Thordekk/Dekk-Core-Donator-Bugtracker#259]
https://www.wowhead.com/spell=61447/travelers-tundra-mammoth

Summoned without NPC merchants on the seats on the sides. (Works correctly on TC)

![WoWScrnShot_012023_142805](https://user-images.githubusercontent.com/64589699/213863494-11c0fe6e-6cde-457a-a1be-e3f79ad5b7e8.jpg)

**Comment by Thordekk** [comment]
Fixed
