### ISSUE TITLE
DB/NPC: Georgio Bolero 

### ISSUE THREAD

**Issue by PivanDepolo** [Thordekk/Dekk-Core-Donator-Bugtracker#260]
https://www.wowhead.com/npc=1346/georgio-bolero

Teaches Alchemy instead of Tailoring

![image](https://user-images.githubusercontent.com/64589699/213863561-dbe56b48-c6d5-4a6b-a318-c01c892557da.png)

**Comment by Thordekk** [comment]
Fixed
