### ISSUE TITLE
DB/NPC: Ironforge Guard

### ISSUE THREAD

**Issue by PivanDepolo** [Thordekk/Dekk-Core-Donator-Bugtracker#264]
https://www.wowhead.com/npc=42783/ironforge-guard

No dialogue with NPCs. Must show paths to various NPCs

![image](https://user-images.githubusercontent.com/64589699/213863724-3f573be2-e52b-4111-b3a5-9b847b778133.png)

**Comment by Thordekk** [comment]
Fixed
