### ISSUE TITLE
DB/Quest: Future of the Flights

### ISSUE THREAD

**Issue by PivanDepolo** [Thordekk/Dekk-Core-Donator-Bugtracker#267]
https://www.wowhead.com/quest=65998/future-of-the-flights

This quest works, but it is impossible to turn it in

![image](https://user-images.githubusercontent.com/64589699/213872991-5e39912e-8f75-4fb1-b7c9-0b89e2a8dd0c.png)

**Comment by Thordekk** [comment]
Fixed
