### ISSUE TITLE
DB/Quest: Library of Alexstrasza

### ISSUE THREAD

**Issue by PivanDepolo** [Thordekk/Dekk-Core-Donator-Bugtracker#268]
https://www.wowhead.com/quest=66000/library-of-alexstrasza

I found only 1 book and it does not count towards the progress of the task

![image](https://user-images.githubusercontent.com/64589699/213873066-67e47b10-0db9-447f-9637-688d93168f8f.png)

**Comment by Thordekk** [comment]
Fixed
