### ISSUE TITLE
DB/Quest: Always Be Crafting

### ISSUE THREAD

**Issue by PivanDepolo** [Thordekk/Dekk-Core-Donator-Bugtracker#271]
https://www.wowhead.com/quest=66112/always-be-crafting

NPCs are friendly and can't be killed 

https://www.wowhead.com/npc=192266/baron-crustcore 

![image](https://user-images.githubusercontent.com/64589699/213873285-c6d96998-888f-401a-87f7-0bd377db26f2.png)

**Comment by Thordekk** [comment]
Fixed
