### ISSUE TITLE
DB/Quest: Opportunities Abound

### ISSUE THREAD

**Issue by PivanDepolo** [Thordekk/Dekk-Core-Donator-Bugtracker#272]
https://www.wowhead.com/quest=70042/opportunities-abound

Visible to characters of all classes. It cannot be fulfilled. Backpack cannot be taken

![image](https://user-images.githubusercontent.com/64589699/213873563-e389b91a-28d4-48d7-aec5-249d4639381c.png)

**Comment by Thordekk** [comment]
fixed
