### ISSUE TITLE
Critical error when talking to NPC in Oribos

### ISSUE THREAD

**Issue by PivanDepolo** [Thordekk/Dekk-Core-Donator-Bugtracker#275]
When you try to talk to the [Lady Moonberry](https://www.wowhead.com/npc=171795/lady-moonberry) or start the quest with the covenants, I didn’t understand exactly), the game crashes with a critical error.

![Wow_sbCTKvQ4LI](https://user-images.githubusercontent.com/64589699/213906766-a1f5201f-0a0a-489b-8ec3-3f30f9b997c7.jpg)

**Comment by Thordekk** [comment]
Fixed
