### ISSUE TITLE
DB/Quest: Adventuring in the Dragon Isles

### ISSUE THREAD

**Issue by PivanDepolo** [Thordekk/Dekk-Core-Donator-Bugtracker#278]
https://www.wowhead.com/quest=72293/adventuring-in-the-dragon-isles

Cannot interact with tactical map

![image](https://user-images.githubusercontent.com/64589699/213910058-3bf163e3-09ab-42e8-9ea1-a17ff80283ae.png)

**Comment by Thordekk** [comment]
need sniff of this

**Comment by Thordekk** [comment]
Fixed
