### ISSUE TITLE
DB/Quest: A Scalpel of a Solution

### ISSUE THREAD

**Issue by PivanDepolo** [Thordekk/Dekk-Core-Donator-Bugtracker#280]
https://www.wowhead.com/quest=66105/a-scalpel-of-a-solution

NPCs are friendly

![image](https://user-images.githubusercontent.com/64589699/213910273-eabd9e72-564c-4080-9faa-4d069ab9d4bb.png)

**Comment by Thordekk** [comment]
Fixed
