### ISSUE TITLE
DB/Quest: Don't Be So Shellfish

### ISSUE THREAD

**Issue by PivanDepolo** [Thordekk/Dekk-Core-Donator-Bugtracker#282]
https://www.wowhead.com/quest=66106/dont-be-so-shellfish

NPCs are friendly. You can't pick up shells either.

![image](https://user-images.githubusercontent.com/64589699/213910388-f80ae340-13bf-44e3-838d-8c0ceb91707d.png)

**Comment by Thordekk** [comment]
Fixed
