### ISSUE TITLE
DB/Quest: A Quack For Help

### ISSUE THREAD

**Issue by PivanDepolo** [Thordekk/Dekk-Core-Donator-Bugtracker#284]
https://www.wowhead.com/quest=66196/a-quack-for-help

The NPC does not follow the character. Impossible to complete

![image](https://user-images.githubusercontent.com/64589699/213910484-146ac63b-cbf2-4bcb-9fe8-69f580c777d4.png)

**Comment by Thordekk** [comment]
Fixed now
