### ISSUE TITLE
DB/Quest: A Sledgehammer of a Solution

### ISSUE THREAD

**Issue by PivanDepolo** [Thordekk/Dekk-Core-Donator-Bugtracker#285]
https://www.wowhead.com/quest=66108/a-sledgehammer-of-a-solution

NPCs are friendly

![image](https://user-images.githubusercontent.com/64589699/213910541-d6c9a66b-f6ec-49d0-8ee2-33a218009776.png)

**Comment by Thordekk** [comment]
FIxed
