### ISSUE TITLE
Zone/Ruby Life Pools: Faction problem

### ISSUE THREAD

**Issue by PivanDepolo** [Thordekk/Dekk-Core-Donator-Bugtracker#288]
https://www.wowhead.com/zone=14063/ruby-life-pools

Mobs and bosses are friendly

![image](https://user-images.githubusercontent.com/64589699/213921870-4b937d26-6489-49d8-a0c3-50032eafcc67.png)

**Comment by Thordekk** [comment]
Being fixed
