### ISSUE TITLE
DB/Quest: Everything Is Better with Bacon Server crash

### ISSUE THREAD

**Issue by PivanDepolo** [Thordekk/Dekk-Core-Donator-Bugtracker#292]
https://www.wowhead.com/quest=26220/everything-is-better-with-bacon

Server crash when dealing damage to an [Mature Swine](https://www.wowhead.com/npc=42504/mature-swine) on the quest "Everything will work with bacon". Right after the first hit

![Wow_nr8BuwHPBb](https://user-images.githubusercontent.com/64589699/213985937-9238e603-1524-4f1e-8159-f5d266fa8cd3.jpg)

**Comment by Thordekk** [comment]
https://gyazo.com/ca11cf2e07b6da678317d6ab268e960e

not for me maybe is an spell used give me wich spell cast
