### ISSUE TITLE
Latest server crashlogs

### ISSUE THREAD

**Issue by PivanDepolo** [Thordekk/Dekk-Core-Donator-Bugtracker#296]
https://gist.github.com/PivanDepolo/a2d047b09da5cd9746220ad731507d4e
https://gist.github.com/PivanDepolo/8f62d4aa76edecdd0f8e85429c5fa702
https://gist.github.com/PivanDepolo/975ab8d71b2b184abd67eb5625858649
https://gist.github.com/PivanDepolo/1168b765b261f58372352a9d6f82118f
https://gist.github.com/PivanDepolo/045343fb003ccc3e873511f1351f9c1a
https://gist.github.com/PivanDepolo/0c6d37625163f8e1b3379b1dd8dce40a
https://gist.github.com/PivanDepolo/e5b892760655102aac1a5ccff0862ca6
https://gist.github.com/PivanDepolo/65ca7cc20a4d530da8d35a089879f692
https://gist.github.com/PivanDepolo/dfbaf996eb3699b077149f1cd263215c
https://gist.github.com/PivanDepolo/f95f8e546f75e393c6a18a34b94a68ca
https://gist.github.com/PivanDepolo/3f82112a7685a8df1f0d4538e2b835c9
https://gist.github.com/PivanDepolo/b783f859a9fa65d5d5da8962e6603524
https://gist.github.com/PivanDepolo/5ad67517493a826cf67cd2be954a1deb
https://gist.github.com/PivanDepolo/b82a67c034edf548e0128e7590e7a60c
https://gist.github.com/PivanDepolo/be0811d48751c639c12ed3a01c812cd0
https://gist.github.com/PivanDepolo/122dfdcdbf0fdfceaf9ab16c80ec614f
https://gist.github.com/PivanDepolo/9ebbd836f7658ad66d1e9a9b2460f214
https://gist.github.com/PivanDepolo/ec126df428a33033e7a65b2f6ccb32e6

**Comment by Thordekk** [comment]
Fixed
