### ISSUE TITLE
Transmogrification does not apply to Tabards, Weapons and Off-Hand

### ISSUE THREAD

**Issue by brownbr** [Thordekk/Dekk-Core-Donator-Bugtracker#3]
When attempting to use transmog on a Weapon, and Off-Hand, or a Tabard, the transmog refuses to apply to the item. Simultaneously, if attempting to apply transmogs to any other equipment it will not work. If you are applying to Weapon, Head, and Shoulders for example, none of the transmogs will apply until you disable the Weapon transmog.

**Comment by Thordekk** [comment]
Being fixed, weapons are fixed now
