### ISSUE TITLE
Alliance Azeroth WorldMap Crash #132

### ISSUE THREAD

**Issue by Ursonne** [Thordekk/Dekk-Core-Donator-Bugtracker#31]
When you have a Alliance Character between level 11 - 49 and open the Azeroth Worldmap the Client Crash with Error #132.

![image](https://user-images.githubusercontent.com/34980984/162223870-e56d78bd-d974-4fbb-945b-ea1a91a6c8c6.png)
Between Level 11, all fine. :)

![image](https://user-images.githubusercontent.com/34980984/162225122-b618d708-2867-4b03-837f-6e730e5b58a4.png)
The Same with a Char with level 14.

When you open the Map of Kul Tiras it is the same, after level 50 is there no error.

On Retail all is fine with the same Client.

**Comment by Thordekk** [comment]
fixed
