### ISSUE TITLE
DB/Quest: Work Order: Word of Haste

### ISSUE THREAD

**Issue by PivanDepolo** [Thordekk/Dekk-Core-Donator-Bugtracker#310]
https://www.wowhead.com/quest=41672/work-order-word-of-haste

I took this quest from NPC [Valdemar Stormseeker](https://www.wowhead.com/npc=106904/valdemar-stormseeker)

Now after each relog in the game it appears. You can't undo it, and you can't hide it either.

**Comment by Thordekk** [comment]
is a world quest is auto removed when finish time this is a work in progress u can remove from character world quest
