### ISSUE TITLE
Mage/Spell: Shifting Power

### ISSUE THREAD

**Issue by PivanDepolo** [Thordekk/Dekk-Core-Donator-Bugtracker#324]
https://www.wowhead.com/spell=314791/shifting-power

Mage ability cooldown reduction effect does not work while channeling

![image](https://user-images.githubusercontent.com/64589699/215597683-e16e09b8-864e-4c0c-a202-5d90d2ee9337.png)

**Comment by Thordekk** [comment]
scripted need test later
