### ISSUE TITLE
Mage/Spell: Freezing Cold

### ISSUE THREAD

**Issue by PivanDepolo** [Thordekk/Dekk-Core-Donator-Bugtracker#325]
https://www.wowhead.com/spell=386763/freezing-cold

Does not work. The Cone of Cold ability works as normal with this talent. Nothing changes

![image](https://user-images.githubusercontent.com/64589699/215597902-e71daa10-bc76-43aa-938f-0c968d449a7c.png)

**Comment by Thordekk** [comment]
scripted we test soon
