### ISSUE TITLE
Mage/Spell: Snap Freeze

### ISSUE THREAD

**Issue by PivanDepolo** [Thordekk/Dekk-Core-Donator-Bugtracker#331]
https://www.wowhead.com/spell=378901/snap-freeze

Does not work. Icy Blood does not apply the indicated buffs when activated.

![image](https://user-images.githubusercontent.com/64589699/215599123-2907936e-b927-429c-b1c4-f83dd1a20777.png)

**Comment by Thordekk** [comment]
Scripted
