### ISSUE TITLE
DB/Quest: In the Blink of an Eye

### ISSUE THREAD

**Issue by PivanDepolo** [Thordekk/Dekk-Core-Donator-Bugtracker#335]
https://www.wowhead.com/quest=44663/in-the-blink-of-an-eye

Buttons don't work. Can't start quest chain

![WoWScrnShot_012823_075529](https://user-images.githubusercontent.com/64589699/215601101-e025045a-bcad-4b6f-9d12-7f510a7283b5.jpg)

**Comment by Thordekk** [comment]
Fixed without scene, scene is broken
