### ISSUE TITLE
Priest/Spell: Holy Word: Salvation

### ISSUE THREAD

**Issue by PivanDepolo** [Thordekk/Dekk-Core-Donator-Bugtracker#340]
https://www.wowhead.com/spell=265202/holy-word-salvation

does not work, only visual effect

![3](https://user-images.githubusercontent.com/64589699/216160523-103e46aa-16ad-4432-be5d-28fb473cda5e.png)

**Comment by Thordekk** [comment]
rewrited need test with players near
