### ISSUE TITLE
DB/NPC: Netherologist Coppernickels

### ISSUE THREAD

**Issue by PivanDepolo** [Thordekk/Dekk-Core-Donator-Bugtracker#344]
https://www.wowhead.com/npc=19569/netherologist-coppernickels

This npc does not issue quest https://www.wowhead.com/quest=10183/off-to-area-52

![image](https://user-images.githubusercontent.com/64589699/216161872-295df098-5b60-4f88-8f35-7ccfca9a33a7.png)

**Comment by Thordekk** [comment]
corrected i test soon
