### ISSUE TITLE
DB/NPC: Larimaine Purdue

### ISSUE THREAD

**Issue by PivanDepolo** [Thordekk/Dekk-Core-Donator-Bugtracker#347]
https://www.wowhead.com/npc=2485/larimaine-purdue

No dialogue with NPC. Unable to learn portals

![image](https://user-images.githubusercontent.com/64589699/216162877-92d2f277-b418-4a72-8586-de94f42ee246.png)

**Comment by Thordekk** [comment]
Blizzard remove this trainer now new is [Azunla](https://www.wowhead.com/npc=164956/azunla) Is the new portal trainer for Stormwind in Shadowlands and is located at 80, 69 in Old Town
