### ISSUE TITLE
DB/NPC: Izal Whitemoon

### ISSUE THREAD

**Issue by PivanDepolo** [Thordekk/Dekk-Core-Donator-Bugtracker#349]
https://www.wowhead.com/npc=88110/izal-whitemoon

Client crash when trying to talk to with NPC

![Wow_8h9Bggts8f](https://user-images.githubusercontent.com/64589699/216163370-1d42ec52-2e25-49f0-a03d-8a007487b693.jpg)

**Comment by Thordekk** [comment]
Fixed
