### ISSUE TITLE
Can't skin, dragon isles

### ISSUE THREAD

**Issue by PivanDepolo** [Thordekk/Dekk-Core-Donator-Bugtracker#364]
Skinning on Dragon Isles not working, writes insufficient level when trying.

https://www.wowhead.com/npc=193806/primal-proto-drake

![image](https://user-images.githubusercontent.com/64589699/216457458-0c1ef4c6-3d1b-4328-9586-a6c13ba46781.png)

**Comment by Thordekk** [comment]
did u learn dragon isles skinning?
