### ISSUE TITLE
DB/Spell: Expert Riding

### ISSUE THREAD

**Issue by PivanDepolo** [Thordekk/Dekk-Core-Donator-Bugtracker#365]
https://www.wowhead.com/spell=34092/expert-riding

for some reason it is impossible to learn "Expert Riding"

![WoWScrnShot_012423_021359](https://user-images.githubusercontent.com/64589699/216457780-566092b3-e9b9-4bf0-ab7c-f2e81decaac6.jpg)

**Comment by Thordekk** [comment]
Work perfect maybe is ure level look mine https://gyazo.com/4d54b96829e14bbc59bd8329946b92e4_
