### ISSUE TITLE
DB/Quest: Forensic Ecology

### ISSUE THREAD

**Issue by PivanDepolo** [Thordekk/Dekk-Core-Donator-Bugtracker#372]
https://www.wowhead.com/quest=66104/forensic-ecology

https://www.wowhead.com/npc=187883 is missing

![WoWScrnShot_020323_100829](https://user-images.githubusercontent.com/64589699/216540180-0a412f07-a68e-4d3c-b726-a1185342e13c.jpg)

**Comment by Thordekk** [comment]
Quest is working perfect just tested
