### ISSUE TITLE
Mage/Spell: Cauterize

### ISSUE THREAD

**Issue by PivanDepolo** [Thordekk/Dekk-Core-Donator-Bugtracker#375]
https://www.wowhead.com/spell=86949/cauterize

A player with this talent cannot be killed. Mage becomes immortal

**Comment by HerokDeV** [comment]
Help for DekkCore

// Cauterize Fix  - 86949
class spell_mage_cauterize : public SpellScriptLoader
{
public:
    spell_mage_cauterize() : SpellScriptLoader("spell_mage_cauterize") { }

    class spell_mage_cauterize_AuraScript : public AuraScript
    {
        PrepareAuraScript(spell_mage_cauterize_AuraScript);

        int32 healtPct;

        enum spellcauterize
        {
            SPELL_MAGE_CAUTERIZE = 87023,
        };
        
        bool Load() override
        {
            healtPct = GetSpellInfo()->GetEffect(EFFECT_1)->CalcValue(GetCaster());
            return GetUnitOwner()->GetTypeId() == TYPEID_PLAYER;
        }

        void CalculateAmount(AuraEffect const* /*auraEffect*/, int32& amount, bool& /*canBeRecalculated*/)
        {
            amount = -1;
        }

        void Absorb(AuraEffect* /*auraEffect*/, DamageInfo& dmgInfo, uint32& absorbAmount)
        {
            Unit* target = GetTarget();

            if (target->GetTypeId() != TYPEID_PLAYER)
                return;
            if (dmgInfo.GetDamage() < target->GetHealth())
                return;

            if (target->ToPlayer()->GetSpellHistory()->HasCooldown(SPELL_MAGE_CAUTERIZE))
                return;

            int bp1 = target->CountPctFromMaxHealth(healtPct);
            target->CastCustomSpell(target, SPELL_MAGE_CAUTERIZE, NULL, &bp1, NULL, true);
            target->CastSpell(target, GetSpellInfo()->GetEffect(EFFECT_2)->TriggerSpell, true);
            target->GetSpellHistory()->AddCooldown(SPELL_MAGE_CAUTERIZE, 0, std::chrono::minutes(2));

            absorbAmount = dmgInfo.GetDamage();
        }

        void Register() override
        {
            DoEffectCalcAmount += AuraEffectCalcAmountFn(spell_mage_cauterize_AuraScript::CalculateAmount, EFFECT_0, SPELL_AURA_SCHOOL_ABSORB);
            OnEffectAbsorb += AuraEffectAbsorbFn(spell_mage_cauterize_AuraScript::Absorb, EFFECT_0);
        }
    };

    class spell_mage_cauterize_SpellScript : public SpellScript
    {
        PrepareSpellScript(spell_mage_cauterize_SpellScript);

        void PreventTrigger(SpellEffIndex effIndex)
        {
            PreventHitEffect(effIndex);
        }

        void Register() override
        {
            OnEffectHit += SpellEffectFn(spell_mage_cauterize_SpellScript::PreventTrigger, EFFECT_2, SPELL_EFFECT_TRIGGER_SPELL);
            OnEffectHitTarget += SpellEffectFn(spell_mage_cauterize_SpellScript::PreventTrigger, EFFECT_2, SPELL_EFFECT_TRIGGER_SPELL);
            OnEffectLaunch += SpellEffectFn(spell_mage_cauterize_SpellScript::PreventTrigger, EFFECT_2, SPELL_EFFECT_TRIGGER_SPELL);
            OnEffectLaunchTarget += SpellEffectFn(spell_mage_cauterize_SpellScript::PreventTrigger, EFFECT_2, SPELL_EFFECT_TRIGGER_SPELL);
        }
    };

    AuraScript* GetAuraScript() const override
    {
        return new spell_mage_cauterize_AuraScript();
    }

    SpellScript* GetSpellScript() const override
    {
        return new spell_mage_cauterize_SpellScript();
    }
};

**Comment by Thordekk** [comment]
> Help for DekkCore
> 
> // Cauterize Fix - 86949 class spell_mage_cauterize : public SpellScriptLoader { public: spell_mage_cauterize() : SpellScriptLoader("spell_mage_cauterize") { }
> 
> ```
> class spell_mage_cauterize_AuraScript : public AuraScript
> {
>     PrepareAuraScript(spell_mage_cauterize_AuraScript);
> 
>     int32 healtPct;
> 
>     enum spellcauterize
>     {
>         SPELL_MAGE_CAUTERIZE = 87023,
>     };
>     
>     bool Load() override
>     {
>         healtPct = GetSpellInfo()->GetEffect(EFFECT_1)->CalcValue(GetCaster());
>         return GetUnitOwner()->GetTypeId() == TYPEID_PLAYER;
>     }
> 
>     void CalculateAmount(AuraEffect const* /*auraEffect*/, int32& amount, bool& /*canBeRecalculated*/)
>     {
>         amount = -1;
>     }
> 
>     void Absorb(AuraEffect* /*auraEffect*/, DamageInfo& dmgInfo, uint32& absorbAmount)
>     {
>         Unit* target = GetTarget();
> 
>         if (target->GetTypeId() != TYPEID_PLAYER)
>             return;
>         if (dmgInfo.GetDamage() < target->GetHealth())
>             return;
> 
>         if (target->ToPlayer()->GetSpellHistory()->HasCooldown(SPELL_MAGE_CAUTERIZE))
>             return;
> 
>         int bp1 = target->CountPctFromMaxHealth(healtPct);
>         target->CastCustomSpell(target, SPELL_MAGE_CAUTERIZE, NULL, &bp1, NULL, true);
>         target->CastSpell(target, GetSpellInfo()->GetEffect(EFFECT_2)->TriggerSpell, true);
>         target->GetSpellHistory()->AddCooldown(SPELL_MAGE_CAUTERIZE, 0, std::chrono::minutes(2));
> 
>         absorbAmount = dmgInfo.GetDamage();
>     }
> 
>     void Register() override
>     {
>         DoEffectCalcAmount += AuraEffectCalcAmountFn(spell_mage_cauterize_AuraScript::CalculateAmount, EFFECT_0, SPELL_AURA_SCHOOL_ABSORB);
>         OnEffectAbsorb += AuraEffectAbsorbFn(spell_mage_cauterize_AuraScript::Absorb, EFFECT_0);
>     }
> };
> 
> class spell_mage_cauterize_SpellScript : public SpellScript
> {
>     PrepareSpellScript(spell_mage_cauterize_SpellScript);
> 
>     void PreventTrigger(SpellEffIndex effIndex)
>     {
>         PreventHitEffect(effIndex);
>     }
> 
>     void Register() override
>     {
>         OnEffectHit += SpellEffectFn(spell_mage_cauterize_SpellScript::PreventTrigger, EFFECT_2, SPELL_EFFECT_TRIGGER_SPELL);
>         OnEffectHitTarget += SpellEffectFn(spell_mage_cauterize_SpellScript::PreventTrigger, EFFECT_2, SPELL_EFFECT_TRIGGER_SPELL);
>         OnEffectLaunch += SpellEffectFn(spell_mage_cauterize_SpellScript::PreventTrigger, EFFECT_2, SPELL_EFFECT_TRIGGER_SPELL);
>         OnEffectLaunchTarget += SpellEffectFn(spell_mage_cauterize_SpellScript::PreventTrigger, EFFECT_2, SPELL_EFFECT_TRIGGER_SPELL);
>     }
> };
> 
> AuraScript* GetAuraScript() const override
> {
>     return new spell_mage_cauterize_AuraScript();
> }
> 
> SpellScript* GetSpellScript() const override
> {
>     return new spell_mage_cauterize_SpellScript();
> }
> ```
> 
> };

Not never we dont use cast custom spell also is wrong scripted

**Comment by Thordekk** [comment]
Rewrited aura was the issue need test soon

**Comment by HerokDeV** [comment]
ok it was only help I'm writing this script well for my source trinity development so I will pull the fix of this power

**Comment by Thordekk** [comment]
> ok it was only help I'm writing this script well for my source trinity development so I will pull the fix of this power

U use cvhattgpt bot u didnt script this spell chat gpt is using code from 10  years ago 😂
