### ISSUE TITLE
DB/Quest: Library of Alexstrasza

### ISSUE THREAD

**Issue by PivanDepolo** [Thordekk/Dekk-Core-Donator-Bugtracker#381]
https://www.wowhead.com/quest=66000/library-of-alexstrasza

After completing this quest, it cannot be turned in.

![image](https://user-images.githubusercontent.com/64589699/216673808-c3d761f7-9aea-4042-a446-9dd1b4e05c03.png)

**Comment by Thordekk** [comment]
Need click one more book is visual bug
