### ISSUE TITLE
MONK/SPELL [ Transcendence ]

### ISSUE THREAD

**Issue by Donzin** [Thordekk/Dekk-Core-Donator-Bugtracker#402]
This is spell don't work. When you use the skill, your clone in spirit form does not appear. so you can't use the teleportation mechanic in place of the clone

https://www.wowhead.com/spell=101643/transcendence
Excellent, unique mobility cooldown. Fantastic for dealing with mechanics in raids, or kiting in Mythic+ dungeons. Great in PvP, as well. Must-have.
![image](https://user-images.githubusercontent.com/124446204/216783175-01701629-e5a7-47a9-bb2b-3e2a6cffa107.png)

**Comment by Thordekk** [comment]
Tested need sniff it to fix

**Comment by ahoffman1** [comment]
fixed
