### ISSUE TITLE
MONK/SPELL [ Summon White Tiger Statue ]

### ISSUE THREAD

**Issue by Donzin** [Thordekk/Dekk-Core-Donator-Bugtracker#403]
Spell Don't work, When summoned the white tiger statue, it should deal AOE damage, and it also cannot follow the tank!

https://www.wowhead.com/spell=388686/summon-white-tiger-statue
![image](https://user-images.githubusercontent.com/124446204/216783675-7e752548-b208-49b4-b685-eb9f4b688de3.png)

**Comment by Thordekk** [comment]
tested and working perfect for me follow caster and do aoe
