### ISSUE TITLE
MONK/SPELL [ Shuffle ] Big importance

### ISSUE THREAD

**Issue by Donzin** [Thordekk/Dekk-Core-Donator-Bugtracker#404]
Shuffle - Increases your Staggered value by 100%. Maintaining this buff is effortless if you use your key abilities on cooldown. This is yet another must-have at the top of the spec tree. Take it.
 
BUG: This Shuffle it should activate whenever the monk tank uses it [Keg Smash](https://www.wowhead.com/spell=121253/keg-smash),[Hit Scheme](https://www.wowhead.com/spell=383695/hit-scheme), [Spinning Crane Kick](https://www.wowhead.com/spell=101546/spinning-crane-kick)

https://www.wowhead.com/guide/classes/monk/brewmaster/abilities-talents-pve-tank
![image](https://user-images.githubusercontent.com/124446204/216784095-4ae60b2d-30f6-4bae-9590-6f2f68cd428e.png)

**Comment by Thordekk** [comment]
Proc now
