### ISSUE TITLE
MONK/SPELL [Chi Burst]

### ISSUE THREAD

**Issue by Donzin** [Thordekk/Dekk-Core-Donator-Bugtracker#406]
Chi Burst - Deals damage to all targets in the line, generates 1 chi.
 
 BUG: The spell is not working, it is not giving damage and healing

![Sem título](https://user-images.githubusercontent.com/124446204/216784823-fe1ae0e0-94bd-4b25-a004-a900ba80d5db.png)

**Comment by Thordekk** [comment]
always add woeheadlink please
use addon id tip in game to see spell id

**Comment by Thordekk** [comment]
Well is areatrigger issue i fix soon
