### ISSUE TITLE
Gathering Professions wrong Icons

### ISSUE THREAD

**Issue by Ursonne** [Thordekk/Dekk-Core-Donator-Bugtracker#41]
On the Gathering Professions there are wrong mouse icons on some nodes. And some are invalid when you click them.

![image](https://user-images.githubusercontent.com/34980984/162467976-fc3a0036-8169-4cad-a08a-fa59c16c80b2.png)
For Example, copper // Dun Morogh

![image](https://user-images.githubusercontent.com/34980984/162468078-f425d799-26e2-4ce7-82fe-237fb9e960e8.png)
Earthroot // Dun Morogh = Wrong (Black Icon)

![image](https://user-images.githubusercontent.com/34980984/162469494-cdccb82b-2ab7-4a14-be7e-df7af68e65ce.png)
Earthroot // Barrens = All fine

**Comment by Thordekk** [comment]
Being fixed
