### ISSUE TITLE
Priest/Spell: Weal and Woe

### ISSUE THREAD

**Issue by PivanDepolo** [Thordekk/Dekk-Core-Donator-Bugtracker#439]
https://www.wowhead.com/spell=390787/weal-and-woe

Stacks not only from confession, but from all attacking and healing spells, from some abilities, such as Mind Explosion and Power Word: Radiance, for some reason, gains 2 stacks, stacks are also not absorbed by the abilities indicated in the talent. Also, this talent does not increase absorption from Power Word: Shield

**Comment by Thordekk** [comment]
Scripted need test soon
