### ISSUE TITLE
Priest/Spell: Protector of the Frail

### ISSUE THREAD

**Issue by PivanDepolo** [Thordekk/Dekk-Core-Donator-Bugtracker#441]
https://www.wowhead.com/spell=373035/protector-of-the-frail

does not reduce cd of [Pain Suppression](https://www.wowhead.com/spell=33206/pain-suppression)

![1](https://user-images.githubusercontent.com/64589699/217153875-b4cdaeed-6dbc-4ab5-be15-d20e47d584f7.jpg)
![WoWScrnShot_020723_003915](https://user-images.githubusercontent.com/64589699/217153883-7e3e2c64-ef85-4cfe-bc4f-293f58df66ef.jpg)

**Comment by Thordekk** [comment]
Scripted need test soon

**Comment by Thordekk** [comment]
works reducing cooldown
