### ISSUE TITLE
Priest/Spell: Sins of the Many

### ISSUE THREAD

**Issue by PivanDepolo** [Thordekk/Dekk-Core-Donator-Bugtracker#442]
https://www.wowhead.com/spell=280391/sins-of-the-many

is not displayed in buffs, in older versions of wow this buff permanently hung on the character, if I'm not mistaken, on your core this buff appeared several times in the buff line with a value of 12% additional damage, but it disappeared somewhere without a trace, so I don't sure it works

![WoWScrnShot_020723_003416](https://user-images.githubusercontent.com/64589699/217154240-e85ea230-efed-418a-bfac-df5ec476fdcb.jpg)

**Comment by Thordekk** [comment]
Visual bug spell working tested on debug
