### ISSUE TITLE
bug_script of the table of heroes with dimensions as and h2

### ISSUE THREAD

**Issue by Steyfix** [Thordekk/Dekk-Core-Donator-Bugtracker#449]
![image](https://user-images.githubusercontent.com/12504219/218141882-c55b4706-f9ca-4440-89c6-229029d23483.png)

Hello as the screen below shows it lacks the appearance of the images on the hero board selection as official. I don't know if it's on smart_ai

**Comment by Thordekk** [comment]
u say new warboard system?

**Comment by Steyfix** [comment]
yes ^^ sorry i expressed myself badly

**Comment by Steyfix** [comment]
yes this interface there
![nouvelle-interface-tableau-recrutement](https://user-images.githubusercontent.com/12504219/218314747-6c9011fe-93c1-4ead-89cd-d01a2b4fbaeb.jpg)

**Comment by Thordekk** [comment]
added initial work
