### ISSUE TITLE
Classic & TBC Dungeon crashing worldserver issues and other issues

### ISSUE THREAD

**Issue by KKBa20** [Thordekk/Dekk-Core-Donator-Bugtracker#471]
Bonus Objective bosses in these listed dungeons crash worldserver too.

Classic -
Ragefire Chasm - Lava Guard Gordoth - crashes worldserver.
https://www.wowhead.com/npc=61528/lava-guard-gordoth

The Stockades - Lord Overheat - crashes worldserver.
https://www.wowhead.com/ptr/npc=46264/lord-overheat

The Deadmines - Doorways through the instance need opened. Apart from first boss, the other bosses may need tested for crashing issues.

Scarlet Monastery - Doorways through the instance need opened, last two bosses may need tested for crashing issues.

Scarlet Halls - Flameweaver Koegler - crashes worldserver.
https://www.wowhead.com/npc=59150/flameweaver-koegler

Shadowfang Keep - Doorway to last boss, Lord Godfrey, needs opened. Lord Godfrey may need tested for crashing issues.
https://www.wowhead.com/npc=46964/lord-godfrey

The Temple of Atal'hakkar - Shade of Eranikus - crashes worldserver.
https://www.wowhead.com/classic/npc=5709/shade-of-eranikus

Zul'farrak - All bosses - crashes worldserver.

TBC-
Hellfire Ramparts - Vazurden the Herald - crashes worldserver
https://www.wowhead.com/tbc/npc=17307/vazruden-the-herald

The Blood Furnace - Keli'dan the Breaker - crashes worldserver
https://www.wowhead.com/npc=17377/kelidan-the-breaker

The Shattered Halls - Grand Warlock Nethekurse encounter doesn't work (He doesn't attack).
https://www.wowhead.com/wotlk/npc=16807/grand-warlock-nethekurse

The Slave Pens - Quagmirran - crashes worldserver
https://www.wowhead.com/npc=17942/quagmirran

The Steamvault - Warlord Kalithresh - crashes worldserver
https://www.wowhead.com/tbc/npc=17798/warlord-kalithresh

The Underbog - The Black Stalker - crashes worldserver
https://www.wowhead.com/tbc/npc=17882/the-black-stalker

Mana-tombs - Nexus-Prince Shaffar - crashes worldserver
https://www.wowhead.com/npc=18344/nexus-prince-shaffar

Sethekk Halls - Talon King Ikiss - crashes worldserver
https://www.wowhead.com/npc=18473/talon-king-ikiss

Shadow Labyrinth - Murmur - crashes worldserver
https://www.wowhead.com/npc=18708/murmur

Auchenai Crypts - Exarch Maladaar - crashes worldserver
https://www.wowhead.com/npc=18373/exarch-maladaar

The Mechanar - Pathaleon the Calculator - crashes worldserver
https://www.wowhead.com/tbc/npc=19220/pathaleon-the-calculator

The Botanica - Warp Splinter - crashes worldserver
https://www.wowhead.com/tbc/npc=17977/warp-splinter

The Arcatraz - Harbringer Skyriss - crashes worldserver
https://www.wowhead.com/tbc/npc=20912/harbinger-skyriss

**Comment by Thordekk** [comment]
Fixed crashes
