### ISSUE TITLE
Bug quest cant be completed #128242 Dk

### ISSUE THREAD

**Issue by mauuser1928** [Thordekk/Dekk-Core-Donator-Bugtracker#473]
https://www.wowhead.com/wotlk/quest=12842/runeforging-preparation-for-battle

All the execution is done but when applying the spell or enchantment to the weapon it does not give the mission as completed.

// ** https://prnt.sc/pKUOR3_DKOhD *//

thank

**Comment by Thordekk** [comment]
Fixed
