### ISSUE TITLE
Nazmir area crashes error wow.exe

### ISSUE THREAD

**Issue by KKBa20** [Thordekk/Dekk-Core-Donator-Bugtracker#476]
In Bfa zone, Nazmir, Primal Wetlands, causes wow.exe an error crash Also, crashes when opening the map in that area too. 

https://user-images.githubusercontent.com/129208594/229247700-06d4523f-db55-4a31-b0f6-0278c5855c36.mp4

![IMG_4299](https://user-images.githubusercontent.com/129208594/229247704-4cdbc7ca-4136-483b-a16d-a3329808cfb7.jpg)

**Comment by Korsar1808** [comment]
<img width="320" alt="image" src="https://user-images.githubusercontent.com/59765795/229313088-b902f704-a331-44f1-8351-bec62cb5b375.png">

sorry but no crash for me
