### ISSUE TITLE
[Class] [Hunter] Spell 187650 Freezing Trap

### ISSUE THREAD

**Issue by Ursonne** [Thordekk/Dekk-Core-Donator-Bugtracker#48]
https://www.wowhead.com/spell=187650/freezing-trap

The Skill / Spell don't trigger when a creature walks over it.

**Comment by Thordekk** [comment]
Confirmed

**Comment by Thordekk** [comment]
https://gyazo.com/b06742dec4e49cbe1e860942727d3b17
