### ISSUE TITLE
Level problem in the DH zone start solution changer worldserver.conf

### ISSUE THREAD

**Issue by mauuser1928** [Thordekk/Dekk-Core-Donator-Bugtracker#481]
They must go to the worldserver.conf configuration and change the appearance of DH to level 8, this way all the npcs, zone and set will automatically stop at the correct level without touching anything in the DB.

pictures "  https://prnt.sc/06fBY1LQDcjv " 

line 900  ---- StartDemonHunterPlayerLevel = 8

Ready

**Comment by Thordekk** [comment]
Added thanks
