### ISSUE TITLE
 Dungeon Boss drops server on kill =  DUNGEON > IGNEOUS CHALLENGE  > Server Crashea

### ISSUE THREAD

**Issue by mauuser1928** [Thordekk/Dekk-Core-Donator-Bugtracker#486]
Error one = when entering the dungeon there are duplicate npcs.

Error Two = when you fight npc 11517 Ogglesflint Boss Burning Fury, it doesn't move and can't be focused.

Error Three = When you fight the last boss of the Lava Guard Gordoth dungeon, the server crashes completely.

//** https://prnt.sc/LZ3aCpOGlqFn **//

**Comment by Korsar1808** [comment]
<img width="337" alt="image" src="https://user-images.githubusercontent.com/59765795/230573100-16b41bbe-6174-401c-bb6f-6e26a0985ec8.png">

Guard Gordoth run no server crash
