### ISSUE TITLE
Drustvar area randomly teleports to Icecrown.

### ISSUE THREAD

**Issue by KKBa20** [Thordekk/Dekk-Core-Donator-Bugtracker#488]
Every time you enter Drustvar, Watchman's Rise, towards some npcs. You randomly get teleported to Icecrown Shadowlands intro.

https://user-images.githubusercontent.com/129208594/230660171-828af988-fd1a-4789-8c37-a48a2a60047d.mp4

**Comment by Thordekk** [comment]
Fixed i didnt get tp anymore
