### ISSUE TITLE
Bug quest #27347 corrosion prevention

### ISSUE THREAD

**Issue by Srboras** [Thordekk/Dekk-Core-Donator-Bugtracker#495]
Llink : https://www.wowhead.com/es/quest=27347/prevenci%C3%B3n-de-la-corrosi%C3%B3n

Example video: https://www.youtube.com/watch?v=QeY45q0DpUs

problem: When we use the power of [Snot Popper] it does not affect the pnj

 ID item=33108

**Comment by Thordekk** [comment]
Fixed
