### ISSUE TITLE
bug quest #25187 Lost in the overflow

### ISSUE THREAD

**Issue by Srboras** [Thordekk/Dekk-Core-Donator-Bugtracker#496]
Llink : https://www.wowhead.com/es/quest=25187/perdidos-en-el-desbordamiento

Example video:  https://www.youtube.com/watch?v=etduJdcSDDQ

problem: We cannot use Thonk's spyglass to search for recent cataclysmic

ID item=52514

**Comment by Thordekk** [comment]
Fixed use the item cancel cinematic and ready
