### ISSUE TITLE
bug quest # 64873 Stretch Your Wings "Dragonflight"

### ISSUE THREAD

**Issue by Srboras** [Thordekk/Dekk-Core-Donator-Bugtracker#507]
Llink : https://www.wowhead.com/quest=64873/stretch-your-wings

Example video: https://www.youtube.com/watch?v=wHFDbZ__k3E

problem: When we talk to Darvishian he doesn't give you the power called [Soar Up] to be able to fly and reach the of the next point.

npc=193890
SpellD 367916

**Comment by Thordekk** [comment]
duplicate report
