### ISSUE TITLE
Bug quest # 9193 investiga las catacumbas amani 

### ISSUE THREAD

**Issue by Srboras** [Thordekk/Dekk-Core-Donator-Bugtracker#510]
link: https://www.wowhead.com/es/quest=9193/investiga-las-catacumbas-amani#comments

Example Video:  https://www.youtube.com/watch?v=YymqGrresBI&t=2s

Problem:The quest can be successfully completed but cannot be delivered to the following NPC: Ranger Vynna

Npc ID: 16203

**Comment by Thordekk** [comment]
Fixed
