### ISSUE TITLE
SpellD #364342 Blessing of the Bronze "Dragonflight"

### ISSUE THREAD

**Issue by Srboras** [Thordekk/Dekk-Core-Donator-Bugtracker#512]
link: https://www.wowhead.com/spell=364342/blessing-of-the-bronze

problem:  this ability gives us 12 runes of power. 

SpellD 364342

![image](https://user-images.githubusercontent.com/89896094/232194433-24bdda7a-c37b-4b8d-beba-cc3a2103a705.png)

**Comment by Thordekk** [comment]
disable custom zolocraft xD
