### ISSUE TITLE
Bug quest 55879 The ride of the scientifically modified boar

### ISSUE THREAD

**Issue by Steyfix** [Thordekk/Dekk-Core-Donator-Bugtracker#523]
as we can see on the screen Torgok id 162817 is dead and therefore impossible to attack him and validate the quest. And the boar once you go down and back up on it pops another one of the possible spam moves for the player.

![image](https://user-images.githubusercontent.com/12504219/234878623-fda88bc4-9fa0-4513-8558-ba646dfdccd4.png)

![image](https://user-images.githubusercontent.com/12504219/234878874-13003a1d-81c3-4b49-ae92-a939b8e7d6eb.png)

**Comment by Korsar1808** [comment]
Not dead prehaps you have kill him at prev Quest?

**Comment by Steyfix** [comment]
hello thank you for your answer to start strange because on my side I have the impression that it is a concern of flag you could export the line of the pnj in sql stp? I thank you
