### ISSUE TITLE
[CRITICAL] Server crash 1

### ISSUE THREAD

**Issue by NesinAlex** [Thordekk/Dekk-Core-Donator-Bugtracker#532]
Server crash for unknown reasons. Segmentation fault. Last log entry "WORLD: unknown spell id 198152 at use action for gameobject (Entry: 245728 GoType: 10)"

**Comment by NesinAlex** [comment]
![image](https://github.com/Thordekk/Dekk-Core-Donator-Bugtracker/assets/42183646/71239fd8-18a2-4874-9e95-a4f8f9a55b37)

**Comment by Thordekk** [comment]
FIxed
