### ISSUE TITLE
Missing NPC on Caravan Brutosaurus Mount

### ISSUE THREAD

**Issue by Steyfix** [Thordekk/Dekk-Core-Donator-Bugtracker#533]
![image](https://github.com/Thordekk/Dekk-Core-Donator-Bugtracker/assets/12504219/e338d09d-900d-4bbf-a6e4-b60ec021d9ba)
As you can see in the photo, the trader njs are missing on the mount.

**Comment by Thordekk** [comment]
They appear in ground need fix vehicle

**Comment by ahoffman1** [comment]
Other vendor mounts have the same issue:
https://github.com/Thordekk/Dekk-Core-Donator-Bugtracker/issues/569

**Comment by Thordekk** [comment]
Fixed
