### ISSUE TITLE
Bug quest The Meltdown Mine id 62

### ISSUE THREAD

**Issue by Steyfix** [Thordekk/Dekk-Core-Donator-Bugtracker#534]
So for this quest we have several concerns like the first one who arrives in the cave where the quest is validated but does not display the validation message in yellow in the middle of the screen. Then the second problem and that we cannot return the quest to the pnj which is however mentioned as finished but as we see on the screen we are blocked.

![image](https://github.com/Thordekk/Dekk-Core-Donator-Bugtracker/assets/12504219/e1a8063f-99ab-4b18-b2d1-cf90a8e35303)
![image](https://github.com/Thordekk/Dekk-Core-Donator-Bugtracker/assets/12504219/a3ca4356-5715-4b8f-afe5-71995a86ee6b)

**Comment by Thordekk** [comment]
Fixed
