### ISSUE TITLE
Sorting in bags does not work.

### ISSUE THREAD

**Issue by NesinAlex** [Thordekk/Dekk-Core-Donator-Bugtracker#536]
Clicking the sort button does nothing.
![image](https://github.com/Thordekk/Dekk-Core-Donator-Bugtracker/assets/42183646/ddb30bb6-5058-476b-9054-9beaf8f4361e)

**Comment by Thordekk** [comment]
on bags or bank?

**Comment by NesinAlex** [comment]
on bags (as on screenshot)

**Comment by Thordekk** [comment]
Fixed
