### ISSUE TITLE
Boats in Stormwind float across the bridge.

### ISSUE THREAD

**Issue by NesinAlex** [Thordekk/Dekk-Core-Donator-Bugtracker#537]
Boats in Stormwind float across the bridge. You can even sit in them.
![image](https://github.com/Thordekk/Dekk-Core-Donator-Bugtracker/assets/42183646/e7e61302-93e6-4c44-99c7-628d8536b5a2)

**Comment by Thordekk** [comment]
Use mmaps and ready not appear there
