### ISSUE TITLE
The name declension window does not stop appearing.

### ISSUE THREAD

**Issue by NesinAlex** [Thordekk/Dekk-Core-Donator-Bugtracker#538]
In ruRU, it constantly asks for the declension of the name.
![image](https://github.com/Thordekk/Dekk-Core-Donator-Bugtracker/assets/42183646/9746eab9-9d70-4deb-802d-4cf2f4fe0c67)

**Comment by Thordekk** [comment]
explain better and add screenshots of english please

**Comment by NesinAlex** [comment]
When you input a ruRU name, the game ask you to fill all cases (possessive case, genetive, accusative, dative, etc) of name. Having done this once, the window should no longer appear.

I believe that a screenshot of this window in English cannot be made.
