### ISSUE TITLE
NPC Teacher 47384/lien-farner does not teach.

### ISSUE THREAD

**Issue by NesinAlex** [Thordekk/Dekk-Core-Donator-Bugtracker#541]
https://www.wowhead.com/npc=47384/lien-farner
All items are active, but clicking on them does nothing.
![image](https://github.com/Thordekk/Dekk-Core-Donator-Bugtracker/assets/42183646/4d372fef-2e5f-47cc-93fd-5a5293d8ae8f)

**Comment by Thordekk** [comment]
Soon we apply the fix
