### ISSUE TITLE
Spell 178940/shattered-souls spawns spheres, but they cannot be picked up.

### ISSUE THREAD

**Issue by NesinAlex** [Thordekk/Dekk-Core-Donator-Bugtracker#543]
https://www.wowhead.com/spell=178940/shattered-souls
![image](https://github.com/Thordekk/Dekk-Core-Donator-Bugtracker/assets/42183646/7e12be13-8a48-408d-aa67-dafe28923d0f)

**Comment by ahoffman1** [comment]
fixed
