### ISSUE TITLE
Stormwind Heirloom vendor prices

### ISSUE THREAD

**Issue by NesinAlex** [Thordekk/Dekk-Core-Donator-Bugtracker#544]
![image](https://github.com/Thordekk/Dekk-Core-Donator-Bugtracker/assets/42183646/8b2eeb12-d965-4402-8945-30d65344da49)

Prices should be like this
https://www.wowhead.com/npc=6566/estelle-gendry#sells;50

**Comment by Thordekk** [comment]
are custom
