### ISSUE TITLE
Leveling scale problems zone=1581/the-deadmines and others

### ISSUE THREAD

**Issue by NesinAlex** [Thordekk/Dekk-Core-Donator-Bugtracker#547]
Enemies at the same time 1 and 13 levels and skulls. And not only in the dungeon, but also in the open world.
https://www.wowhead.com/zone=1581/the-deadmines
![image](https://github.com/Thordekk/Dekk-Core-Donator-Bugtracker/assets/42183646/dc6d84a0-978a-446b-b3aa-bd563592470e)

must be level 7-50 like here
![image](https://github.com/Thordekk/Dekk-Core-Donator-Bugtracker/assets/42183646/764076b5-cdd4-4a4e-8f3d-b6d20b97a259)

my settings
![image](https://github.com/Thordekk/Dekk-Core-Donator-Bugtracker/assets/42183646/51f3837a-710e-4496-abea-8fb44610ddb1)

**Comment by Thordekk** [comment]
need sniffs

**Comment by NesinAlex** [comment]
Me and my players can't do that. I don't even have a subscription.

**Comment by Thordekk** [comment]
Fixed scaling all maps
