### ISSUE TITLE
The problem with resurrection zone=717/the-stockade

### ISSUE THREAD

**Issue by NesinAlex** [Thordekk/Dekk-Core-Donator-Bugtracker#548]
When you die in a dungeon, there is no way to resurrect. You have to restart the game. I appear outside the dungeon, I go into it, and the resurrection does not occur.

The only way out is to resurrect with an angel with a debuff.

the-stockade - does not resurrect
ragefire-chasm - as not tested
the-deadmines - resurrects

https://www.wowhead.com/zone=717/the-stockade
![image](https://github.com/Thordekk/Dekk-Core-Donator-Bugtracker/assets/42183646/74d28a03-c994-4bf7-8fb3-92d0b9016412)

**Comment by Thordekk** [comment]
Fixed
