### ISSUE TITLE
[CRITICAL] Server Crash 2

### ISSUE THREAD

**Issue by NesinAlex** [Thordekk/Dekk-Core-Donator-Bugtracker#549]
Reason unknown (how you will fix without stacktrace idn)
Segmentation fault
![image](https://github.com/Thordekk/Dekk-Core-Donator-Bugtracker/assets/42183646/4776ddaa-2493-4e96-8d87-c9e6e864dffb)

**Comment by NesinAlex** [comment]
Connected gdb debugger.

**Comment by NesinAlex** [comment]
backtrace
![image](https://github.com/Thordekk/Dekk-Core-Donator-Bugtracker/assets/42183646/23229dee-f88c-411b-98e2-36a16408de8d)

**Comment by NesinAlex** [comment]
code
![image](https://github.com/Thordekk/Dekk-Core-Donator-Bugtracker/assets/42183646/767b7ed0-caa2-407f-83e2-85928df4960b)

**Comment by Thordekk** [comment]
Fixed only one crash on panda starting zone need fix
