### ISSUE TITLE
Immortal cow

### ISSUE THREAD

**Issue by NesinAlex** [Thordekk/Dekk-Core-Donator-Bugtracker#550]
![image](https://github.com/Thordekk/Dekk-Core-Donator-Bugtracker/assets/42183646/740957a7-fec1-4269-9500-3ebff262305c)

**Comment by Thordekk** [comment]
Npc id?  use addon id tip

**Comment by ahoffman1** [comment]
Cow id 2442
https://www.wowhead.com/npc=2442/cow

https://github.com/Thordekk/Dekk-Core-Donator-Bugtracker/assets/1356757/db0378ed-fae5-407c-a605-9c6c2342791f

**Comment by NesinAlex** [comment]
It seems that all NPCs with 1 health are immortal

**Comment by Thordekk** [comment]
fixed
