### ISSUE TITLE
[CRITICAL] [DUPLICATE] Unlimited chest 

### ISSUE THREAD

**Issue by NesinAlex** [Thordekk/Dekk-Core-Donator-Bugtracker#551]
This chest can be looted endlessly, it does not disappear.
Small Treasure Chest
![image](https://github.com/Thordekk/Dekk-Core-Donator-Bugtracker/assets/42183646/1fa891e6-a334-41a1-a71b-265a79941f32)

**Comment by Thordekk** [comment]
add id in reports

**Comment by Thordekk** [comment]
Fixed
