### ISSUE TITLE
CHROMIE - Need fix choice Back to Present!

### ISSUE THREAD

**Issue by mudyx** [Thordekk/Dekk-Core-Donator-Bugtracker#552]
Changing expansion seem to working but if you need back to present (Dragonflight) you cannot becasue this choice not working.

https://www.wowhead.com/npc=167032/chromie
![Screenshot_2](https://github.com/Thordekk/Dekk-Core-Donator-Bugtracker/assets/128794239/e483afdf-26b5-477a-9b7e-5c484ca2e873)

**Comment by Thordekk** [comment]
Being fixed soon
