### ISSUE TITLE
Night Warrior customization 

### ISSUE THREAD

**Issue by KKBa20** [Thordekk/Dekk-Core-Donator-Bugtracker#555]
The Night Warrior customization dark eyes aren't unlocked or useable, and they cannot be unlocked.

https://www.wowhead.com/spell=285907/blessing-of-the-night-warrior

**Comment by ahoffman1** [comment]
fixed, turn in the quest https://www.wowhead.com/quest=53990/in-darkest-night at https://www.wowhead.com/npc=149612/shandris-feathermoon
