### ISSUE TITLE
Several 'Halls of Reflection' issues, making it unplayable

### ISSUE THREAD

**Issue by ahoffman1** [Thordekk/Dekk-Core-Donator-Bugtracker#559]
This was tested on a level 30 Alliance character.

https://www.dropbox.com/s/8wrrl8bdi83g08q/World%20Of%20Warcraft%202023.05.15%20-%2017.35.47.62.DVR.mp4?dl=0

https://www.dropbox.com/s/sb2q6ibjauu1zx5/World%20Of%20Warcraft%202023.05.15%20-%2017.43.03.63.DVR.mp4?dl=0

- Multiple Jainas and Sylvannases (supposed to be one Jaina _or_ Sylvannas depending on if the player is Horde or Alliance)
Jaina ID: 37221
Sylvannas ID: 37223

- All the ghosts around the room are already spawned (not supposed to be), hostile and immediately attack the player
- Uther doesn't spawn during the sequence, but his dialogue text is displayed in the chat
- Random not moving Lich King seen behind the door when it opens (a second one walks into the room)
- The Lich King grabbing sword doesn't remove the object, and during the remove animation a duplicate Frostmourne is going through his chest
- Marwyn fight crashes world server (couldn't progress further)

Intended behavior:
https://www.youtube.com/watch?v=U4gmguq4oHc&t=13s

**Comment by Thordekk** [comment]
Need make conditions to factions
