### ISSUE TITLE
Culling of Stratholme issues, unplayable

### ISSUE THREAD

**Issue by ahoffman1** [Thordekk/Dekk-Core-Donator-Bugtracker#561]
This was tested on a level 50 Alliance character.

- I cannot enter as anything above level 60.

- Interacting with Chromie (https://www.wowhead.com/npc=26527/chromie) and pressing dialogue options asks if I want to purchase Dual Spec (clicking confirms dialogue options and does not buy it). This still gives the Arcane Disruptor, but asks for dual specialization.
![image](https://github.com/Thordekk/Dekk-Core-Donator-Bugtracker/assets/1356757/1548af50-7116-4474-8ecd-1d5bc1cf6a11)

- Plagued crate models are not spawned in, beams are visible
![image](https://github.com/Thordekk/Dekk-Core-Donator-Bugtracker/assets/1356757/77f2bb28-24c9-4247-8339-dcbcffeb094c)
![image](https://github.com/Thordekk/Dekk-Core-Donator-Bugtracker/assets/1356757/3d548dca-5395-4743-9f19-af560bbc7340)
All of them are like that, that's just two examples

- Chromie (https://www.wowhead.com/npc=27915/chromie) does the same dual specialization dialogue issue)
![image](https://github.com/Thordekk/Dekk-Core-Donator-Bugtracker/assets/1356757/826f1219-92a9-4161-9c0f-ead45efa8eff)

- Uther (https://www.wowhead.com/npc=26528/uther-the-lightbringer) and Knights of the Silver Hand (https://www.wowhead.com/npc=28612/knight-of-the-silver-hand) spawned in before scripted event happens:
![image](https://github.com/Thordekk/Dekk-Core-Donator-Bugtracker/assets/1356757/1a70ee93-881e-4dd8-83e3-84ceb57cc17f)
- Jaina (https://www.wowhead.com/npc=26497/lady-jaina-proudmoore) spawned in before scripted event happens
![image](https://github.com/Thordekk/Dekk-Core-Donator-Bugtracker/assets/1356757/28e3a97f-8486-4f60-a0b4-628741bd1cd9)

- Talking to Chromie (https://www.wowhead.com/npc=27915/chromie) to start the scripted event spawns a second set of Uthers
![image](https://github.com/Thordekk/Dekk-Core-Donator-Bugtracker/assets/1356757/b41b9446-982b-4c6e-a352-6b3bed14d467)
-  Talking to Chromie (https://www.wowhead.com/npc=27915/chromie) to start the scripted event doesn't actually start the event, the Uther spawns and nothing happens.

- Arthas (https://www.wowhead.com/npc=26499/arthas) spawns correctly on the bridge, but never does anything
![image](https://github.com/Thordekk/Dekk-Core-Donator-Bugtracker/assets/1356757/3a039905-1ae7-4297-be48-0f4eae80aa54)
 
- Mal'Ganis (https://www.wowhead.com/npc=26533/malganis) already spawned in the entire time in the entrance of the city, but not attackable
![image](https://github.com/Thordekk/Dekk-Core-Donator-Bugtracker/assets/1356757/36298408-4c07-48f9-8c9a-1d3e42306627)

I cannot test anything further, since the scripted event never happens

Intended behavior:
https://www.youtube.com/watch?v=PvtsLfBOwec

**Comment by Thordekk** [comment]
Fixed gossips

**Comment by Thordekk** [comment]
https://gyazo.com/16846836b4b63b45d5ba9922a6dde395
