### ISSUE TITLE
Mounts with vendors don't work

### ISSUE THREAD

**Issue by ahoffman1** [Thordekk/Dekk-Core-Donator-Bugtracker#569]
The [Grand Expedition Yak](https://www.wowhead.com/item=84101/reins-of-the-grand-expedition-yak)'s vendors are not attached:

https://github.com/Thordekk/Dekk-Core-Donator-Bugtracker/assets/1356757/87a9158f-edbc-4434-9727-4dbf96508e6d

[Traveler's Tundra Mammoth](https://www.wowhead.com/item=44235/reins-of-the-travelers-tundra-mammoth) has no vendors at all.
For Alliance characters, the two vendors on the mammoth's side seats are Gnimo (https://www.wowhead.com/npc=32639/gnimo) and Hakmud of Argus (https://www.wowhead.com/npc=32638/hakmud-of-argus).

For Horde characters, the vendors are: Drix Blackwrench (https://www.wowhead.com/npc=32641/drix-blackwrench) and Mojodishu (https://www.wowhead.com/npc=32642/mojodishu).
![image](https://github.com/Thordekk/Dekk-Core-Donator-Bugtracker/assets/1356757/327b840e-b6eb-4f97-bb6f-7fc57fccc320)
retail:
![image](https://github.com/Thordekk/Dekk-Core-Donator-Bugtracker/assets/1356757/acb136eb-2c16-49c2-8587-bca937079f3f)

The [Mighty Caravan Brutosaur's](https://www.wowhead.com/item=163042/reins-of-the-mighty-caravan-brutosaur) vendors are not attached:

https://github.com/Thordekk/Dekk-Core-Donator-Bugtracker/assets/1356757/4d84513b-5945-4bbe-b7f1-ab9e5be5730f

**Comment by Thordekk** [comment]
Vehicle issue already reported
