### ISSUE TITLE
Holiday event NPCs and spells exist outside of the event timeframe

### ISSUE THREAD

**Issue by ahoffman1** [Thordekk/Dekk-Core-Donator-Bugtracker#573]
It is currently May 16th, 2023

### -- Love is in the Air (February 6 - February 20) --
- Kwee Q. Peddlefeet (37887), Lovely Merchant (37674), Public Relations Agent (37675), and Inspector Snip Snagglebolt (38066) are present
![image](https://github.com/Thordekk/Dekk-Core-Donator-Bugtracker/assets/1356757/b30b4951-e06e-4979-95bb-76bca734bc30)
![image](https://github.com/Thordekk/Dekk-Core-Donator-Bugtracker/assets/1356757/f5d0c820-bf97-440e-a800-43f279044152)
- Stormwind Love Boat (36812) driving around the river (only supposed to happen during the Love is in the Air event)
![image](https://github.com/Thordekk/Dekk-Core-Donator-Bugtracker/assets/1356757/014a4eec-fa13-4115-b2fa-2526ab7bd071)
- Stormwind Love Boats (36812) drive on the sidewalk still, even though I have mmaps
![image](https://github.com/Thordekk/Dekk-Core-Donator-Bugtracker/assets/1356757/014a4eec-fa13-4115-b2fa-2526ab7bd071)
https://www.dropbox.com/s/wifi1b3ssxxzzlv/World%20Of%20Warcraft%202023.05.16%20-%2012.14.25.06.DVR.mp4?dl=0
![image](https://github.com/Thordekk/Dekk-Core-Donator-Bugtracker/assets/1356757/e0505751-4ce6-4fe4-b269-325c7bc1ad90)

-Heavenly Perfume (spell 71507) effect is active on most Stormwind City guards (npc 68), probably from the Love is in the Air quest (24629) . It is May, not during love is in the air event https://www.wowhead.com/quest=24629/a-perfect-puff-of-perfume
https://www.wowhead.com/spell=71507/heavily-perfumed 
![image](https://github.com/Thordekk/Dekk-Core-Donator-Bugtracker/assets/1356757/ae956ead-a327-43af-92bf-7fc6121ef4a4)

### -- Darkmoon Fair -- first Sunday of each month and leaves at the end of the day the following Saturday.
- "Come visit the Darkmoon Fair" poster on the wall even though the Darkmoon Fair isn't happening
![image](https://github.com/Thordekk/Dekk-Core-Donator-Bugtracker/assets/1356757/c77b8817-94ee-4115-a259-0e79b2afb24d)
![image](https://github.com/Thordekk/Dekk-Core-Donator-Bugtracker/assets/1356757/01c5a9e8-b1bc-4b52-8503-c6db8b32842d)

### -- Children's Week -- (May 1st - May 8th)
- 2 copies of Orphan Matron Nightingale (14550, 51998) present even though Children's Week event is over (May 1st - May 8th), coordinates 56.3, 54.1
![image](https://github.com/Thordekk/Dekk-Core-Donator-Bugtracker/assets/1356757/3046c5e8-028d-4222-b041-0bfe321979a3)
![image](https://github.com/Thordekk/Dekk-Core-Donator-Bugtracker/assets/1356757/746dac2b-1669-4aa4-9319-229bfd37cd0d)

**Comment by Thordekk** [comment]
All events not work we dont plan to fix soon take more time
