### ISSUE TITLE
Faithful Watchdog (Stormsong Valley) show they are alive/dead

### ISSUE THREAD

**Issue by ahoffman1** [Thordekk/Dekk-Core-Donator-Bugtracker#576]
These Faithful Dogs (https://www.wowhead.com/npc=130452/faithful-watchdog) show they are dead and alive at the same time

https://github.com/Thordekk/Dekk-Core-Donator-Bugtracker/assets/1356757/c64b57f9-c61f-4d93-b8ca-92b7f927289c

![image](https://github.com/Thordekk/Dekk-Core-Donator-Bugtracker/assets/1356757/fa11f329-9efa-438c-abd9-b30b00160dc1)

**Comment by Thordekk** [comment]
Fixed
