### ISSUE TITLE
Boats in Stormwind float across the bridge 2

### ISSUE THREAD

**Issue by NesinAlex** [Thordekk/Dekk-Core-Donator-Bugtracker#578]
Mmaps enabled
Fresh mmap vmaps maps files uploaded
No more errors about mmaps in console (there were errors last time)

BUT

![image](https://github.com/Thordekk/Dekk-Core-Donator-Bugtracker/assets/42183646/20ddc4f6-105c-400a-9512-b28d53e63996)

**Comment by NesinAlex** [comment]
Boat ID 36812

**Comment by NesinAlex** [comment]
Also, at the finish point, boats are doubled and tripled, etc.
![image](https://github.com/Thordekk/Dekk-Core-Donator-Bugtracker/assets/42183646/6e411ac5-7c3a-4682-9119-878e63df2b74)

**Comment by ahoffman1** [comment]
I included it in https://github.com/Thordekk/Dekk-Core-Donator-Bugtracker/issues/573 , the boats aren't supposed to even be there outside the 'Love is in the Air' event

**Comment by NesinAlex** [comment]
![image](https://github.com/Thordekk/Dekk-Core-Donator-Bugtracker/assets/42183646/d31f1aad-f025-4b34-8105-0de799e6eec0)

**Comment by ahoffman1** [comment]
fixed
