### ISSUE TITLE
[Transmog] Weapon Enchants

### ISSUE THREAD

**Issue by Ursonne** [Thordekk/Dekk-Core-Donator-Bugtracker#58]
Wowhead Links (For example)
https://www.wowhead.com/item=138802/illusion-power-torrent
https://www.wowhead.com/item=172177/illusion-wraithchill

When you use the Illusion-Items to learn a transmog weapon illusion(?) / Enchant

You don't unlock the transmog option

**Comment by Thordekk** [comment]
click on weapon enchantment
