### ISSUE TITLE
Vale of Eternal Blossoms Engineer-specific NPCs don't detect Engineering

### ISSUE THREAD

**Issue by ahoffman1** [Thordekk/Dekk-Core-Donator-Bugtracker#582]
Tested as level 50 alliance character.

- H.A.R.V.E.Y. (https://www.wowhead.com/npc=65599/h-a-r-v-e-y) is supposed to be an auctioneer for Engineers, but he doesn't detect that the player is an Engineer.
![image](https://github.com/Thordekk/Dekk-Core-Donator-Bugtracker/assets/1356757/825d8ba7-b28b-4224-a370-197ccc425863)

- Lil' Canny (https://www.wowhead.com/npc=65596/lil-canny) is supposed to act as a bank for Engineers, but he is not interactable at all (no dialogue window or anything)
![image](https://github.com/Thordekk/Dekk-Core-Donator-Bugtracker/assets/1356757/c945840f-5091-4b69-b342-12321657607f)

![image](https://github.com/Thordekk/Dekk-Core-Donator-Bugtracker/assets/1356757/ea2669ea-8b3a-47cf-bb8b-f2de2d680235)

**Comment by Thordekk** [comment]
Fixed
