### ISSUE TITLE
(quest 47098) Out Like Flynn: first gate closed and other issues

### ISSUE THREAD

**Issue by ahoffman1** [Thordekk/Dekk-Core-Donator-Bugtracker#585]
https://www.wowhead.com/quest=47098/out-like-flynn

- (minor) Flynn starts standing up (as opposed to sitting in retail)

- The cell gate is closed, and never opens, preventing the player from pulling the Cell Block Lever (next step).
In retail, the cell is never closed at all and allows the player to leave immediately

DekkCore:
https://www.dropbox.com/s/gssfu0pxl0nngc3/World%20Of%20Warcraft%202023.05.16%20-%2017.54.01.15.DVR.mp4?dl=0
Retail:
https://youtu.be/kcvdog6UU5w

Logging out and back in completely removes the cell door.

## More issues on this specific quest: 
- After pulling the lever, one Tol Dagor Inmate spawns, even though there are supposed to be a done running around
DekkCore: https://www.dropbox.com/s/lbfw5c1bmov1qvk/pullinglever.mp4?dl=0
Retail: https://youtu.be/kcvdog6UU5w?t=31

- Interacting with the gate should blow the lock open, but it just teleports the player to the other side and blocks them from going back
DekkCore: https://www.dropbox.com/s/nsqpvy51a1tif5y/teleportgate.mp4?dl=0
Retail: https://youtu.be/kcvdog6UU5w?t=136

Boat ride ---
- At the rideable boat, Flynn Fairwind and Taelia are not in the boat paddling it and no dialogue is being said
- The camera gets sent really far away before it fades to black, then the camera is under a mountain before placing in the right position
DekkCore: https://www.dropbox.com/s/09t1j6ime19qumu/boatride.mp4?dl=0
Retail: https://youtu.be/kcvdog6UU5w?t=196

**Comment by Thordekk** [comment]
fixed
