### ISSUE TITLE
Black Market NPC missing / non-functional

### ISSUE THREAD

**Issue by ahoffman1** [Thordekk/Dekk-Core-Donator-Bugtracker#587]
- In Draenor Nagrand, Madam Goya (https://www.wowhead.com/npc=83867/madam-goya) opens the Black Market, but:
1) All of the auctions are completed
2) The entire black market (every single item) is on the list, instead of a random few, changing daily
![image](https://github.com/Thordekk/Dekk-Core-Donator-Bugtracker/assets/1356757/dacd75f3-e906-485a-a313-14f73cb35168)

- In Legion Dalaran, Madam Goya (https://www.wowhead.com/npc=100986/madam-goya) is completely missing
![image](https://github.com/Thordekk/Dekk-Core-Donator-Bugtracker/assets/1356757/dacb4582-a20b-41ea-813e-51c9dbb7e7d9)

- In Boralus, Madam Gosu (https://www.wowhead.com/npc=142062/madam-gosu) is present, but not interactable
![image](https://github.com/Thordekk/Dekk-Core-Donator-Bugtracker/assets/1356757/07e3e3cb-5bf1-4628-81aa-cc9fee657e1b)

- In Revendreth, Ta'xera (https://www.wowhead.com/npc=160081/taxera) opens the Black Market, and has the same problem as Madam Goya in Draenor
![image](https://github.com/Thordekk/Dekk-Core-Donator-Bugtracker/assets/1356757/80ef4509-dfc3-4b5d-9504-b74639fad086)

- In Valdrakken, Madam Goya (https://www.wowhead.com/npc=189676/madam-goya) is not interactable
![image](https://github.com/Thordekk/Dekk-Core-Donator-Bugtracker/assets/1356757/57a5205a-97ff-494f-a6ef-d612f55c5ed5)

**Comment by Thordekk** [comment]
Fixed all npcs but blackmarket will be checked soon
