### ISSUE TITLE
Northrend Dalaran Engineering Auction House non-functional

### ISSUE THREAD

**Issue by ahoffman1** [Thordekk/Dekk-Core-Donator-Bugtracker#588]
This was tested as a level 50 Alliance character.

As an Alliance Engineer, Brassbolt Mechawrench (https://www.wowhead.com/npc=35594/brassbolt-mechawrench) is supposed to allow the player to interact with him and use the Auction House.

As a Horde Engineer, Reginald Arcfire (https://www.wowhead.com/npc=35607/reginald-arcfire) is supposed to allow the player to interact with him and use the Auction House.

Only the one associated with the faction the player is on should appear, but both do at the same time. The friendly one can be interacted with, but does not open the auction house, just a generic dialog window

![image](https://github.com/Thordekk/Dekk-Core-Donator-Bugtracker/assets/1356757/3f0d7e5c-3a48-4ede-899d-c241ab477201)

**Comment by Thordekk** [comment]
Fixed
