### ISSUE TITLE
Gameobject missing on the wall

### ISSUE THREAD

**Issue by Steyfix** [Thordekk/Dekk-Core-Donator-Bugtracker#596]
Hello the hero board gameobject is missing on the wall of the lion's pride inn in elwyn forest
![WoWScrnShot_051723_163854](https://github.com/Thordekk/Dekk-Core-Donator-Bugtracker/assets/12504219/e9d9dd02-8343-4b59-bd97-bbf6bd173d54)

**Comment by Thordekk** [comment]
if its for quest add id please always add id

**Comment by Steyfix** [comment]
![WoWScrnShot_052323_172208](https://github.com/Thordekk/Dekk-Core-Donator-Bugtracker/assets/12504219/b558d775-263e-4975-a196-7fca578517c6)

I send you a screenshot of the official to show it

**Comment by Thordekk** [comment]
Spawned need sniffs from this object
