### ISSUE TITLE
QuestID: 53791 - The Pride of the Sin'dorei

### ISSUE THREAD

**Issue by brownbr** [Thordekk/Dekk-Core-Donator-Bugtracker#6]
When you get Exalted with Silvermoon, Ambassador Dawnsworn does not appear. Also, Lor'Themar Theron does not respond to said quest. The rest of the questline does not seem to function either.

**Comment by Thordekk** [comment]
Ure right npc is not spawned going to add him now

**Comment by Thordekk** [comment]
Need sniffs of that if someone can provide

**Comment by Thordekk** [comment]
https://gyazo.com/bf7189616c51f3d45b85d13fa5a6c998

**Comment by Thordekk** [comment]
Fixed
