### ISSUE TITLE
Duplicate Highlord Bolvar Fordragon in Shadowlands intro quest

### ISSUE THREAD

**Issue by ahoffman1** [Thordekk/Dekk-Core-Donator-Bugtracker#602]
Tested as level 50 Alliance character.

In the intro quests for shadowlands, on the Frozen Throne platform, there are two Bolvars (https://www.wowhead.com/npc=169076/highlord-bolvar-fordragon) standing inside each other, not animated at all

https://github.com/Thordekk/Dekk-Core-Donator-Bugtracker/assets/1356757/112a9484-ea9f-45cc-bf71-19184c32403b

**Comment by Thordekk** [comment]
Fixed
