### ISSUE TITLE
[CRITICAL] Server Crash 8 FieldValueConverter.cpp:47 

### ISSUE THREAD

**Issue by NesinAlex** [Thordekk/Dekk-Core-Donator-Bugtracker#605]
Loading battle pets info...
>> Loaded 0 battle pet breeds. DB table `battle_pet_breeds` is empty.
>> Loaded 0 battle pet qualities. DB table `battle_pet_quality` is empty.
Loading scenarios
>> Loaded 224 instance scenario entries in 1 ms
Loading scenario poi data
>> Loaded 91 scenario POI definitions in 5 ms
Loading active world quests templates...
Loading world quests rewards...
Loading Currencys Loot...
Loading phase names...
>> Loaded 3162 phase names in 17 ms.
Loading flux phases...
Loading Active World quests...
Loading Adventure Map UIs by Creatures...
>> Loaded 9 Adventure MapUI by Creature in 2 ms
Loading Zone Scripts...
>> Loaded 14 zone scriptnames in 1 ms
Loading Archaeology Digsites...
>> Loaded 450 Archaeology Digsites in 2 ms
Loading Character Challenges...
>> Loaded 0 Character Challenges in 1 ms
Loading Garrison Scripts...
>> Loaded 6 garrison scriptnames in 2 ms
Loading Quest task...
Loading battlepay data...
Loading Battlepay display info addons ...
Loading Battlepay display info ...
>> Loaded 82 Battlepay display info with 56 visual in 1 ms.
Loading Battlepay products ...
Loading Battlepay product groups ...
>> Loaded 14 Battlepay product groups in 0 ms
Loading Battlepay shop entries ...
>> Loaded 70 Battlepay shop entries in 0 ms
World initialized in 0 minutes 40 seconds
[New Thread 0x7ffdd7bff640 (LWP 404613)]
< DekkCore > rev. ee6f1961c844+ 2023-05-18 20:53:34 +0200 (master branch)Project Zereth (Unix, RelWithDebInfo, Static) (worldserver-daemon) ready...
[New Thread 0x7ffdd73fe640 (LWP 404614)]
|DekkCore| command:> GenerateOploteLoot manual false _challengeWeekList 0

/root/dekkcoreshadowlandsnew/src/server/database/Database/FieldValueConverter.cpp:47 in LogTruncation ASSERTION FAILED:
  false
Field::GetUInt32 on VAR_STRING field battlenet_accounts.battlePayCredits (battlenet_accounts.battlePayCredits) at index 0 caused value to be truncated. Use Field::GetString or Field::GetBinary instead.

Thread 1 "worldserver" received signal SIGSEGV, Segmentation fault.
0x0000555557660271 in Trinity::Assert (file=<optimized out>, line=line@entry=47, function=<optimized out>, debugInfo="", message=<optimized out>, format=<optimized out>) at /root/dekkcoreshadowlandsnew/src/common/Debugging/Errors.cpp:92
92          Crash(formattedMessage.c_str());

BACKTRACE

#0  0x0000555557660271 in Trinity::Assert (file=<optimized out>, line=line@entry=47, function=<optimized out>, debugInfo="", message=<optimized out>, format=<optimized out>) at /root/dekkcoreshadowlandsnew/src/common/Debugging/Errors.cpp:92
#1  0x000055555756a8e5 in BaseDatabaseResultValueConverter::LogTruncation (getter=0x555557a4e3d3 "Field::GetUInt32", meta=0x7ffe3ec09300) at /root/dekkcoreshadowlandsnew/src/server/database/Database/FieldValueConverter.cpp:46
#2  0x000055555754a8c0 in PrimitiveResultValueConverter<char const*, std::void_t>::GetUInt32 (this=<optimized out>, meta=0x7ffe08cac880) at /root/dekkcoreshadowlandsnew/src/server/database/Database/FieldValueConverters.h:101
#3  0x0000555557012842 in BattlepayManager::SendAccountCredits (this=0x7ffd901d6210) at /root/dekkcoreshadowlandsnew/src/server/game/Fluxurion/BattlePay/BattlePayMgr.cpp:1211
#4  0x000055555736a250 in PacketHandler<WorldPackets::BattlePay::GetProductList, &WorldSession::HandleGetProductList>::Call (this=<optimized out>, session=0x7ffd900af800, packet=...) at /root/dekkcoreshadowlandsnew/src/server/game/Server/Protocol/Opcodes.cpp:35
#5  0x000055555729bb18 in WorldSession::Update (this=0x7ffd900af800, diff=1, updater=...) at /root/dekkcoreshadowlandsnew/src/server/game/Server/WorldSession.cpp:467
#6  0x000055555746dca4 in World::UpdateSessions (this=this@entry=0x555558678550 <World::instance()::instance>, diff=diff@entry=1) at /root/dekkcoreshadowlandsnew/src/server/game/World/World.cpp:3640
#7  0x000055555746b99f in World::Update (this=0x555558678550 <World::instance()::instance>, diff=1) at /root/dekkcoreshadowlandsnew/src/server/game/World/World.cpp:2849
#8  0x00005555561d47c0 in WorldUpdateLoop () at /root/dekkcoreshadowlandsnew/src/server/worldserver/Main.cpp:531
#9  0x00005555561d254f in main (argc=<optimized out>, argv=<optimized out>) at /root/dekkcoreshadowlandsnew/src/server/worldserver/Main.cpp:407

**Comment by NesinAlex** [comment]
last update NOW

**Comment by Thordekk** [comment]
i upload a fix soon for al fieldvalues
