### ISSUE TITLE
spell=6201/create-healthstone gives stone with 0 charges

### ISSUE THREAD

**Issue by NesinAlex** [Thordekk/Dekk-Core-Donator-Bugtracker#607]
[spell=6201/create-healthstone](https://www.wowhead.com/spell=6201/create-healthstone)
item id = 5512

![image](https://github.com/Thordekk/Dekk-Core-Donator-Bugtracker/assets/42183646/7178c7c3-6272-473e-8a4f-8fceeed420f6)

**Comment by NesinAlex** [comment]
visual bug.
stone work but shows 0 (no charges)
cache deleted
Works 3 times as expected

**Comment by Thordekk** [comment]
Is working
