### ISSUE TITLE
spell=186257/aspect-of-the-cheetah buffs for 2 hours

### ISSUE THREAD

**Issue by NesinAlex** [Thordekk/Dekk-Core-Donator-Bugtracker#608]
must 9 sec
https://www.wowhead.com/spell=186257/aspect-of-the-cheetah
![image](https://github.com/Thordekk/Dekk-Core-Donator-Bugtracker/assets/42183646/74c75ad1-38ff-47a8-85d3-0803a6860f7c)

**Comment by Thordekk** [comment]
Disable zolocraft
