### ISSUE TITLE
quest=1468/childrens-week two npc in one

### ISSUE THREAD

**Issue by NesinAlex** [Thordekk/Dekk-Core-Donator-Bugtracker#610]
NPC 51988, 14450. In Stormwind, two almost identical npcs in one place. One gives the [quest "Children's Week"](https://www.wowhead.com/quest=1468/childrens-week), the second does not.
![image](https://github.com/Thordekk/Dekk-Core-Donator-Bugtracker/assets/42183646/e89daaf1-dccb-411e-a08e-458e01a6c789)

**Comment by ahoffman1** [comment]
fixed
