### ISSUE TITLE
pack of Dracthyr npcs nightmare the city

### ISSUE THREAD

**Issue by NesinAlex** [Thordekk/Dekk-Core-Donator-Bugtracker#612]
NPCs: 198551, 198533, 198526, 198531, 198506, 198505, 201312, 192529, 198482. They are hostile to the player and attack guards in Stormwind. Characters: Void Elf, Mechagnome, Pandaren
![image](https://github.com/Thordekk/Dekk-Core-Donator-Bugtracker/assets/42183646/550a1579-9607-46cf-8b0a-9bd6dc661d4f)

**Comment by Thordekk** [comment]
Fixed
