### ISSUE TITLE
spell=43265/death-and-decay doesn't hit additional targets

### ISSUE THREAD

**Issue by NesinAlex** [Thordekk/Dekk-Core-Donator-Bugtracker#616]
https://www.wowhead.com/spell=43265/death-and-decay

Must hit up to 7 enemies.

![image](https://github.com/Thordekk/Dekk-Core-Donator-Bugtracker/assets/42183646/d94c6755-c0a9-4e33-95e0-d8139d859392)

**Comment by Thordekk** [comment]
https://gyazo.com/d38ac635e72a0156635620858e282c5a
