### ISSUE TITLE
spell=136/mend-pet mechagnome missing spell

### ISSUE THREAD

**Issue by NesinAlex** [Thordekk/Dekk-Core-Donator-Bugtracker#618]
https://www.wowhead.com/spell=136/mend-pet

Mechagnome Hunt does not have a spell to heal a pet. I spied ID on a night elf, because a mechagnome doesn’t even have future spells

![image](https://github.com/Thordekk/Dekk-Core-Donator-Bugtracker/assets/42183646/a7459796-394c-4a14-9aaf-3c573386ba8b)

**Comment by Thordekk** [comment]
added
