### ISSUE TITLE
[BfA] [Quest] 49468 "Required Webinar"

### ISSUE THREAD

**Issue by Ursonne** [Thordekk/Dekk-Core-Donator-Bugtracker#62]
https://www.wowhead.com/quest=49468/required-webinar

When you click NPC 134122 you don't freed the Lumberjack, it happens nothing. (No Trigger for Quest)
https://www.wowhead.com/npc=134122/webbed-lumberjack

And the https://www.wowhead.com/npc=129842 follow you when you attack them, but thats eggs without legs :O

**Comment by Thordekk** [comment]
Fixed
