### ISSUE TITLE
quest=62/the-fargodeep-mine doesn't end where it should

### ISSUE THREAD

**Issue by NesinAlex** [Thordekk/Dekk-Core-Donator-Bugtracker#622]
https://www.wowhead.com/quest=62/the-fargodeep-mine

the quest is not counted when entering the specified zone. On retail in this place, intelligence would have already been counted

![image](https://github.com/Thordekk/Dekk-Core-Donator-Bugtracker/assets/42183646/3e3d9245-43cd-406a-9bfe-f68d5478bb1c)

**Comment by Steyfix** [comment]
I confirm the concern that I had raised still have not fixed impossible to return it to the npc

**Comment by Thordekk** [comment]
Fixed
