### ISSUE TITLE
quest=60891/cataclysm-onward-to-adventure-in-the-eastern-kingdoms nowhere to complete

### ISSUE THREAD

**Issue by NesinAlex** [Thordekk/Dekk-Core-Donator-Bugtracker#624]
https://www.wowhead.com/quest=60891/cataclysm-onward-to-adventure-in-the-eastern-kingdoms

Quest 60891, given when you choose the time of the Cataclysm with Chromie. You need to turn in the quest board, but there is no way.
Abyss Elf, mage.

![image](https://github.com/Thordekk/Dekk-Core-Donator-Bugtracker/assets/42183646/690a857d-2ada-4a59-b913-d9d3b31dad8a)

**Comment by Thordekk** [comment]
Fixed u need talk to chromie near call board
