### ISSUE TITLE
npc=160737/combat-dummy cannot be killed

### ISSUE THREAD

**Issue by NesinAlex** [Thordekk/Dekk-Core-Donator-Bugtracker#629]
https://www.wowhead.com/npc=160737/combat-dummy

Y cant complete this quest because dummy heal themself too quick

![image](https://github.com/Thordekk/Dekk-Core-Donator-Bugtracker/assets/42183646/3eb73dd8-3d3e-4f43-8438-05aa17335836)

**Comment by Thordekk** [comment]
Fixed
