### ISSUE TITLE
DH moves above floor level and cannot go down.

### ISSUE THREAD

**Issue by NesinAlex** [Thordekk/Dekk-Core-Donator-Bugtracker#632]
Abilities have been used:
https://www.wowhead.com/spell=196055/double-jump
https://www.wowhead.com/spell=195072/fel-rush
https://www.wowhead.com/spell=131347/glide

**Comment by NesinAlex** [comment]
![image](https://github.com/Thordekk/Dekk-Core-Donator-Bugtracker/assets/42183646/19d17566-8233-4633-94d7-5a336311a18c)

**Comment by Thordekk** [comment]
use mmaps
