### ISSUE TITLE
Fire Mage Spell 12654

### ISSUE THREAD

**Issue by KKBa20** [Thordekk/Dekk-Core-Donator-Bugtracker#633]
The ignite fire mage spell does 0 damage to target. The spell ignite is meant to do 5.0% damage to target.

https://www.wowhead.com/spell=12654/ignite

![WoWScrnShot_052423_203254](https://github.com/Thordekk/Dekk-Core-Donator-Bugtracker/assets/129208594/92727014-6ed4-4c4a-b98b-0031fc1b80a2)

**Comment by ahoffman1** [comment]
fixed
