### ISSUE TITLE
[CRITICAL] zone=9028/ataldazar scripts Server Crash

### ISSUE THREAD

**Issue by NesinAlex** [Thordekk/Dekk-Core-Donator-Bugtracker#638]
VIDEO https://disk.yandex.ru/i/RS46yWnOuFKDUQ

BACKTRACE

#0  npc_ataldazar_soulspawn::npc_ataldazar_soulspawn (this=0x7ffd69e09000, pCreature=pCreature@entry=0x7ffd69e269c0) at /root/dekkcoreshadowlandsnew/src/server/scripts/DekkCore/BattleforAzeroth/AtalDazar/boss_yazma.cpp:215
#1  0x000055555625e72f in GenericCreatureScript<npc_ataldazar_soulspawn>::GetAI (this=<optimized out>, me=0x7ffd69e269c0) at /root/dekkcoreshadowlandsnew/src/server/game/Scripting/ScriptMgr.h:1566
#2  0x0000555557496729 in FactorySelector::SelectAI (creature=creature@entry=0x7ffd69e269c0) at /root/dekkcoreshadowlandsnew/src/server/game/AI/CreatureAISelector.cpp:92
#3  0x0000555556e5e714 in Creature::AIM_Create (this=this@entry=0x7ffd69e269c0, ai=ai@entry=0x0) at /root/dekkcoreshadowlandsnew/src/server/game/Entities/Creature/Creature.cpp:1033
#4  Creature::AIM_Initialize (this=this@entry=0x7ffd69e269c0, ai=ai@entry=0x0) at /root/dekkcoreshadowlandsnew/src/server/game/Entities/Creature/Creature.cpp:1040
#5  0x0000555556e5e587 in Creature::AddToWorld (this=0x7ffd69e269c0) at /root/dekkcoreshadowlandsnew/src/server/game/Entities/Creature/Creature.cpp:329
#6  0x00005555574dc9de in AddObjectHelper<Creature> (cell=..., m=..., count=@0x7ffff175ceac: 101, map=map@entry=0x7ffe09293100, obj=obj@entry=0x7ffd69e269c0) at /root/dekkcoreshadowlandsnew/src/server/game/Grids/ObjectGridLoader.cpp:96
#7  0x00005555574dc01a in LoadHelper<Creature> (guid_set=..., cell=..., m=..., count=@0x7ffff175caa8: 242, map=0x7ffe09293100, phaseId=phaseId@entry=0, phaseOwner=std::optional<ObjectGuid> [no contained value]) at /root/dekkcoreshadowlandsnew/src/server/game/Grids/ObjectGridLoader.cpp:127
#8  0x00005555574dccdf in ObjectGridLoader::Visit (this=0x7ffff175ce90, m=...) at /root/dekkcoreshadowlandsnew/src/server/game/Grids/ObjectGridLoader.cpp:142
#9  VisitorHelper<ObjectGridLoader, Creature> (v=..., c=...) at /root/dekkcoreshadowlandsnew/src/server/game/Grids/Dynamic/TypeContainerVisitor.h:43
#10 VisitorHelper<ObjectGridLoader, Creature, TypeList<DynamicObject, TypeList<Corpse, TypeList<AreaTrigger, TypeList<SceneObject, TypeList<Conversation, TypeNull> > > > > > (v=..., c=...) at /root/dekkcoreshadowlandsnew/src/server/game/Grids/Dynamic/TypeContainerVisitor.h:49
#11 0x00005555574dcc0f in VisitorHelper<ObjectGridLoader, GameObject, TypeList<Creature, TypeList<DynamicObject, TypeList<Corpse, TypeList<AreaTrigger, TypeList<SceneObject, TypeList<Conversation, TypeNull> > > > > > > (v=..., c=...) at /root/dekkcoreshadowlandsnew/src/server/game/Grids/Dynamic/TypeContainerVisitor.h:50
#12 0x00005555574db8db in VisitorHelper<ObjectGridLoader, TypeList<GameObject, TypeList<Creature, TypeList<DynamicObject, TypeList<Corpse, TypeList<AreaTrigger, TypeList<SceneObject, TypeList<Conversation, TypeNull> > > > > > > > (v=..., c=...) at /root/dekkcoreshadowlandsnew/src/server/game/Grids/Dynamic/TypeContainerVisitor.h:56
#13 TypeContainerVisitor<ObjectGridLoader, TypeMapContainer<TypeList<GameObject, TypeList<Creature, TypeList<DynamicObject, TypeList<Corpse, TypeList<AreaTrigger, TypeList<SceneObject, TypeList<Conversation, TypeNull> > > > > > > > >::Visit (this=<optimized out>, c=...) at /root/dekkcoreshadowlandsnew/src/server/game/Grids/Dynamic/TypeContainerVisitor.h:90
#14 Grid<Player, TypeList<Player, TypeList<Creature, TypeList<Corpse, TypeList<DynamicObject, TypeNull> > > >, TypeList<GameObject, TypeList<Creature, TypeList<DynamicObject, TypeList<Corpse, TypeList<AreaTrigger, TypeList<SceneObject, TypeList<Conversation, TypeNull> > > > > > > >::Visit<ObjectGridLoader> (this=<optimized out>, visitor=...) at /root/dekkcoreshadowlandsnew/src/server/game/Grids/Grid.h:90
#15 NGrid<8u, Player, TypeList<Player, TypeList<Creature, TypeList<Corpse, TypeList<DynamicObject, TypeNull> > > >, TypeList<GameObject, TypeList<Creature, TypeList<DynamicObject, TypeList<Corpse, TypeList<AreaTrigger, TypeList<SceneObject, TypeList<Conversation, TypeNull> > > > > > > >::VisitGrid<ObjectGridLoader, TypeList<GameObject, TypeList<Creature, TypeList<DynamicObject, TypeList<Corpse, TypeList<AreaTrigger, TypeList<SceneObject, TypeList<Conversation, TypeNull> > > > > > > > (this=<optimized out>, x=<optimized out>, y=<optimized out>, visitor=...) at /root/dekkcoreshadowlandsnew/src/server/game/Grids/NGrid.h:147
#16 ObjectGridLoader::LoadN (this=0x7ffff175ce90) at /root/dekkcoreshadowlandsnew/src/server/game/Grids/ObjectGridLoader.cpp:186
#17 0x00005555571cdfc3 in Map::LoadGridObjects (this=<optimized out>, grid=0x125, cell=...) at /root/dekkcoreshadowlandsnew/src/server/game/Maps/Map.cpp:408
#18 0x00005555571cdf22 in Map::EnsureGridLoaded (this=0x7ffe09293100, cell=...) at /root/dekkcoreshadowlandsnew/src/server/game/Maps/Map.cpp:396
#19 0x00005555570c7e0a in Map::Visit<Trinity::PlayerRelocationNotifier, TypeMapContainer<TypeList<Player, TypeList<Creature, TypeList<Corpse, TypeList<DynamicObject, TypeNull> > > > > > (this=this@entry=0x7ffe09293100, cell=..., visitor=...) at /root/dekkcoreshadowlandsnew/src/server/game/Maps/Map.h:924
#20 0x00005555570c7ffe in Cell::VisitCircle<Trinity::PlayerRelocationNotifier, TypeMapContainer<TypeList<Player, TypeList<Creature, TypeList<Corpse, TypeList<DynamicObject, TypeNull> > > > > > (this=this@entry=0x7ffff175d0e0, visitor=..., map=..., begin_cell=..., end_cell=...) at /root/dekkcoreshadowlandsnew/src/server/game/Grids/Cells/CellImpl.h:143
#21 0x00005555570c7c60 in Cell::Visit<Trinity::PlayerRelocationNotifier, TypeMapContainer<TypeList<Player, TypeList<Creature, TypeList<Corpse, TypeList<DynamicObject, TypeNull> > > > > > (this=<optimized out>, this@entry=0x7ffff175d0e0, standing_cell=..., visitor=..., map=..., x_off=x_off@entry=-848.299988, y_off=y_off@entry=2082.30005, radius=<optimized out>, radius@entry=533.333313) at /root/dekkcoreshadowlandsnew/src/server/game/Grids/Cells/CellImpl.h:101
#22 0x00005555570c651c in Cell::Visit<Trinity::PlayerRelocationNotifier, TypeMapContainer<TypeList<Player, TypeList<Creature, TypeList<Corpse, TypeList<DynamicObject, TypeNull> > > > > > (this=0x7ffff175d0e0, standing_cell=..., visitor=..., map=..., obj=..., radius=533.333313) at /root/dekkcoreshadowlandsnew/src/server/game/Grids/Cells/CellImpl.h:65
#23 Cell::VisitAllObjects<Trinity::PlayerRelocationNotifier> (center_obj=center_obj@entry=0x7ffe08c6c0c0, visitor=..., radius=533.333313, dont_load=<optimized out>) at /root/dekkcoreshadowlandsnew/src/server/game/Grids/Cells/CellImpl.h:211
#24 0x00005555570c5f69 in Trinity::DelayedUnitRelocation::Visit (this=0x7ffff175d358, m=...) at /root/dekkcoreshadowlandsnew/src/server/game/Grids/Notifiers/GridNotifiers.cpp:231
#25 0x00005555571e7535 in VisitorHelper<Trinity::DelayedUnitRelocation, Player> (v=..., c=...) at /root/dekkcoreshadowlandsnew/src/server/game/Grids/Dynamic/TypeContainerVisitor.h:43
#26 VisitorHelper<Trinity::DelayedUnitRelocation, Player, TypeList<Creature, TypeList<Corpse, TypeList<DynamicObject, TypeNull> > > > (v=..., c=...) at /root/dekkcoreshadowlandsnew/src/server/game/Grids/Dynamic/TypeContainerVisitor.h:49
#27 VisitorHelper<Trinity::DelayedUnitRelocation, TypeList<Player, TypeList<Creature, TypeList<Corpse, TypeList<DynamicObject, TypeNull> > > > > (v=..., c=...) at /root/dekkcoreshadowlandsnew/src/server/game/Grids/Dynamic/TypeContainerVisitor.h:56
#28 TypeContainerVisitor<Trinity::DelayedUnitRelocation, TypeMapContainer<TypeList<Player, TypeList<Creature, TypeList<Corpse, TypeList<DynamicObject, TypeNull> > > > > >::Visit (this=<optimized out>, c=...) at /root/dekkcoreshadowlandsnew/src/server/game/Grids/Dynamic/TypeContainerVisitor.h:90
#29 Grid<Player, TypeList<Player, TypeList<Creature, TypeList<Corpse, TypeList<DynamicObject, TypeNull> > > >, TypeList<GameObject, TypeList<Creature, TypeList<DynamicObject, TypeList<Corpse, TypeList<AreaTrigger, TypeList<SceneObject, TypeList<Conversation, TypeNull> > > > > > > >::Visit<Trinity::DelayedUnitRelocation> (this=<optimized out>, visitor=...) at /root/dekkcoreshadowlandsnew/src/server/game/Grids/Grid.h:97
#30 NGrid<8u, Player, TypeList<Player, TypeList<Creature, TypeList<Corpse, TypeList<DynamicObject, TypeNull> > > >, TypeList<GameObject, TypeList<Creature, TypeList<DynamicObject, TypeList<Corpse, TypeList<AreaTrigger, TypeList<SceneObject, TypeList<Conversation, TypeNull> > > > > > > >::VisitGrid<Trinity::DelayedUnitRelocation, TypeList<Player, TypeList<Creature, TypeList<Corpse, TypeList<DynamicObject, TypeNull> > > > > (this=<optimized out>, x=x@entry=288, y=y@entry=7, visitor=...) at /root/dekkcoreshadowlandsnew/src/server/game/Grids/NGrid.h:147
#31 0x00005555571d25b6 in Map::Visit<Trinity::DelayedUnitRelocation, TypeMapContainer<TypeList<Player, TypeList<Creature, TypeList<Corpse, TypeList<DynamicObject, TypeNull> > > > > > (this=0x7ffe09293100, cell=..., visitor=...) at /root/dekkcoreshadowlandsnew/src/server/game/Maps/Map.h:925
#32 Map::ProcessRelocationNotifies (this=this@entry=0x7ffe09293100, diff=diff@entry=10) at /root/dekkcoreshadowlandsnew/src/server/game/Maps/Map.cpp:881
#33 0x00005555571d0936 in Map::Update (this=0x7ffe09293100, t_diff=<optimized out>) at /root/dekkcoreshadowlandsnew/src/server/game/Maps/Map.cpp:822
#34 0x00005555571da2f2 in InstanceMap::Update (this=0x7ffdd52715b8, t_diff=293) at /root/dekkcoreshadowlandsnew/src/server/game/Maps/Map.cpp:2927
#35 0x00005555571f25a5 in MapUpdateRequest::call (this=0x7ffe14ad5e20) at /root/dekkcoreshadowlandsnew/src/server/game/Maps/MapUpdater.cpp:43
#36 0x00005555571f2147 in MapUpdater::WorkerThread (this=0x555558653060 <MapManager::instance()::instance+144>) at /root/dekkcoreshadowlandsnew/src/server/game/Maps/MapUpdater.cpp:119
#37 0x00007ffff70942b3 in ?? () from /lib/x86_64-linux-gnu/libstdc++.so.6
#38 0x00007ffff6d1db43 in start_thread (arg=<optimized out>) at ./nptl/pthread_create.c:442
#39 0x00007ffff6dafa00 in clone3 () at ../sysdeps/unix/sysv/linux/x86_64/clone3.S:81

**Comment by ahoffman1** [comment]
bfa dungeons are basically all broken, only the teleports were added so far

**Comment by ahoffman1** [comment]
fixed this crash
