### ISSUE TITLE
[CRITICAL] Server Crash Pet.cpp:523 NOT FIXED

### ISSUE THREAD

**Issue by NesinAlex** [Thordekk/Dekk-Core-Donator-Bugtracker#639]
point 2 : (241.573, -59.9615, 24.6786)
point 3 : (241.573, -59.9615, 24.6786)
GetCharmedGUID(): 0000000000000000
GetCharmerGUID(): 0000000000000000
No vehicle kit
m_Controlled size: 0
AIName:  ScriptName: npc_pet_dk_guardian WaypointPath: 0 SpawnId: 1
TempSummonType: 8 Summoner: Player-1-00000039Timer: 0
Owner: Player-1-00000039
PetType: 0 PetNumber: 52

Thread 16 "worldserver" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7ffff175f640 (LWP 658934)]
0x0000555557675c31 in Trinity::Assert (file=<optimized out>, line=line@entry=523, function=<optimized out>, debugInfo="MapID: 574 Map name: 'Крепость Утгард' X: 241.573 Y: -59.9615 Z: 24.6786 O: 3.12993\nPet-0-1-574-0-26125-0000000001 Entry 26125\nName: Pebblecruncher\nIsAIEnabled: true DeathState: 0 UnitMo"..., message=<optimized out>) at /root/dekkcoreshadowlandsnew/src/common/Debugging/Errors.cpp:78
78          Crash(formattedMessage.c_str());

BACKTRACE

#0  0x0000555557675c31 in Trinity::Assert (file=<optimized out>, line=line@entry=523, function=<optimized out>, debugInfo="MapID: 574 Map name: 'Крепость Утгард' X: 241.573 Y: -59.9615 Z: 24.6786 O: 3.12993\nPet-0-1-574-0-26125-0000000001 Entry 26125\nName: Pebblecruncher\nIsAIEnabled: true DeathState: 0 UnitMo"..., message=<optimized out>) at /root/dekkcoreshadowlandsnew/src/common/Debugging/Errors.cpp:78
#1  0x0000555556eed616 in Pet::SavePetToDB (this=0x7ffe09530c80, mode=<optimized out>) at /root/dekkcoreshadowlandsnew/src/server/game/Entities/Pet/Pet.cpp:523
#2  0x0000555556f0d438 in Player::RemovePet (this=0x7ffe08c6f840, pet=0x7ffe09530c80, mode=PET_SAVE_NOT_IN_SLOT, returnreagent=<optimized out>) at /root/dekkcoreshadowlandsnew/src/server/game/Entities/Player/Player.cpp:21643
#3  0x0000555556e7bcdf in TempSummon::UnSummon (this=0x7ffe09530c80, msTime=<optimized out>) at /root/dekkcoreshadowlandsnew/src/server/game/Entities/Creature/TemporarySummon.cpp:328
#4  0x0000555556fe2256 in Unit::RemoveAllControlled (this=this@entry=0x7ffe08c6f840) at /root/dekkcoreshadowlandsnew/src/server/game/Entities/Unit/Unit.cpp:6441
#5  0x0000555556fe791e in Unit::setDeathState (this=0x7ffe08c6f840, s=JUST_DIED) at /root/dekkcoreshadowlandsnew/src/server/game/Entities/Unit/Unit.cpp:8562
#6  0x0000555556f0d9ba in Player::setDeathState (this=0x7ffe08c6f840, s=JUST_DIED) at /root/dekkcoreshadowlandsnew/src/server/game/Entities/Player/Player.cpp:1328
#7  0x0000555556fcaa68 in Unit::Kill (attacker=<optimized out>, attacker@entry=0x7ffe094bfb40, victim=0x7ffd9319d350, durabilityLoss=8, skipSettingDeathState=false) at /root/dekkcoreshadowlandsnew/src/server/game/Entities/Unit/Unit.cpp:10978
#8  0x0000555556fc9457 in Unit::DealDamage (attacker=0x7ffe094bfb40, victim=0x7ffd9312b050, damage=<optimized out>, cleanDamage=0x7ffff175cc08, cleanDamage@entry=0x7ffff175cbf8, damagetype=damagetype@entry=SPELL_DIRECT_DAMAGE, damageSchoolMask=<optimized out>, spellProto=<optimized out>, durabilityLoss=true) at /root/dekkcoreshadowlandsnew/src/server/game/Entities/Unit/Unit.cpp:1007
#9  0x0000555556fcd538 in Unit::DealSpellDamage (this=0x7ffd9319d350, damageInfo=<optimized out>, durabilityLoss=<optimized out>) at /root/dekkcoreshadowlandsnew/src/server/game/Entities/Unit/Unit.cpp:1257
#10 0x00005555573aac41 in Spell::TargetInfo::DoDamageAndTriggers (this=0x7ffd93180c18, spell=0x7ffd9325e000) at /root/dekkcoreshadowlandsnew/src/server/game/Spells/Spell.cpp:2789
#11 0x00005555573b3c1c in Spell::DoProcessTargetContainer<std::vector<Spell::TargetInfo, std::allocator<Spell::TargetInfo> > > (this=<optimized out>, targetContainer=...) at /root/dekkcoreshadowlandsnew/src/server/game/Spells/Spell.cpp:3836
#12 Spell::handle_immediate (this=this@entry=0x7ffd9325e000) at /root/dekkcoreshadowlandsnew/src/server/game/Spells/Spell.cpp:3885
#13 0x00005555573b1b24 in Spell::_cast (this=0x7ffd9325e000, skipCheck=<optimized out>) at /root/dekkcoreshadowlandsnew/src/server/game/Spells/Spell.cpp:3740
#14 0x0000555556cd9fef in UnitAI::DoMeleeAttackIfReady (this=0x7ffdefb07000) at /root/dekkcoreshadowlandsnew/src/server/game/AI/CoreAI/UnitAI.cpp:77
#15 0x0000555556fe96dd in Unit::AIUpdateTick (this=0x7ffe094bfb40, diff=2467475536) at /root/dekkcoreshadowlandsnew/src/server/game/Entities/Unit/Unit.cpp:9466
#16 0x0000555556e6127d in Creature::Update (this=0x7ffe094bfb40, diff=10) at /root/dekkcoreshadowlandsnew/src/server/game/Entities/Creature/Creature.cpp:854
#17 0x00005555570c6949 in Trinity::ObjectUpdater::Visit<Creature> (this=0x7ffff175d460, m=...) at /root/dekkcoreshadowlandsnew/src/server/game/Grids/Notifiers/GridNotifiers.cpp:263
#18 0x00005555571e7262 in VisitorHelper<Trinity::ObjectUpdater, Creature> (v=..., c=...) at /root/dekkcoreshadowlandsnew/src/server/game/Grids/Dynamic/TypeContainerVisitor.h:43
#19 VisitorHelper<Trinity::ObjectUpdater, Creature, TypeList<DynamicObject, TypeList<Corpse, TypeList<AreaTrigger, TypeList<SceneObject, TypeList<Conversation, TypeNull> > > > > > (v=..., c=...) at /root/dekkcoreshadowlandsnew/src/server/game/Grids/Dynamic/TypeContainerVisitor.h:49
#20 VisitorHelper<Trinity::ObjectUpdater, GameObject, TypeList<Creature, TypeList<DynamicObject, TypeList<Corpse, TypeList<AreaTrigger, TypeList<SceneObject, TypeList<Conversation, TypeNull> > > > > > > (v=..., c=...) at /root/dekkcoreshadowlandsnew/src/server/game/Grids/Dynamic/TypeContainerVisitor.h:50
#21 VisitorHelper<Trinity::ObjectUpdater, TypeList<GameObject, TypeList<Creature, TypeList<DynamicObject, TypeList<Corpse, TypeList<AreaTrigger, TypeList<SceneObject, TypeList<Conversation, TypeNull> > > > > > > > (v=..., c=...) at /root/dekkcoreshadowlandsnew/src/server/game/Grids/Dynamic/TypeContainerVisitor.h:56
#22 TypeContainerVisitor<Trinity::ObjectUpdater, TypeMapContainer<TypeList<GameObject, TypeList<Creature, TypeList<DynamicObject, TypeList<Corpse, TypeList<AreaTrigger, TypeList<SceneObject, TypeList<Conversation, TypeNull> > > > > > > > >::Visit (this=<optimized out>, c=...) at /root/dekkcoreshadowlandsnew/src/server/game/Grids/Dynamic/TypeContainerVisitor.h:90
#23 Grid<Player, TypeList<Player, TypeList<Creature, TypeList<Corpse, TypeList<DynamicObject, TypeNull> > > >, TypeList<GameObject, TypeList<Creature, TypeList<DynamicObject, TypeList<Corpse, TypeList<AreaTrigger, TypeList<SceneObject, TypeList<Conversation, TypeNull> > > > > > > >::Visit<Trinity::ObjectUpdater> (this=<optimized out>, visitor=...) at /root/dekkcoreshadowlandsnew/src/server/game/Grids/Grid.h:90
#24 NGrid<8u, Player, TypeList<Player, TypeList<Creature, TypeList<Corpse, TypeList<DynamicObject, TypeNull> > > >, TypeList<GameObject, TypeList<Creature, TypeList<DynamicObject, TypeList<Corpse, TypeList<AreaTrigger, TypeList<SceneObject, TypeList<Conversation, TypeNull> > > > > > > >::VisitGrid<Trinity::ObjectUpdater, TypeList<GameObject, TypeList<Creature, TypeList<DynamicObject, TypeList<Corpse, TypeList<AreaTrigger, TypeList<SceneObject, TypeList<Conversation, TypeNull> > > > > > > > (this=<optimized out>, x=<optimized out>, y=y@entry=7, visitor=...) at /root/dekkcoreshadowlandsnew/src/server/game/Grids/NGrid.h:147
#25 0x00005555571d0037 in Map::Visit<Trinity::ObjectUpdater, TypeMapContainer<TypeList<GameObject, TypeList<Creature, TypeList<DynamicObject, TypeList<Corpse, TypeList<AreaTrigger, TypeList<SceneObject, TypeList<Conversation, TypeNull> > > > > > > > > (this=0x7ffe092c6e00, cell=..., visitor=...) at /root/dekkcoreshadowlandsnew/src/server/game/Maps/Map.h:925
#26 Map::VisitNearbyCellsOf (this=this@entry=0x7ffe092c6e00, obj=obj@entry=0x7ffe08c6f840, gridVisitor=..., worldVisitor=...) at /root/dekkcoreshadowlandsnew/src/server/game/Maps/Map.cpp:659
#27 0x00005555571d0475 in Map::Update (this=0x7ffe092c6e00, t_diff=10) at /root/dekkcoreshadowlandsnew/src/server/game/Maps/Map.cpp:727
#28 0x00005555571da5e2 in InstanceMap::Update (this=0x7ffd9319d350, t_diff=2467475536) at /root/dekkcoreshadowlandsnew/src/server/game/Maps/Map.cpp:2927
#29 0x00005555571f2895 in MapUpdateRequest::call (this=0x7ffdf5e7a140) at /root/dekkcoreshadowlandsnew/src/server/game/Maps/MapUpdater.cpp:43
#30 0x00005555571f2437 in MapUpdater::WorkerThread (this=0x555558653060 <MapManager::instance()::instance+144>) at /root/dekkcoreshadowlandsnew/src/server/game/Maps/MapUpdater.cpp:119
#31 0x00007ffff70942b3 in ?? () from /lib/x86_64-linux-gnu/libstdc++.so.6
#32 0x00007ffff6d1db43 in start_thread (arg=<optimized out>) at ./nptl/pthread_create.c:442
#33 0x00007ffff6dafa00 in clone3 () at ../sysdeps/unix/sysv/linux/x86_64/clone3.S:81

**Comment by NesinAlex** [comment]
Server Updated 10 min ago

**Comment by NesinAlex** [comment]
We can't find dependencies. Every time it crashes for a different reason than we thought.

**Comment by NesinAlex** [comment]
Here one player of my server capture try to die from mobs when pet is active
https://disk.yandex.ru/i/pWeTYD_jWKQAAA

**Comment by ahoffman1** [comment]
Does it happen when the pet dies?

**Comment by ahoffman1** [comment]
fixed
