### ISSUE TITLE
[CRITICAL] Server Crash BFA ShrineOfTheStorm

### ISSUE THREAD

**Issue by NesinAlex** [Thordekk/Dekk-Core-Donator-Bugtracker#641]
Spell::EffectTriggerSpell spell 197923 tried to trigger unknown spell 197707
EndEmpoweredSpell 1
EndEmpoweredSpell 1
EndEmpoweredSpell 1
EndEmpoweredSpell 1
EndEmpoweredSpell 1
EndEmpoweredSpell 1
EndEmpoweredSpell 1
EndEmpoweredSpell 1
EndEmpoweredSpell 1
EndEmpoweredSpell 1
EndEmpoweredSpell 1
EndEmpoweredSpell 1
EndEmpoweredSpell 1
EndEmpoweredSpell 1

Thread 16 "worldserver" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7ffff175f640 (LWP 680187)]
0x00005555562ae4e0 in npc_rexxar::MoveInLineOfSight (this=0x7ffdeb7d6b40, unit=<optimized out>) at /root/dekkcoreshadowlandsnew/src/server/scripts/DekkCore/BattleforAzeroth/ShrineOfTheStorm/shrine_of_the_storm.cpp:54
54                  if (player->IsInDist(me, 8.0f) && instance && !instance->GetData(DATA_INSTANCE_ENTER))

BACKTRACE

#0  0x00005555562ae4e0 in npc_rexxar::MoveInLineOfSight (this=0x7ffdeb7d6b40, unit=<optimized out>) at /root/dekkcoreshadowlandsnew/src/server/scripts/DekkCore/BattleforAzeroth/ShrineOfTheStorm/shrine_of_the_storm.cpp:54
#1  0x0000555556cd3ecf in CreatureAI::MoveInLineOfSight_Safe (this=0x7ffdd2282280, who=0x4) at /root/dekkcoreshadowlandsnew/src/server/game/AI/CreatureAI.cpp:116
#2  0x00005555570c978e in Trinity::PlayerRelocationNotifier::Visit (this=0x7ffff175d148, m=...) at /root/dekkcoreshadowlandsnew/src/server/game/Grids/Notifiers/GridNotifiers.cpp:167
#3  VisitorHelper<Trinity::PlayerRelocationNotifier, Creature> (v=..., c=...) at /root/dekkcoreshadowlandsnew/src/server/game/Grids/Dynamic/TypeContainerVisitor.h:43
#4  VisitorHelper<Trinity::PlayerRelocationNotifier, Creature, TypeList<DynamicObject, TypeList<Corpse, TypeList<AreaTrigger, TypeList<SceneObject, TypeList<Conversation, TypeNull> > > > > > (v=..., c=...) at /root/dekkcoreshadowlandsnew/src/server/game/Grids/Dynamic/TypeContainerVisitor.h:49
#5  0x00005555570c9319 in Map::Visit<Trinity::PlayerRelocationNotifier, TypeMapContainer<TypeList<GameObject, TypeList<Creature, TypeList<DynamicObject, TypeList<Corpse, TypeList<AreaTrigger, TypeList<SceneObject, TypeList<Conversation, TypeNull> > > > > > > > > (this=0x7ffe08c293c0, cell=..., visitor=...) at /root/dekkcoreshadowlandsnew/src/server/game/Maps/Map.h:925
#6  Cell::VisitCircle<Trinity::PlayerRelocationNotifier, TypeMapContainer<TypeList<GameObject, TypeList<Creature, TypeList<DynamicObject, TypeList<Corpse, TypeList<AreaTrigger, TypeList<SceneObject, TypeList<Conversation, TypeNull> > > > > > > > > (this=this@entry=0x7ffff175d0e0, visitor=..., map=..., begin_cell=..., end_cell=...) at /root/dekkcoreshadowlandsnew/src/server/game/Grids/Cells/CellImpl.h:143
#7  0x00005555570c8f89 in Cell::Visit<Trinity::PlayerRelocationNotifier, TypeMapContainer<TypeList<GameObject, TypeList<Creature, TypeList<DynamicObject, TypeList<Corpse, TypeList<AreaTrigger, TypeList<SceneObject, TypeList<Conversation, TypeNull> > > > > > > > > (this=<optimized out>, this@entry=0x7ffff175d0e0, standing_cell=..., visitor=..., map=..., x_off=x_off@entry=4167.76758, y_off=y_off@entry=-1258.28125, radius=<optimized out>) at /root/dekkcoreshadowlandsnew/src/server/game/Grids/Cells/CellImpl.h:101
#8  0x00005555570c6e46 in Cell::Visit<Trinity::PlayerRelocationNotifier, TypeMapContainer<TypeList<GameObject, TypeList<Creature, TypeList<DynamicObject, TypeList<Corpse, TypeList<AreaTrigger, TypeList<SceneObject, TypeList<Conversation, TypeNull> > > > > > > > > (this=0x7ffff175d0e0, standing_cell=..., visitor=..., map=..., obj=..., radius=533.333313) at /root/dekkcoreshadowlandsnew/src/server/game/Grids/Cells/CellImpl.h:65
#9  Cell::VisitAllObjects<Trinity::PlayerRelocationNotifier> (center_obj=center_obj@entry=0x7ffe08c0d280, visitor=..., radius=533.333313, dont_load=<optimized out>) at /root/dekkcoreshadowlandsnew/src/server/game/Grids/Cells/CellImpl.h:213
#10 0x00005555570c6829 in Trinity::DelayedUnitRelocation::Visit (this=0x7ffff175d358, m=...) at /root/dekkcoreshadowlandsnew/src/server/game/Grids/Notifiers/GridNotifiers.cpp:231
#11 0x00005555571e8315 in VisitorHelper<Trinity::DelayedUnitRelocation, Player> (v=..., c=...) at /root/dekkcoreshadowlandsnew/src/server/game/Grids/Dynamic/TypeContainerVisitor.h:43
#12 VisitorHelper<Trinity::DelayedUnitRelocation, Player, TypeList<Creature, TypeList<Corpse, TypeList<DynamicObject, TypeNull> > > > (v=..., c=...) at /root/dekkcoreshadowlandsnew/src/server/game/Grids/Dynamic/TypeContainerVisitor.h:49
#13 VisitorHelper<Trinity::DelayedUnitRelocation, TypeList<Player, TypeList<Creature, TypeList<Corpse, TypeList<DynamicObject, TypeNull> > > > > (v=..., c=...) at /root/dekkcoreshadowlandsnew/src/server/game/Grids/Dynamic/TypeContainerVisitor.h:56
#14 TypeContainerVisitor<Trinity::DelayedUnitRelocation, TypeMapContainer<TypeList<Player, TypeList<Creature, TypeList<Corpse, TypeList<DynamicObject, TypeNull> > > > > >::Visit (this=<optimized out>, c=...) at /root/dekkcoreshadowlandsnew/src/server/game/Grids/Dynamic/TypeContainerVisitor.h:90
#15 Grid<Player, TypeList<Player, TypeList<Creature, TypeList<Corpse, TypeList<DynamicObject, TypeNull> > > >, TypeList<GameObject, TypeList<Creature, TypeList<DynamicObject, TypeList<Corpse, TypeList<AreaTrigger, TypeList<SceneObject, TypeList<Conversation, TypeNull> > > > > > > >::Visit<Trinity::DelayedUnitRelocation> (this=<optimized out>, visitor=...) at /root/dekkcoreshadowlandsnew/src/server/game/Grids/Grid.h:97
#16 NGrid<8u, Player, TypeList<Player, TypeList<Creature, TypeList<Corpse, TypeList<DynamicObject, TypeNull> > > >, TypeList<GameObject, TypeList<Creature, TypeList<DynamicObject, TypeList<Corpse, TypeList<AreaTrigger, TypeList<SceneObject, TypeList<Conversation, TypeNull> > > > > > > >::VisitGrid<Trinity::DelayedUnitRelocation, TypeList<Player, TypeList<Creature, TypeList<Corpse, TypeList<DynamicObject, TypeNull> > > > > (this=<optimized out>, x=x@entry=240, y=y@entry=5, visitor=...) at /root/dekkcoreshadowlandsnew/src/server/game/Grids/NGrid.h:147
#17 0x00005555571d3396 in Map::Visit<Trinity::DelayedUnitRelocation, TypeMapContainer<TypeList<Player, TypeList<Creature, TypeList<Corpse, TypeList<DynamicObject, TypeNull> > > > > > (this=0x7ffe08c293c0, cell=..., visitor=...) at /root/dekkcoreshadowlandsnew/src/server/game/Maps/Map.h:925
#18 Map::ProcessRelocationNotifies (this=this@entry=0x7ffe08c293c0, diff=diff@entry=10) at /root/dekkcoreshadowlandsnew/src/server/game/Maps/Map.cpp:881
#19 0x00005555571d1716 in Map::Update (this=0x7ffe08c293c0, t_diff=<optimized out>) at /root/dekkcoreshadowlandsnew/src/server/game/Maps/Map.cpp:822
#20 0x00005555571db0d2 in InstanceMap::Update (this=0x7ffdd2282280, t_diff=4) at /root/dekkcoreshadowlandsnew/src/server/game/Maps/Map.cpp:2927
#21 0x00005555571f3385 in MapUpdateRequest::call (this=0x7ffdf89028c0) at /root/dekkcoreshadowlandsnew/src/server/game/Maps/MapUpdater.cpp:43
#22 0x00005555571f2f27 in MapUpdater::WorkerThread (this=0x555558655060 <MapManager::instance()::instance+144>) at /root/dekkcoreshadowlandsnew/src/server/game/Maps/MapUpdater.cpp:119
#23 0x00007ffff70942b3 in ?? () from /lib/x86_64-linux-gnu/libstdc++.so.6
#24 0x00007ffff6d1db43 in start_thread (arg=<optimized out>) at ./nptl/pthread_create.c:442
#25 0x00007ffff6dafa00 in clone3 () at ../sysdeps/unix/sysv/linux/x86_64/clone3.S:81

**Comment by ahoffman1** [comment]
fixed
