### ISSUE TITLE
pnj faction concern

### ISSUE THREAD

**Issue by Steyfix** [Thordekk/Dekk-Core-Donator-Bugtracker#645]
![WoWScrnShot_053023_223338](https://github.com/Thordekk/Dekk-Core-Donator-Bugtracker/assets/12504219/01e19501-3c11-4b28-a395-c14833dc30d1)

as you can see I have a pnj level faction concern because it is impossible to transmit the order to him thanks to the interaction.

pnj id: 198401

**Comment by Thordekk** [comment]
Fixed
