### ISSUE TITLE
[BfA] [Quest] [Worldserver Crash] 49233 "I'm a Druid, not a Priest"

### ISSUE THREAD

**Issue by Ursonne** [Thordekk/Dekk-Core-Donator-Bugtracker#65]
https://www.wowhead.com/quest=49233/im-a-druid-not-a-priest
https://www.wowhead.com/item=153350/repurposed-gilnean-staff

When you use the Questitem the worldserver crash and close

**Comment by Thordekk** [comment]
fixed
