### ISSUE TITLE
neltharus(dun)

### ISSUE THREAD

**Issue by Xdoses** [Thordekk/Dekk-Core-Donator-Bugtracker#665]
https://www.wowhead.com/zone=14011/neltharus

All monsters are "yellow(nuetruall)   No end boss gear loot.  no fun unless shit attacks yah

**Comment by Korsar1808** [comment]
no all npc right.Hav you Gm On?
<img width="234" alt="image" src="https://github.com/Thordekk/Dekk-Core-Donator-Bugtracker/assets/59765795/dc5420ae-34ab-42ae-9588-5a1a065aaa8e">
