### ISSUE TITLE
QuestID: 60545 - Shadowlands: A Chilling Summons

### ISSUE THREAD

**Issue by brownbr** [Thordekk/Dekk-Core-Donator-Bugtracker#7]
Cannot turn in quest, trigger relating to "Report to Highlord Bolivar Fordragon at the Frozen Throne" does not work. Scripts relating to Alliance and Horde leaders talking to each other does work.

A less important issue, Darion Mograine does not walk up to the teleporter pad with you. From what I remember he walks beside you chatting with you. Not necessary to the quest but verbosity is best!

**Comment by Thordekk** [comment]
Fixed
