### ISSUE TITLE
Outland - Nagrand 

### ISSUE THREAD

**Issue by KKBa20** [Thordekk/Dekk-Core-Donator-Bugtracker#701]
All npcs in nagrand are only level one and they don’t scale the level to your character’s level like it should do.

Also these orcs somehow have blue beam casted everywhere for no reason. 

![IMG_4483](https://github.com/Thordekk/Dekk-Core-Donator-Bugtracker/assets/129208594/5242fdf5-58fa-4d2b-9248-b0088ff86ef6)
![IMG_4484](https://github.com/Thordekk/Dekk-Core-Donator-Bugtracker/assets/129208594/7c9ad852-5ce0-44d2-a47c-3a3e5a0456c7)

**Comment by ahoffman1** [comment]
fixed
