### ISSUE TITLE
Can’t summon hunter’s pet when at a higher level

### ISSUE THREAD

**Issue by KKBa20** [Thordekk/Dekk-Core-Donator-Bugtracker#703]
As soon as my character reaches level 33 and over, I can no longer summon my pet. It says that the spell is not available to you.

![IMG_4486](https://github.com/Thordekk/Dekk-Core-Donator-Bugtracker/assets/129208594/79fce8f7-55f6-42de-b47c-e6bfc8282351)

**Comment by ahoffman1** [comment]
fixed, Lone Wolf talent was broken
