### ISSUE TITLE
[BfA] Mistfall Cleft 

### ISSUE THREAD

**Issue by Ursonne** [Thordekk/Dekk-Core-Donator-Bugtracker#74]
Many spawns have wrong level.
they have levels between 15-45, they should all adjust to playerlevel

![image](https://user-images.githubusercontent.com/34980984/163689468-dd809aef-2924-496e-a1bd-26310ca0e08d.png)
![image](https://user-images.githubusercontent.com/34980984/163689474-5e906d3d-8d40-492e-a95f-35a4ab8c819d.png)
![image](https://user-images.githubusercontent.com/34980984/163689482-eacdab31-7b07-4775-b4d9-35340f8fcaeb.png)
![image](https://user-images.githubusercontent.com/34980984/163689491-19e39bbb-10b4-4423-89e9-e179b8eec4cc.png)

**Comment by Thordekk** [comment]
wrong level scaling
