### ISSUE TITLE
[BfA] [Quest] 49720 "Free Bird"

### ISSUE THREAD

**Issue by Ursonne** [Thordekk/Dekk-Core-Donator-Bugtracker#77]
https://www.wowhead.com/quest=49720/free-bird

You can repeat open the Hawk Cage and always trigger for the quest (no Hawk in the Cage)

![image](https://user-images.githubusercontent.com/34980984/163690292-4488f0f0-041c-4f25-9fd8-10749d4c10c6.png)

**Comment by Thordekk** [comment]
Quest can be completed later we change flag to despawn on click
