### ISSUE TITLE
See if it would be possible to activate bag slots?

### ISSUE THREAD

**Issue by Steyfix** [Thordekk/Dekk-Core-Donator-Bugtracker#776]
![WoWScrnShot_062123_183234](https://github.com/Thordekk/Dekk-Core-Donator-Bugtracker/assets/12504219/ddf0be0b-8e27-4e3a-bf7a-c82e85366c1f)
Hello I would like to know if it would be possible to remove the plus which redirects the player to blizzard links to automatically validate for all players the 4 bag slots currently unusable see my screen thank you.

**Comment by Thordekk** [comment]
I check soon that link is added on client side
