### ISSUE TITLE
Bug objectif bonus 65994

### ISSUE THREAD

**Issue by Steyfix** [Thordekk/Dekk-Core-Donator-Bugtracker#777]
![WoWScrnShot_062123_185936](https://github.com/Thordekk/Dekk-Core-Donator-Bugtracker/assets/12504219/a8909a34-e9b4-467c-8038-8733301baded)
https://www.wowhead.com/fr/quest=65994/justice-djaradine
The objective does not give automatically when entering the zone and when I add it to myself and fill the progress bar to 100% and the quest does not give automatically either.

**Comment by Thordekk** [comment]
Fixed
