### ISSUE TITLE
spell=3716/consuming-shadows - Warlock Pet

### ISSUE THREAD

**Issue by KKBa20** [Thordekk/Dekk-Core-Donator-Bugtracker#779]
Warlock, pet, void walker, does zero damage with its spell against enemies.

![WoWScrnShot_062323_185042](https://github.com/Thordekk/Dekk-Core-Donator-Bugtracker/assets/129208594/1d2e9000-0db2-4c95-a2c6-280af8dc25d4)

https://www.wowhead.com/spell=3716/consuming-shadows

**Comment by fluxurion** [comment]
Core/Pet: Fix warlock pet spellpower calculation
Core/Pet: Warlock pets now use Energy instead of Mana

https://github.com/Thordekk/Dekk-Core-Donator-Bugtracker/assets/25673748/c802144e-99ba-484c-995f-154df130a7a3
