### ISSUE TITLE
Imp doesn't attack - Warlock Pet

### ISSUE THREAD

**Issue by KKBa20** [Thordekk/Dekk-Core-Donator-Bugtracker#780]
When your character first obtains the imp, it works just fine. But when your character reaches higher, level 9 and over, the imp doesn't attack or move at its enemy.

https://github.com/Thordekk/Dekk-Core-Donator-Bugtracker/assets/129208594/54a37904-2670-4b8e-9d9b-72ce63e70190

**Comment by Thordekk** [comment]
https://gyazo.com/e25c9d89eabcece72df8d153674a780d
Idk what happened but is working now wild imps attack target fine
