### ISSUE TITLE
spell=104316/call-dreadstalkers - Warlock

### ISSUE THREAD

**Issue by KKBa20** [Thordekk/Dekk-Core-Donator-Bugtracker#781]
The spell only spawns one dreadstalker, instead of two. I think the dreadstalker doesn't attack enemies either.

![WoWScrnShot_062323_185505](https://github.com/Thordekk/Dekk-Core-Donator-Bugtracker/assets/129208594/36143bd4-95f5-4e46-be22-cac09ba7c859)

https://github.com/Thordekk/Dekk-Core-Donator-Bugtracker/assets/129208594/ebae7715-1dc8-42aa-a289-12d24877b4d8

https://www.wowhead.com/spell=104316/call-dreadstalkers

**Comment by Thordekk** [comment]
Fixed call 2 on same position but work as intendeed
