### ISSUE TITLE
Frost mage spell - 84714

### ISSUE THREAD

**Issue by KKBa20** [Thordekk/Dekk-Core-Donator-Bugtracker#786]
The frozen orb launches back and forth and doesn't deal any damage to targets.

https://www.wowhead.com/spell=84714/frozen-orb

https://github.com/Thordekk/Dekk-Core-Donator-Bugtracker/assets/129208594/7aaa0807-3b16-47ca-8398-d33aa8ec1a7a

**Comment by Thordekk** [comment]
Fixed https://gyazo.com/90893436968a5e65d26e01a240aff4bb
