### ISSUE TITLE
bug quest 66577 The Aspect Invitation

### ISSUE THREAD

**Issue by Steyfix** [Thordekk/Dekk-Core-Donator-Bugtracker#788]
hello as you can see on the screen I take the quest but I can't do anything else the quest does not validate with the gossip.

I'm level 12 esque it's a problem with my level because it seems to me that this quest should only appear at level 60 right?
![WoWScrnShot_062923_211154](https://github.com/Thordekk/Dekk-Core-Donator-Bugtracker/assets/12504219/0d563ee7-2c93-4a87-965e-df3d89502e9a)

**Comment by Thordekk** [comment]
Quest work on gossip select maybe is level yes

**Comment by Steyfix** [comment]
it would be possible to pass the quest available only at level 60 to avoid worries please? and the quest just before too
