### ISSUE TITLE
fix gossip fly pnj 42426

### ISSUE THREAD

**Issue by Steyfix** [Thordekk/Dekk-Core-Donator-Bugtracker#789]
As we see on the screen the npc does not provide the fly.
![WoWScrnShot_070123_175041](https://github.com/Thordekk/Dekk-Core-Donator-Bugtracker/assets/12504219/df2fa867-ad2b-427a-ad9e-e94fbea6f404)

**Comment by Thordekk** [comment]
missing npc flag
