### ISSUE TITLE
Concern for damage in the quest area 54933

### ISSUE THREAD

**Issue by Steyfix** [Thordekk/Dekk-Core-Donator-Bugtracker#794]
I go to take the quest https://www.wowhead.com/fr/quest=54933/lib%C3%A9rer-la-lumi%C3%A8re and I get attacked by an invisible mob that even in gm mode impossible to see the screen of my quest log.
![WoWScrnShot_070223_134110](https://github.com/Thordekk/Dekk-Core-Donator-Bugtracker/assets/12504219/479b24b2-318c-4e6e-bc86-ce98b2a4d454)

**Comment by Thordekk** [comment]
do .npc near
