### ISSUE TITLE
can´t complete: https://www.wowhead.com/quest=59938/down-with-the-quilboar

### ISSUE THREAD

**Issue by Primalclaw** [Thordekk/Dekk-Core-Donator-Bugtracker#796]
can´t complete:
![image](https://github.com/Thordekk/Dekk-Core-Donator-Bugtracker/assets/138524098/b9963f04-71fd-486a-9705-a2825d6dabfc)
![image](https://github.com/Thordekk/Dekk-Core-Donator-Bugtracker/assets/138524098/a5f322bc-bc67-4515-a61b-c607bff298c3)

**Comment by Korsar1808** [comment]
<img width="265" alt="image" src="https://github.com/Thordekk/Dekk-Core-Donator-Bugtracker/assets/59765795/3a50056b-f2d7-4197-b90d-1c76f3139585">
no issu found in horde
