### ISSUE TITLE
https://www.wowhead.com/es/quest=66000/biblioteca-de-alexstrasza

### ISSUE THREAD

**Issue by Primalclaw** [Thordekk/Dekk-Core-Donator-Bugtracker#803]
Hay un problema y es este:
![image](https://github.com/Thordekk/Dekk-Core-Donator-Bugtracker/assets/138524098/314aa69b-bdb9-407a-8bea-e48f7946300d)
La tengo completada pero no me deja seguir.

**Comment by Thordekk** [comment]
Fixed
