### ISSUE TITLE
Rogue Stealth issues

### ISSUE THREAD

**Issue by Tyrallis** [Thordekk/Dekk-Core-Donator-Bugtracker#804]
Rogues [Stealth](https://www.wowhead.com/spell=1784/stealth) [1784] does not allow me to cast [Cheap  Shot](https://www.wowhead.com/spell=1833/cheap-shot) [1833] and [Ambush](https://www.wowhead.com/spell=8676/ambush) [8676].
Relogging doesn't fix it
![image](https://github.com/Thordekk/Dekk-Core-Donator-Bugtracker/assets/94403538/dcc40ea4-eb42-47dd-bd86-b9c1b86d65ce)

**Comment by Thordekk** [comment]
Fixed
