### ISSUE TITLE
Drachtyr ability not working as inteded & Quest

### ISSUE THREAD

**Issue by ipro4911** [Thordekk/Dekk-Core-Donator-Bugtracker#809]
Fire Breath ability http://www.wowgold.hk/evoker-fire-breath/ doesnt do any damage even when charged up to lvl 1,2,3 and when doesnt hold until level 3 of charge as it does animation and the fire infuser doesnt actually reset ur ability cooldown 
![image](https://github.com/Thordekk/Dekk-Core-Donator-Bugtracker/assets/105972244/77f1f298-3e70-43f7-9826-fba3aa05d05c)

![image](https://github.com/Thordekk/Dekk-Core-Donator-Bugtracker/assets/105972244/9adf8d95-040f-44cf-8a8e-79d2df2fd716)

Quest 64872 or fire within only checks when u used fire infuser but u dont get ability & and when try to use it it doesnt check when u used lvl 1 2 or 3 
![image](https://github.com/Thordekk/Dekk-Core-Donator-Bugtracker/assets/105972244/68139b82-fe60-44d1-9c64-b9cfb5d3abe7)

**Comment by ipro4911** [comment]
Also when trying to exit of soar mode with like fire breath it crashes server disconnecting anyone while its on cooldown 86 seconds

**Comment by Thordekk** [comment]
Being fixed
