### ISSUE TITLE
Chromie Quests are targeting Alliance Quest Lines

### ISSUE THREAD

**Issue by Hobart2967** [Thordekk/Dekk-Core-Donator-Bugtracker#82]
When trying to follow the Chromie questlines as Horde, you'll mostly get Alliance Quest lines.

This is valid for:

- Legion (Leads to Stormwind docks)
- Burning Crusade (Leads to Honor Hold)
- Wrath of the Lich King (Leads to Alliance Base in Howling Fjord / Borean Tundra)
- Mists of Pandaria (Ported to Horde base, but quest target is located in Alliance base)
- Cataclysm (Leads to Stormwind)

Working Quest Lines:
- (none known so far)

Quest Lines with partial Workaround:

- Warlords of Draenor (Questline itself is broken though, see #84)

With a high chance, this is also valid for the other extensions

The only extension that worked out partially, was *Warlords of Draenor*, there you have a workaround: The Questline itself is triggered for Horde, but the Portal of the Mage in the Basement of the Orgrimmars Portal Tower leads you to falling from a high distance into the Alliance Camp in Blasted lands.

Dying and logging out/in will work around getting away from there, following the rest of the quest line.

**Comment by Hobart2967** [comment]
// Update: Tested MoP, not working either

**Comment by Hobart2967** [comment]
// Update: Added Cataclysm and some more specific infos.

**Comment by Thordekk** [comment]
Being scripted all
