### ISSUE TITLE
No reward for completing the quest Preservation, Augmentation, or Devastation

### ISSUE THREAD

**Issue by Raidrogon** [Thordekk/Dekk-Core-Donator-Bugtracker#836]
When you turn in the quest https://www.wowhead.com/quest=65701/preservation-augmentation-or-devastation

You should be awarded with https://www.wowhead.com/item=191808/crimson-dracthyr-battlegear-leggings

In this case its just gives me:

![image](https://github.com/Thordekk/Dekk-Core-Donator-Bugtracker/assets/89360396/60864c97-d0a3-451d-9fc8-20f8dc335119)

**Comment by Thordekk** [comment]
Fixed
