### ISSUE TITLE
No buff for the quest Run! Dracthyr zone

### ISSUE THREAD

**Issue by Raidrogon** [Thordekk/Dekk-Core-Donator-Bugtracker#839]
During this chapter quest you will need to:

Retreat!
Outrun the Avatar of the Storm
Wrathion found and healed

Run to the first area indicated on your map to fulfill the requirement Outrun the Avatar of the Storm. You will need to go slightly off the path to hit the circle. Once you've done that, your goal will change to Wrathion Found.

![image](https://github.com/Thordekk/Dekk-Core-Donator-Bugtracker/assets/89360396/071d0ed6-5a1e-4134-b4f3-35c3bcb02755)

Run down the hill to Wrathion and use a quick [ Living Flame](https://www.wowhead.com/spell=361469/living-flame) to heal Wrathion. Turn in the quest to Wrathion.

**Comment by Raidrogon** [comment]
Also, when you run down the stairs a giant wind elemental should start chasing you down stairs. You need to glide down the stairs quickly, to retreat to safety.

**Comment by Thordekk** [comment]
being reworked entire zone
