### ISSUE TITLE
Aspectral Invitation quest bugged

### ISSUE THREAD

**Issue by Raidrogon** [Thordekk/Dekk-Core-Donator-Bugtracker#844]
Speak to Wrathion or Ebyssian.

[Wrathion](https://www.wowhead.com/user=Wrathion) said:
No one threw any fruit at you, did they? I am told that happens sometimes.

Wrathion and Ebyssian will fill you in on what happened in the Alliance or Horde Councils in regard to the Aspects' invitation to the Dragon Isles.

![image](https://github.com/Thordekk/Dekk-Core-Donator-Bugtracker/assets/89360396/0f2b39a9-a28e-42d9-88be-5bb5200d6ef4)

**Comment by Thordekk** [comment]
Work perfect now
