### ISSUE TITLE
After completing the previous quest no quest given automatically

### ISSUE THREAD

**Issue by Raidrogon** [Thordekk/Dekk-Core-Donator-Bugtracker#846]
After you have completed the previous quest [An Iconic, Draconic Look](https://www.wowhead.com/quest=65613/an-iconic-draconic-look) you should be given another quest named https://www.wowhead.com/quest=32674/i-believe-you-can-fly

![image](https://github.com/Thordekk/Dekk-Core-Donator-Bugtracker/assets/89360396/667ca676-fc20-4930-b34e-bf3d5a76b0c1)

**Comment by Thordekk** [comment]
Quest obsolete by blizzard removed
