### ISSUE TITLE
When the quest I Believe You Can Fly is accepted the other quest is not there

### ISSUE THREAD

**Issue by Raidrogon** [Thordekk/Dekk-Core-Donator-Bugtracker#847]
When you accept the quest https://www.wowhead.com/quest=32674/i-believe-you-can-fly
You need to talk to [Scalecommander Cindrethresh](https://www.wowhead.com/npc=184786/scalecommander-cindrethresh) which is not there.

![image](https://github.com/Thordekk/Dekk-Core-Donator-Bugtracker/assets/89360396/90302097-1c2e-4d3c-a1bb-73c11e9858ab)

**Comment by Thordekk** [comment]
quest removed by blizz https://www.wowhead.com/quest=32674/i-believe-you-can-fly
