### ISSUE TITLE
Can't complete The Dark Talons next to the npc

### ISSUE THREAD

**Issue by Raidrogon** [Thordekk/Dekk-Core-Donator-Bugtracker#848]
After you complete the previous quest  Expeditionary Coordination https://www.wowhead.com/quest=65443/expeditionary-coordination
You are given this quest called The Dark Talons which you need to complete [Orders delivered to Kodethi](https://www.wowhead.com/npc=198440/orders-delivered-to-kodethi)

When the quest is marked as complete and you talk to the npc you can talk to the npc to teleport you to the zepplin but the menu doesn't work:
![image](https://github.com/Thordekk/Dekk-Core-Donator-Bugtracker/assets/89360396/835ce24f-4555-4bcb-bff6-f01cfcd33a10)

**Comment by Thordekk** [comment]
Fixed
