### ISSUE TITLE
NPC Storm Huntress Suhrakka <Storm Vendor> is not there

### ISSUE THREAD

**Issue by Raidrogon** [Thordekk/Dekk-Core-Donator-Bugtracker#850]
When you have a quest to complete named Chasing Storms (https://www.wowhead.com/quest=69944/chasing-storms), the npc to complete the quest is not there.

![image](https://github.com/Thordekk/Dekk-Core-Donator-Bugtracker/assets/89360396/91a1ae07-8639-4e19-b36d-b3968f5f9696)

**Comment by Raidrogon** [comment]
https://www.wowhead.com/npc=195899/storm-huntress-suhrakka

**Comment by Thordekk** [comment]
Fixed
