### ISSUE TITLE
Zepplin doesn't arrive because it doesn't work or bugged

### ISSUE THREAD

**Issue by Raidrogon** [Thordekk/Dekk-Core-Donator-Bugtracker#851]
When you are on the quest https://www.wowhead.com/quest=65444/to-the-dragon-isles
You should see a time for arrival from the npc named Skarukaru with a bar on top telling you how much is left for the zepplin to arrive.

Video guide: https://www.youtube.com/watch?v=72_15TfZyAU

**Comment by Thordekk** [comment]
Fixed
