### ISSUE TITLE
Can't Learn Master Riding Skill from Trainer

### ISSUE THREAD

**Issue by Raidrogon** [Thordekk/Dekk-Core-Donator-Bugtracker#852]
Not able to learn Master Riding Skill even though I have it learned from the boost that GM provided.

![image](https://github.com/Thordekk/Dekk-Core-Donator-Bugtracker/assets/89360396/a1f5cf89-f14e-45c1-9f3b-3be0dd571510)

**Comment by Thordekk** [comment]
Dont exist any more on retail https://www.wowhead.com/es/npc=44919/maztha#english-comments
