### ISSUE TITLE
Dragon Basic spells that cause server crashes

### ISSUE THREAD

**Issue by Lion-Anderson** [Thordekk/Dekk-Core-Donator-Bugtracker#871]
*The key spell:370553 https://www.wowhead.com/spell=370553/tip-the-scales*
*This spell (370553) will cause the following spell crashes the server*
1.spell=396286 https://www.wowhead.com/spell=396286/upheaval
2.spell=382614 https://www.wowhead.com/spell=382614/dream-breath
3.spell=382731 https://www.wowhead.com/spell=382731/spiritbloom
4.spell=359073 https://www.wowhead.com/spell=359073/eternity-surge
5.spell=357208 https://www.wowhead.com/spell=357208/fire-breath
6.spell=370553 https://www.wowhead.com/spell=370553/tip-the-scales
*Even without using spell 370553, the following spells still crash the server 50% of the time*

**Comment by Thordekk** [comment]
Fixed now
