### ISSUE TITLE
Mage's two orb spells will crash the server

### ISSUE THREAD

**Issue by Lion-Anderson** [Thordekk/Dekk-Core-Donator-Bugtracker#885]
https://www.wowhead.com/spell=84714/frozen-orb
https://www.wowhead.com/spell=153626/arcane-orb
Has enough damage to destroy worldserver.exe

**Comment by Thordekk** [comment]
https://www.wowhead.com/spell=153626/arcane-orb fixed

**Comment by Thordekk** [comment]
fixed
