### ISSUE TITLE
Monk talents Brewmaster

### ISSUE THREAD

**Issue by KamiNoEnd** [Thordekk/Dekk-Core-Donator-Bugtracker#888]
Spirit of the Ox and Gift of the Ox do not spawn healing spheres 

Staggering Strikes do not reduce stagger 

Shuffle doesn't do anything

Special Delivery doesn't throw a keg when using your Brews

Celestial Flames doesn't proc

After death i lose my talents and need to relog

I'm only level 30, more will come if i find more, will comment on this same issue so please do not close it <3

**Comment by Thordekk** [comment]
Scripted most of them future reports add ids
