### ISSUE TITLE
Mobs are falling through the ground

### ISSUE THREAD

**Issue by hsimpson** [Thordekk/Dekk-Core-Donator-Bugtracker#89]
Most of the mobs instances and even outside are falling through the ground when attacking them.

**Comment by Thordekk** [comment]
u need to enable vmaps that is normal with vmaps disabled

**Comment by Thordekk** [comment]
u need to enable vmaps that is normal with vmaps disabled

**Comment by Thordekk** [comment]
u need to enable vmaps that is normal with vmaps disabled
