### ISSUE TITLE
Monk Spell

### ISSUE THREAD

**Issue by KamiNoEnd** [Thordekk/Dekk-Core-Donator-Bugtracker#891]
Expel Harm doesn't deal damage (10 percent of amount healed) when used

**Comment by KamiNoEnd** [comment]
Celestial Brew give 0 Absorption

**Comment by Thordekk** [comment]
Harm  need to script soon is a new spell

**Comment by fluxurion** [comment]
Fixed both


https://github.com/Thordekk/Dekk-Core-Donator-Bugtracker/assets/25673748/c6682e37-9e48-4073-8b03-83bd82b3c18e


https://github.com/Thordekk/Dekk-Core-Donator-Bugtracker/assets/25673748/5f063782-af3c-48a1-913e-3b3a77c43938
