### ISSUE TITLE
Dark Iron Dwarf Racial

### ISSUE THREAD

**Issue by KamiNoEnd** [Thordekk/Dekk-Core-Donator-Bugtracker#893]
Mole machine doesn't have any teleport to BRD

**Comment by Korsar1808** [comment]
Which are the ones at the start area?

**Comment by KamiNoEnd** [comment]
https://www.wowhead.com/spell=265225/mole-machine#comments

Those are the one i know, as by the one at the start area, i'm pretty sure it's script should be in by default, and i don't have this one in particulat

**Comment by KamiNoEnd** [comment]
Maybe the reason is because the Starting quest for the Dark Iron Dwarves are not implemented yet?

Aka See image
![image](https://github.com/Thordekk/Dekk-Core-Donator-Bugtracker/assets/49670986/8af30949-8af3-49bb-ae0a-b64323644beb)

**Comment by Korsar1808** [comment]
But they are and Transporter takes you to Stormwind

**Comment by Korsar1808** [comment]
<img width="338" alt="image" src="https://github.com/Thordekk/Dekk-Core-Donator-Bugtracker/assets/59765795/68bcb42d-9256-4762-806c-d7c8b4ddce6e">

**Comment by Korsar1808** [comment]
<img width="158" alt="image" src="https://github.com/Thordekk/Dekk-Core-Donator-Bugtracker/assets/59765795/07fc7eb4-d26d-4474-a909-3eae8fba8cd9">
