### ISSUE TITLE
Riding training

### ISSUE THREAD

**Issue by KamiNoEnd** [Thordekk/Dekk-Core-Donator-Bugtracker#894]
I'm trying to learn Riding on my Dark Iron Dwarf, I'm level 30 and when i hit the Train button, nothing happens, i'm being told it's learned automaticaly, and a GM even tried to make me learn it with commands, and it said already known, but i cannot fly and my mount speed is stuck at 60 %

**Comment by Thordekk** [comment]
Riding trainers are removed on retail
