### ISSUE TITLE
Deeb breath still no scripted to work move u foward

### ISSUE THREAD

**Issue by ipro4911** [Thordekk/Dekk-Core-Donator-Bugtracker#895]
https://www.wowhead.com/spell=358385/landslide
https://www.wowhead.com/spell=357210/deep-breath
Both still arent working scripted even after saying its fixed it needs script to work because animation stands still

**Comment by fluxurion** [comment]
Hi! There is some misunderstanding about evoker's deep breath. Maybe a mixup with dream breath. But no worries i just started to script deep breath too!

**Comment by fluxurion** [comment]
Fixed

https://github.com/Thordekk/Dekk-Core-Donator-Bugtracker/assets/25673748/b5d0fb99-6a48-4f70-ad83-9e34424bc929

**Comment by fluxurion** [comment]
Landslide too
