### ISSUE TITLE
Character Customization that needs unlocked & usable for repack

### ISSUE THREAD

**Issue by KKBa20** [Thordekk/Dekk-Core-Donator-Bugtracker#896]
1) Night Warrior Eyes, https://www.wowhead.com/spell=285907/blessing-of-the-night-warrior

2) Dark Ranger Skin & Eyes, https://www.wowhead.com/guide/dark-ranger-customizations-transmog-how-to-unlock, https://www.wowhead.com/achievement=15579/return-to-lordaeron

3) Draenei Man'nari Eredar Skins & Eyes, https://www.wowhead.com/achievement=18938/seeing-red-account

**Comment by Thordekk** [comment]
https://www.wowhead.com/achievement=13251/in-teldrassils-shadow u need this achievement

**Comment by fluxurion** [comment]
I'm Workin on it

**Comment by fluxurion** [comment]
Fixed
