### ISSUE TITLE
Mission https://www.wowhead.com/quest=64873/stretch-your-wings

### ISSUE THREAD

**Issue by Huichonix** [Thordekk/Dekk-Core-Donator-Bugtracker#897]
The item is there, but the item does not activate hence, no next step is working on the missing unable to complete it. 
![image](https://github.com/Thordekk/Dekk-Core-Donator-Bugtracker/assets/144864440/a7f770e1-7906-4e81-8768-315a28082f5d)

**Comment by Thordekk** [comment]
First step tal to dracthyr who give quest and he complete first step , second the rings are bug ure right we rewrite soon

**Comment by Korsar1808** [comment]
rewright second ring
