### ISSUE TITLE
QuestID: 59752 - A Fractured Blade

### ISSUE THREAD

**Issue by brownbr** [Thordekk/Dekk-Core-Donator-Bugtracker#9]
Cannot rally Knights of the Ebon Blade. I am able to activate the Knights, but then nothing happens.

**Comment by jamesc97** [comment]
If you mean swear loyalty to lich and rally knights of ebon blade this works now if ya mean starter area for dk in newest donator repack it works now

**Comment by jamesc97** [comment]
if ya mean one in maw i was told thier currently working on this and the other stuff in maw zone

**Comment by jamesc97** [comment]
think its fixed now

**Comment by Thordekk** [comment]
Fixed
