### ISSUE TITLE
Bug with this mission double Bear spawn

### ISSUE THREAD

**Issue by KeenVenQC** [Thordekk/Dekk-Core-Donator-Bugtracker#903]
Bug with this mission double Bear spawn : 

https://www.wowhead.com/quest=55879/ride-of-the-scientifically-enhanced-boar

![image](https://github.com/Thordekk/Dekk-Core-Donator-Bugtracker/assets/103703563/8d92d8fa-80a9-4e70-b376-0ceaf2cf029f)

and Hord character spawn 

![image](https://github.com/Thordekk/Dekk-Core-Donator-Bugtracker/assets/103703563/2d3c4c22-8940-4f3a-94d2-018624271499)

**Comment by Thordekk** [comment]
visual bugs we check later
