### ISSUE TITLE
Crash server with one quest : Right Beneath Their Eyes

### ISSUE THREAD

**Issue by KeenVenQC** [Thordekk/Dekk-Core-Donator-Bugtracker#908]
this is the world crash log :

[8b2d061b5dda_worldserver.exe_13-9_21-49-6.txt](https://github.com/Thordekk/Dekk-Core-Donator-Bugtracker/files/12611149/8b2d061b5dda_worldserver.exe_13-9_21-49-6.txt)

the quest is this quest and cant complete the quest :

https://www.wowhead.com/quest=55981/right-beneath-their-eyes

**Comment by KeenVenQC** [comment]
Crash Occur when you talk to this NPC and transform you again in Ogre but the NPC not supposed to give that option and when you did CRASH ;

![image](https://github.com/Thordekk/Dekk-Core-Donator-Bugtracker/assets/103703563/5b86a3fb-28f2-4404-b4ff-7b08e2a26ac4)

**Comment by Thordekk** [comment]
Fixed crash
