### ISSUE TITLE
Error on Darkhave in Shadowlands, Kills WoW

### ISSUE THREAD

**Issue by arcronis** [Thordekk/Dekk-Core-Donator-Bugtracker#91]
![Bildschirmfoto 2022-04-28 um 12 07 50](https://user-images.githubusercontent.com/8113180/165729855-71af8ad3-f5bc-4146-9666-aabcf8ebbf1f.png)

Got this error on Darkhaven in Shadowlands

**Comment by Thordekk** [comment]
Fixed
