### ISSUE TITLE
Quest Bug

### ISSUE THREAD

**Issue by KeenVenQC** [Thordekk/Dekk-Core-Donator-Bugtracker#913]
Quest Bug cant complete the quest and start the fight with him

Quest : https://www.wowhead.com/quest=58915/hjalmars-final-execution

![image](https://github.com/Thordekk/Dekk-Core-Donator-Bugtracker/assets/103703563/9221f524-65d1-4439-af58-bdd243e6d098)

**Comment by Thordekk** [comment]
Fixed
