### ISSUE TITLE
Quest crash server

### ISSUE THREAD

**Issue by KeenVenQC** [Thordekk/Dekk-Core-Donator-Bugtracker#914]
This quest still don't work and when you ask the NPC to transform you again even when is not supposed to it crash the server :

Quest : https://www.wowhead.com/quest=55981/right-beneath-their-eyes

![image](https://github.com/Thordekk/Dekk-Core-Donator-Bugtracker/assets/103703563/b55351b4-559c-49b8-bc39-0402e0b3c5b2)

![image](https://github.com/Thordekk/Dekk-Core-Donator-Bugtracker/assets/103703563/d1df9c3d-730e-4640-8462-81b2eedb47f2)

Crash LOG :

[a819201d928d_worldserver.exe_[14-9_22-52-16].txt](https://github.com/Thordekk/Dekk-Core-Donator-Bugtracker/files/12615098/a819201d928d_worldserver.exe_.14-9_22-52-16.txt)

**Comment by Thordekk** [comment]
fixed
