### ISSUE TITLE
Four Crash Spells Priest/Mage

### ISSUE THREAD

**Issue by Lion-Anderson** [Thordekk/Dekk-Core-Donator-Bugtracker#915]
https://www.wowhead.com/spell=110744/divine-star
https://www.wowhead.com/spell=122121/divine-star
https://www.wowhead.com/spell=153626/arcane-orb
https://www.wowhead.com/spell=84714/frozen-orb

**Comment by Thordekk** [comment]
https://gyazo.com/0fc6a9c31970e8f26100606753d1c54a

**Comment by Thordekk** [comment]
https://gyazo.com/3f96942690c586154fe9bc5ebd590f26

mage not crash anymore

**Comment by Thordekk** [comment]
https://gyazo.com/0ea590294d917fc971ed004a04380732 Fixed divine star

**Comment by Thordekk** [comment]
Fix all
