### ISSUE TITLE
Bug quest (Exile Reach)

### ISSUE THREAD

**Issue by KeenVenQC** [Thordekk/Dekk-Core-Donator-Bugtracker#916]
The NPC do nothing except sleeping haha quest name in the screen ( but you got hit by him )

Quest : https://www.wowhead.com/fr/quest=55990/contr%C3%B4ler-leurs-pierres

![image](https://github.com/Thordekk/Dekk-Core-Donator-Bugtracker/assets/103703563/dd27a216-40c6-4ec5-945a-98c8a0887751)

**Comment by KeenVenQC** [comment]
Can't complete the quest too even if you have the 3 stones

![image](https://github.com/Thordekk/Dekk-Core-Donator-Bugtracker/assets/103703563/eadae026-e8a1-4145-b5fa-15359c2b81e2)

**Comment by Thordekk** [comment]
working now
