### ISSUE TITLE
Old Dungeons Reminder

### ISSUE THREAD

**Issue by KKBa20** [Thordekk/Dekk-Core-Donator-Bugtracker#920]
Just a little reminder that these dungeons need worked on for level scaling, accessibility, boss crash fixes and maybe some scripting.

The Burning Crusade Dungeons -
Hellfire Ramparts - https://www.wowhead.com/tbc/zone=3562/hellfire-ramparts
The Blood Furnace - https://www.wowhead.com/tbc/zone=3713/the-blood-furnace
The Slave Pens - https://www.wowhead.com/tbc/zone=3713/the-blood-furnace
The Underbog - https://www.wowhead.com/tbc/zone=3716/the-underbog
Mana-Tombs - https://www.wowhead.com/tbc/zone=3792/mana-tombs
Auchenai Crypts - https://www.wowhead.com/tbc/zone=3790/auchenai-crypts
Old Hillsbrad Foothills - https://www.wowhead.com/tbc/zone=2367/old-hillsbrad-foothills
Sethekk Halls - https://www.wowhead.com/tbc/zone=3791/sethekk-halls
The Steamvault - https://www.wowhead.com/tbc/zone=3715/the-steamvault
Shadow Labyrinth - https://www.wowhead.com/tbc/zone=3789/shadow-labyrinth
The Shattered Halls - https://www.wowhead.com/tbc/zone=3714/the-shattered-halls
The Black Morass - https://www.wowhead.com/tbc/zone=2366/the-black-morass
The Botanica - https://www.wowhead.com/tbc/zone=3847/the-botanica
The Mechanar - https://www.wowhead.com/tbc/zone=3849/the-mechanar
The Arcatraz - https://www.wowhead.com/tbc/zone=3848/the-arcatraz
Magisters' Terrace - https://www.wowhead.com/tbc/zone=4131/magisters-terrace

Wrath Of The Lich King Dungeons -
Utgarde Keep - https://www.wowhead.com/wotlk/zone=206/utgarde-keep
Azjol-Nerub - https://www.wowhead.com/wotlk/zone=4277/azjol-nerub
Ahn'kahet: The Old Kingdom - https://www.wowhead.com/wotlk/zone=4494/ahnkahet-the-old-kingdom
The Nexus - https://www.wowhead.com/wotlk/zone=4265/the-nexus
Drak'Tharon Keep - https://www.wowhead.com/wotlk/zone=4196/draktharon-keep
The Violet Hold - https://www.wowhead.com/wotlk/zone=4415/the-violet-hold
Gundrak - https://www.wowhead.com/wotlk/zone=4416/gundrak
Halls of Stone - https://www.wowhead.com/wotlk/zone=4264/halls-of-stone
Halls of Lightning - https://www.wowhead.com/wotlk/zone=4272/halls-of-lightning
The Oculus - https://www.wowhead.com/wotlk/zone=4228/the-oculus
Utgarde Pinnacle - https://www.wowhead.com/wotlk/zone=1196/utgarde-pinnacle
The Culling of Stratholme - https://www.wowhead.com/wotlk/zone=4100/the-culling-of-stratholme
Trial of the Champion - https://www.wowhead.com/wotlk/zone=4723/trial-of-the-champion
The Forge of Souls - https://www.wowhead.com/wotlk/zone=4809/the-forge-of-souls
Pit of Saron - https://www.wowhead.com/wotlk/zone=4813/pit-of-saron
Halls of Reflection - https://www.wowhead.com/wotlk/zone=4820/halls-of-reflection

Cataclysm Dungeons -
The Vortex Pinnacle - https://www.wowhead.com/zone=5035/the-vortex-pinnacle
Throne of the Tides - https://www.wowhead.com/zone=5004/throne-of-the-tides
Zul'Gurub - https://www.wowhead.com/zone=1977/zulgurub
Zul'Aman - https://www.wowhead.com/zone=3805/zulaman
Lost City of the Tol'vir - https://www.wowhead.com/zone=5396/lost-city-of-the-tolvir
The Stonecore - https://www.wowhead.com/zone=5088/the-stonecore
Grim Batol - https://www.wowhead.com/zone=4950/grim-batol
End Time - https://www.wowhead.com/zone=5789/end-time
Well of Eternity - https://www.wowhead.com/zone=5788/well-of-eternity
Blackrock Caverns - https://www.wowhead.com/zone=4926/blackrock-caverns
Halls of Origination - https://www.wowhead.com/zone=4945/halls-of-origination
Hour of Twilight - https://www.wowhead.com/zone=5844/hour-of-twilight

Mists Of Pandaria Dungeons -
Scholomance - https://www.wowhead.com/zone=6066/scholomance
Scarlet Halls - https://www.wowhead.com/zone=6052/scarlet-halls
Scarlet Monastery - https://www.wowhead.com/zone=6109/scarlet-monastery
Temple of the Jade Serpent - https://www.wowhead.com/zone=5956/temple-of-the-jade-serpent
Mogu'shan Palace - https://www.wowhead.com/zone=6182/mogushan-palace
Gate of the Setting Sun - https://www.wowhead.com/zone=5976/gate-of-the-setting-sun
Siege of Niuzao Temple - https://www.wowhead.com/zone=6214/siege-of-niuzao-temple
Shado-Pan Monastery - https://www.wowhead.com/zone=5918/shado-pan-monastery
Stormstout Brewery - https://www.wowhead.com/zone=5963/stormstout-brewery

Warlords Of Draenor Dungeons - 
Bloodmaul Slag Mines - https://www.wowhead.com/zone=6874/bloodmaul-slag-mines
Auchindoun - https://www.wowhead.com/zone=6912/auchindoun
The Everbloom - https://www.wowhead.com/zone=7109/the-everbloom
Grimrail Depot - https://www.wowhead.com/zone=6984/grimrail-depot
Iron Docks - https://www.wowhead.com/zone=6951/iron-docks
Shadowmoon Burial Grounds - https://www.wowhead.com/zone=6932/shadowmoon-burial-grounds
Skyreach - https://www.wowhead.com/zone=6988/skyreach
Upper Blackrock Spire - https://www.wowhead.com/zone=7307/upper-blackrock-spire

**Comment by Thordekk** [comment]
level scaling being added
