### ISSUE TITLE
Quest Bug ( DragonFlight )

### ISSUE THREAD

**Issue by KeenVenQC** [Thordekk/Dekk-Core-Donator-Bugtracker#922]
When a first character do the quest after i create a another dracthyr and i try to talk to Tethalash and heal him and nothing happen and the quest dont continue...

Quest : https://www.wowhead.com/fr/quest=64864/r%C3%A9veillez-vous-dracthyrs

![image](https://github.com/Thordekk/Dekk-Core-Donator-Bugtracker/assets/103703563/cd11d7c2-5dd7-4c1e-8c9f-1d499128ca71)

**Comment by KeenVenQC** [comment]
And when you create a new chracter dracthyr your not suppose to have this quest :

**Comment by KeenVenQC** [comment]
![image](https://github.com/Thordekk/Dekk-Core-Donator-Bugtracker/assets/103703563/e20ca606-3eb8-44e8-82e8-f5479617cfca)

**Comment by Korsar1808** [comment]
<img width="414" alt="image" src="https://github.com/Thordekk/Dekk-Core-Donator-Bugtracker/assets/59765795/e4c52596-022f-472a-9a4c-de3629352539">

**Comment by Korsar1808** [comment]
sorry but for me run the quest good
