### ISSUE TITLE
Bug Quest ( DragonFlight )

### ISSUE THREAD

**Issue by KeenVenQC** [Thordekk/Dekk-Core-Donator-Bugtracker#924]
When you have the quest for heal some dracthyr when you heal one is count as 2 and you can heal the same one for the 5 ask

Quest : https://www.wowhead.com/fr/quest=64866/d%C3%A9part-imminent

![image](https://github.com/Thordekk/Dekk-Core-Donator-Bugtracker/assets/103703563/3f76fc36-5bd6-49d2-98cf-f870b0b3b132)

**Comment by Thordekk** [comment]
need npc id

**Comment by Thordekk** [comment]
Fixed

**Comment by Thordekk** [comment]
UPDATE `world`.`creature` SET `spawntimesecs`=12 WHERE `id` =187133 ;
