### ISSUE TITLE
Dracthyr Dragonflight bug

### ISSUE THREAD

**Issue by KeenVenQC** [Thordekk/Dekk-Core-Donator-Bugtracker#928]
When you die in a instance like this quest you cant take back your character alive it say you have to penetrate in the instance and cant get back alive

Quest : https://www.wowhead.com/fr/quest=65046/les-primalistes

![image](https://github.com/Thordekk/Dekk-Core-Donator-Bugtracker/assets/103703563/7a19c6ea-41a4-43b5-9c1e-c74476a3d917)

**Comment by Thordekk** [comment]
On it
