### ISSUE TITLE
Quest bug ( BFA )

### ISSUE THREAD

**Issue by KeenVenQC** [Thordekk/Dekk-Core-Donator-Bugtracker#929]
When you have to talk to Jena you cant so you stock there and cant continue

Quest : https://www.wowhead.com/fr/quest=46728/la-nation-de-kul-tiras

![image](https://github.com/Thordekk/Dekk-Core-Donator-Bugtracker/assets/103703563/a9771a9d-6979-4f7d-b562-3ef266862cdc)

**Comment by Korsar1808** [comment]
you must speak with Jena at stormwind port
