### ISSUE TITLE
Quest & System Error

### ISSUE THREAD

**Issue by iroydphp** [Thordekk/Dekk-Core-Donator-Bugtracker#932]
**Quest Error 1** : There is a bug where held quests disappear when you end the game while the quest is on hold. You cannot give up or complete the quest.

**Quest Error 2** : When proceeding with the Obvious Successor quest [Speak with Bazentus], the NPC does not exist. Also, even if you forcefully create that NPC, you will not be able to talk to it. This quest is the main quest route of the Awakening Coast.

**Quest Error  3** : The Learn the 'Take to the Skies' Skill with Lithragosa quest does not work in [Dragon Glyphs and You].

**System Error 1** : Even if your reputation score increases, your reputation level does not increase.

 **System Error 2** : Guild System none
 
 **System Error 3** : If you change your race after creating your character as a Death Knight, the Adventure Guide feature will not work.

**Comment by Thordekk** [comment]
Almost isues are fixed, guild need clubfiner  not implemented yet but guild work
