### ISSUE TITLE
Silverspine quests so far

### ISSUE THREAD

**Issue by KKBa20** [Thordekk/Dekk-Core-Donator-Bugtracker#933]
Quests that need scripted, worked on and fixed.

https://www.wowhead.com/quest=26998/iterating-upon-success -- fixed
https://www.wowhead.com/quest=27039/dangerous-intentions -- fixed
https://www.wowhead.com/quest=27045/waiting-to-exsanguinate -- fixed
https://www.wowhead.com/quest=27069/steel-thunder -- fixed
https://www.wowhead.com/quest=27088/its-only-poisonous-if-you-ingest-it -- fixed
https://www.wowhead.com/quest=27099/no-escape -- fixed
https://www.wowhead.com/quest=27226/hair-of-the-dog -- fixed u need target orc to use spell 
https://www.wowhead.com/quest=27232/the-waters-run-red -- fixed
https://www.wowhead.com/quest=27193/seek-and-destroy -- fixed
https://www.wowhead.com/quest=27194/cornered-and-crushed -- fixed
https://www.wowhead.com/quest=27195/nowhere-to-run -- fixed
https://www.wowhead.com/quest=27290/to-forsaken-forward-command

**Comment by Thordekk** [comment]
https://www.wowhead.com/quest=26998/iterating-upon-success fixed

**Comment by Thordekk** [comment]
Fixed
