### ISSUE TITLE
Can't learn skill with Lithragosa to complete Campaign Quest quest=68798

### ISSUE THREAD

**Issue by Algeth** [Thordekk/Dekk-Core-Donator-Bugtracker#955]
On this quest when required to learn a skill from the NPC 193364, we can't learn the skill with her. 
Therefore impossible to continue this Campaign Quest Line in Dragonflight.

https://www.wowhead.com/quest=68798

**Comment by Thordekk** [comment]
Fixed gossip will fix full quest soon
