### ISSUE TITLE
[Exile Startzone End] Can't complete quest because Apprentice Riding is already known quest=60345

### ISSUE THREAD

**Issue by Algeth** [Thordekk/Dekk-Core-Donator-Bugtracker#957]
https://www.wowhead.com/quest=60345/license-to-ride

When talking to NPC 4752 Riding trainer, Apprentice Riding skill is already known, therefore it's impossible to complete the quest objective and finish this questline which is the end of the Exile's Reach intro for Hord.

**Comment by Thordekk** [comment]
This quest was marked obsolete by Blizzard and cannot be obtained or completed. Will delete soon
