### ISSUE TITLE
[IMPORTANT] Missing NPC can't complete quest 55981

### ISSUE THREAD

**Issue by Algeth** [Thordekk/Dekk-Core-Donator-Bugtracker#961]
When finishing Right Beneath Their Eyes (Quest ID: 55981) , Alliance side, you can't complete it. Captain Garrick is only part of the npc following you but not waiting to complete the quest where she should be. 

https://www.wowhead.com/npc=156961/captain-garrick

**Comment by Thordekk** [comment]
That quest is not needed any  more class quest are removed in exiles
