### ISSUE TITLE
Quest Error

### ISSUE THREAD

**Issue by iroydphp** [Thordekk/Dekk-Core-Donator-Bugtracker#973]
Quest 68798 Error [ Learn the 'Take to the Skies' Skill with Lithragosa ] does not work.

**Comment by iroydphp** [comment]
It appears that the cause of this quest is that the achievement is not processed. achievement=16668

**Comment by Algeth** [comment]
Hi,
The issue is already posted: https://github.com/Thordekk/Dekk-Core-Donator-Bugtracker/issues/955
Thank you for your report,
