### ISSUE TITLE
Dracthyr starter.

### ISSUE THREAD

**Issue by KamiNoEnd** [Thordekk/Dekk-Core-Donator-Bugtracker#991]
If someone Awake Scalecommander Azurathel before you, you cannot get the credit for your quest.

https://www.wowhead.com/quest=64864/awaken-dracthyr

https://www.wowhead.com/npc=183380/scalecommander-azurathel
![image](https://github.com/Thordekk/Dekk-Core-Donator-Bugtracker/assets/49670986/56c3dab2-3090-4ada-ac2b-3e30c3247ba9)

**Comment by KamiNoEnd** [comment]
![image](https://github.com/Thordekk/Dekk-Core-Donator-Bugtracker/assets/49670986/d023003f-c53a-4609-b87a-1370eee6a156)

Crystal Key to open the treasure room doesn't work

**Comment by Thordekk** [comment]
Fixed
